### ISSUE TITLE
Vite breaks on 1.2.1, works on 1.2.0

### ISSUE THREAD

**Issue by dszymon** [oven-sh/bun#16868]
### What version of Bun is running?

oven/bun:1.2.1-slim

### What platform is your computer?

debian based CI/CD runner

### What steps can reproduce the bug?

In a multi-stage dockerfile we have two commands building two different targets:
```dockerfile
FROM build-base AS build-client
RUN bun run build:client # vite build --ssrManifest manifest.client.json

FROM build-base AS build-server
RUN bun run build:server # vite build --ssr ./src/entry-server.ts
```

The build command sometimes hangs, sometimes works as expected when building on macbook (arwin 24.1.0 arm64 arm) using orbstack. On CI/CD debian runner `build:server` command passes, but the `build:client` always fails with the following error:
```
#33 [build-client 1/1] RUN bun run build:client
#33 0.524 $ vite build --ssrManifest manifest.client.json
#33 1.430 vite v6.0.11 building for production...
#33 1.721 transforming...
#33 4.139 ✓ 292 modules transformed.
#33 4.140 x Build failed in 2.63s
#33 4.140 error during build:
#33 4.140 [commonjs--resolver] Transform failed with 1 error:
#33 4.140 /app/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7010:185: ERROR: Unexpected "\x1b"
#33 4.140 file: /app/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js
#33 4.140     at failureErrorWithLog (/app/node_modules/esbuild/lib/main.js:1476:19)
#33 4.140     at <anonymous> (/app/node_modules/esbuild/lib/main.js:755:50)
#33 4.140     at <anonymous> (/app/node_modules/esbuild/lib/main.js:622:9)
#33 4.140     at handleIncomingPacket (/app/node_modules/esbuild/lib/main.js:677:12)
#33 4.140     at readFromStdout (/app/node_modules/esbuild/lib/main.js:600:7)
#33 4.140     at emit (node:events:87:22)
#33 4.140     at addChunk (internal:streams/readable:265:47)
#33 4.140     at readableAddChunkPushByteMode (internal:streams/readable:243:18)
#33 4.140     at handleNumberResult (internal:streams/native-readable:69:18)
#33 4.140     at <anonymous> (internal:streams/native-readable:43:68)
#33 4.233 error: script "build:client" exited with code 1
#33 ERROR: process "/bin/sh -c bun run build:client" did not complete successfully: exit code: 1
#32 [build-server 1/1] RUN bun run build:server
#32 DONE 7.3s
------
 > [build-client 1/1] RUN bun run build:client:
4.140     at <anonymous> (/app/node_modules/esbuild/lib/main.js:755:50)
4.140     at <anonymous> (/app/node_modules/esbuild/lib/main.js:622:9)
4.140     at handleIncomingPacket (/app/node_modules/esbuild/lib/main.js:677:12)
4.140     at readFromStdout (/app/node_modules/esbuild/lib/main.js:600:7)
4.140     at emit (node:events:87:22)
4.140     at addChunk (internal:streams/readable:265:47)
4.140     at readableAddChunkPushByteMode (internal:streams/readable:243:18)
4.140     at handleNumberResult (internal:streams/native-readable:69:18)
4.140     at <anonymous> (internal:streams/native-readable:43:68)
4.233 error: script "build:client" exited with code 1
------
Dockerfile:37
```

It works as expected on both, macbook and CI/CD, when using `oven/bun:1.2.0-slim`

### What is the expected behavior?

```
#32 [build-server 1/1] RUN bun run build:server
#32 0.412 $ vite build --ssr ./src/entry-server.ts
#32 1.287 vite v6.0.11 building SSR bundle for production...
#32 1.514 transforming...
#32 5.000 ✓ 269 modules transformed.
#32 5.220 rendering chunks...
<redacted files>
#32 5.408 ✓ built in 4.04s
#32 DONE 5.8s
#33 [build-client 1/1] RUN bun run build:client
#33 0.421 $ vite build --ssrManifest manifest.client.json
#33 1.244 vite v6.0.11 building for production...
#33 1.511 transforming...
#33 7.133 ✓ 556 modules transformed.
#33 7.487 rendering chunks...
#33 7.811 computing gzip size...
<redacted files>
#33 7.877 ✓ built in 6.56s
#33 DONE 8.1s
```

**Comment by Foorack** [comment]
Can reproduce this as well internally.

**Works:**
```
curl -fsSL https://bun.sh/install | bash -s "bun-v1.2.0"
rm node_modules/ -rf && bun install && bun run --bun build
```

**Breaks:**
```
curl -fsSL https://bun.sh/install | bash -s "bun-v1.2.1"
rm node_modules/ -rf && bun install && bun run --bun build
```

**Comment by Foorack** [comment]
The output of `vite build --debug` is the same on both Bun 1.2.0 and 1.2.1.

It gets to the line "vite v6.0.7 building for production..." and then crashes with:

```bash
 2102 modules transformed.
x Build failed in 10.24s
error during build:
[vite:define] Transform failed with 1 error:
/home/user/Documents/git/project/node_modules/react-router/dist/development/chunk-K6AXKMTT.mjs:6696:10: ERROR: Expected ";" but found "{"
file: /home/user/Documents/git/project/node_modules/react-router/dist/development/chunk-K6AXKMTT.mjs
    at failureErrorWithLog (/home/user/Documents/git/project/node_modules/esbuild/lib/main.js:1476:19)
    at <anonymous> (/home/user/Documents/git/project/node_modules/esbuild/lib/main.js:755:50)
    at <anonymous> (/home/user/Documents/git/project/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/home/user/Documents/git/project/node_modules/esbuild/lib/main.js:677:12)
    at readFromStdout (/home/user/Documents/git/project/node_modules/esbuild/lib/main.js:600:7)
    at emit (node:events:87:22)
    at addChunk (internal:streams/readable:265:47)
    at readableAddChunkPushByteMode (internal:streams/readable:243:18)
    at handleNumberResult (internal:streams/native-readable:69:18)
    at <anonymous> (internal:streams/native-readable:43:68)
```

When building with older Bun 1.2.0, it says "3673 modules transformed".

**Comment by Foorack** [comment]
It's always claiming to crash inside a seemingly random library, sometimes it's "react-router", "tabster" or other modules, so don't think it's anything related to those. The line number is always different, and it's alwasy "Expected X but found RANDOMBYTE".

And for the record I've reproduced everything on Vite `6.0.11` as well, so upgrading Vite to latest does not help.

My current suspicion is with changes in `node:fs` https://bun.sh/blog/bun-v1.2.1#node-fs-compatibility-improvements

**Comment by RiskyMH** [comment]
I believe this is the same issue as #16823, to consolidate issues I'll close as duplicate. If that issue is fixed and this isn't let me know and I can unopen.
