### PR TITLE
jsc: replace MarkedArrayBuffer::from_bytes with an owning constructor

### PR DESCRIPTION
**Pull request by robobun**
### What

`MarkedArrayBuffer::from_bytes(&mut [u8], JSType)` (`src/jsc/array_buffer.rs`) was a safe, public constructor that stored a borrowed slice's pointer in a lifetime-less struct with `owns_buffer: true`. The safe `destroy()` then freed that pointer with the default allocator, so safe code could free a stack buffer:

```rust
let mut bytes = [0u8; 1];
let mut buffer = MarkedArrayBuffer::from_bytes(&mut bytes, JSType::Uint8Array);
buffer.destroy(); // mi_free / libc free on a stack address
```

`to_js` / `to_node_buffer` had the same problem deferred: they install `MarkedArrayBuffer_deallocator` over the stored pointer, so GC frees it later.

All in-tree callers upheld the contract manually (`Box::leak` / `heap::into_raw` a default-allocator `Box<[u8]>`, then reborrow), so there is no user-reachable corruption today; this closes the API-boundary soundness hole.

Fixes #31969

### Fix

- Replace `MarkedArrayBuffer::from_bytes(&mut [u8])` with `MarkedArrayBuffer::from_owned_bytes(Box<[u8]>, JSType)`, built on the existing `ArrayBuffer::from_owned_bytes`, so the ownership transfer is enforced by the type system. This is the same shape #31174 proposed for this type (that PR also covers the separate `ArrayBuffer::from_bytes` hole, #31970, which this PR deliberately does not touch).
- Route `MarkedArrayBuffer::from_string` through it.
- Migrate every caller off the manual leak-and-reborrow dance: `Terminal.rs`, `SubprocessPipeReader.rs`, `shell/subproc.rs`, and `node_fs.rs` (x3, aliased as `Buffer::from_bytes`).
- `to_js` / `to_node_buffer` now take `&mut self` and clear `owns_buffer` at the handoff, so a `destroy()` after the buffer has been given to JSC cannot free the allocation a second time (flagged by review). The `Readable.rs` struct-literal construction was migrated to `from_owned_bytes` for the same reason.
- `destroy()` now skips the free when `byte_len == 0`: an empty `Box<[u8]>` has no backing allocation (its pointer is dangling), so freeing it with the default allocator was itself an invalid free. Same reasoning as the existing empty-case guard in `JSValue::create_buffer_from_box`.

No behavior change: the pointers handed to JSC and the installed deallocators are identical before and after (callers already passed `into_boxed_slice()` allocations).

### Test

`test/regression/marked-array-buffer-ownership-soundness.test.ts` + companion fixture crate, following the compile-fail pattern from #31093: the fixture contains exactly the unsound snippet above, and the test asserts `cargo check --locked` rejects it (`error[E0599]: no associated function or constant named 'from_bytes' found for struct 'MarkedArrayBuffer'`, exit 101). On the unfixed tree the fixture compiles cleanly and the test fails; if a safe borrowed-slice constructor is ever reintroduced, it fails again. Skips when `cargo` or the cppbind codegen output is unavailable (prebuilt-only CI runners). The fixture's `Cargo.lock` is committed and checked with `--locked` so resolution never floats.

### Verification

- Soundness test: fails on unfixed `src/` (fixture compiles), passes with the fix (E0599).
- Existing coverage over the migrated call sites, all passing under the ASAN debug build: `test/js/bun/terminal/terminal.test.ts` (87 pass), `test/js/bun/spawn/spawnSync.test.ts` (6 pass), `test/js/node/fs/fs.test.ts -t readFile` (20 pass) and `-t readlink` (4 pass).
- Standalone-graph `readFileSync` Buffer path verified with a compiled executable reading an embedded file.
- Empty-buffer paths (`readFileSync` of an empty file, multipart FormData with an empty file blob) verified under ASAN.
- `cargo clippy -p bun_jsc -p bun_runtime --no-deps` clean.

### CODE REVIEW

File: test/regression/marked-array-buffer-ownership-soundness.test.ts [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+const fixtureDir = join(import.meta.dir, "marked-array-buffer-ownership-soundness-fixture");
+// bun_jsc's build script needs the cppbind codegen output (produced by
+// `bun bd` / `bun run build`); skip on runners that only have a prebuilt
+// bun binary and no build tree.
+const codegenDir = join(import.meta.dir, "../../build/debug/codegen");
+const hasCodegen = existsSync(join(codegenDir, "cpp.rs"));
+
+test.skipIf(!cargo || !hasCodegen)(
+  "MarkedArrayBuffer cannot adopt a borrowed slice as owned storage",
+  { timeout: 10 * 60 * 1000 }, // first run type-checks bun_jsc's dep graph; cached after
```
[the remark this answers is not in the document]
Comment (robobun) [reply test/regression/marked-array-buffer-ownership-soundness.test.ts:38]: Keeping the budget: bun's default per-test timeout is 5s, and the first run of this test type-checks bun_jsc's dependency graph from scratch. Measured cold on this branch: 25.2s in a warm-registry container, and the precedent test in #31093 budgets the same 10 minutes for the same reason (bun_core's graph). Without the override the test fails on every cold runner. This is a budget for a single long compile, not a sleep.

File: test/regression/marked-array-buffer-ownership-soundness.test.ts [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+  async () => {
+    await using proc = spawn({
+      // `--locked` so the fixture's committed Cargo.lock pins the transitive
+      // dep graph — the assertions below only fire for the intended
+      // resolution error, not for registry drift.
+      cmd: [cargo!, "check", "--locked", "--message-format=short"],
```
[the remark this answers is not in the document]
Comment (robobun) [reply test/regression/marked-array-buffer-ownership-soundness.test.ts:44]: Kept --locked for hermetic resolution, and made the stale-lockfile case self-diagnosing in d156042275: the test now throws with the regeneration command (cd <fixture> && cargo update) plus cargo's output, the assertions are direct toContain calls on the combined output (so any mismatch prints it), and the fixture Cargo.toml documents the regeneration step.

File: src/jsc/array_buffer.rs [hunk 3]
```diff
@@ -977,13 +979,19 @@ impl MarkedArrayBuffer {
...
             self.owns_buffer = false;
-            // SAFETY: buffer.ptr was allocated by the global allocator (heap::alloc / allocator.dupe).
-            unsafe { bun_alloc::default_alloc::free(self.buffer.ptr.cast()) };
+            // An empty `Box<[u8]>` has no backing allocation — `from_owned_bytes`
+            // stored its dangling pointer, so there is nothing to free (same
+            // reasoning as `JSValue::create_buffer_from_box`).
+            if self.buffer.byte_len != 0 {
+                // SAFETY: `owns_buffer` is only set by `from_owned_bytes`, which
+                // took the pointer from a non-empty default-allocator `Box<[u8]>`.
+                unsafe { bun_alloc::default_alloc::free(self.buffer.ptr.cast()) };
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/jsc/array_buffer.rs:994]: Took option A in d156042275: the Readable.rs struct literal now goes through MarkedArrayBuffer::from_owned_bytes, so from_owned_bytes is the only remaining owns_buffer: true producer and the SAFETY comment is literally true (rg 'owns_buffer: true' src/ matches only the constructor).
