### ISSUE TITLE
`events.setMaxListeners` doesn't work with `AbortSignal`

### ISSUE THREAD

**Issue by Azarattum** [oven-sh/bun#3306]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

Trying to set max listeners of an AbortSignal throws an error.
```js
const ac = new AbortController();
require("node:events").setMaxListeners(1, ac.signal);
```

### What is the expected behavior?

As per [node documentation](https://nodejs.org/api/events.html#eventssetmaxlistenersn-eventtargets) `events.setMaxListeners` should accept any `EventTarget` as arguments. Since `AbortSignal` [inherits from `EventTarget`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal#instance_properties) setting its max listeners should be supported. The code provided above works fine in Node (tested in `v20.3.0`).

### What do you see instead?

An error is thrown:
```
89 |   validateNumber(n, "setMaxListeners", 0);
90 |   var length;
91 |   if (eventTargets && (length = eventTargets.length))
92 |     for (let i = 0;i < length; i++)
93 | 
94 |       eventTargets[i].setMaxListeners(n);
         ^
TypeError: eventTargets[i].setMaxListeners is not a function. (In 'eventTargets[i].setMaxListeners(n)', 'eventTargets[i].setMaxListeners' is undefined)
      at node:child_process:94:6
      at ~/build/a.cjs:2:0
```

### Additional information

This breaks compatibility with libraries that rely on setting max listeners for abort signals.

**Comment by Azarattum** [comment]
The issue is still preset in Bun `1.0`.

**Comment by Azarattum** [comment]
I think this has been fixed in Bun [1.1.25](https://bun.sh/blog/bun-v1.1.25#execa-now-works). Cannot reproduce on the latest version (1.1.27 at the time)
