### ISSUE TITLE
TS Type error when importing a .txt file

### ISSUE THREAD

**Issue by fturmel** [oven-sh/bun#9276]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

Since 1.0.26, I'm seeing the type error `TS2307 (Cannot find module './input.txt' or its corresponding type declarations.)` when importing a .txt file.

![CleanShot 2024-03-06 at 10 09 03@2x](https://github.com/oven-sh/bun/assets/4009209/87968dab-5f47-45d9-a82a-144e6052b5f3)

The error goes away when reverting the type definitions to `"bun-types": "1.0.25"`

![CleanShot 2024-03-06 at 10 12 55@2x](https://github.com/oven-sh/bun/assets/4009209/c25a5229-bc30-4543-8a1c-c146b3da4e1c)

### Additional information

Possibly introduced by #8195?

I also tried using `@types/bun`, but the same behavior was introduced in version 1.0.5

**Comment by fturmel** [comment]
It seems like moving these module declarations...

https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/packages/bun-types/globals.d.ts#L144-L152

..._inside_ the global module declaration fixes the type regression.

https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/packages/bun-types/globals.d.ts#L154

However with Bun v1.1.5 just released and support for import attributes (`import ... with {type:'text'}`, there's a new class of import type errors that will need a solution.

**Comment by alii** [comment]
Thanks for reporting!

According to the [TypeScript Docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html) import assertions don't have any impact on type checking.

> The contents of these attributes are not checked by TypeScript since they’re host-specific, and are simply left alone so that browsers and runtimes can handle them (and possibly error).

So looks like were just missing a `*.txt` declaration in the types. Will get this fixed!

**Comment by fturmel** [comment]
Thanks for following up @alii. I'm actually not able to reproduce this problem anymore. I think it got fixed in `bun-types: "1.1.42"` or earlier, that's around the time I realized I was able to delete my own `types.d.ts` file and the types were correct again.

![Image](https://github.com/user-attachments/assets/da0239b7-bbd0-44e2-b84b-b254f8f0860c)

Sounds like there won't be type assertion based on import attributes either? Feel free to close this issue if there's nothing more to investigate here!

**Comment by alii** [comment]
Oh great, was just about to look into reproducing this. Glad it's fixed, thanks for letting me know!
