### ISSUE TITLE
Unable to create svelte project with bunx

### ISSUE THREAD

**Issue by 0x00ff7f** [oven-sh/bun#5226]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

WSL (Microsoft Windows NT 10.0.22621.0 x64)

### What steps can reproduce the bug?

When I try to create a Svelte project with Bun, the bunx command crashes.

Snippet:
`bunx create-svelte my-project`

### What is the expected behavior?

Getting a new Svelte Project with Bun.

### What do you see instead?

file:///tmp/create-svelte@latest--bunx/node_modules/create-svelte/bin.js:19
        const dir = await p.text({
                    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error: "create-svelte" exited with code 1 (SIGHUP)

### Additional information

I've tried with a Next project, and it was no problem. My Next project is up and running. This only happens when I try creating my Svelte project. I tried in both v1.0.0 and 1.0.1.

**Comment by Kireobat** [comment]
I am having the same issue, but I ran this command instead:

`bun create svelte@latest my-app `

Same error

```
file:///tmp/create-svelte@latest--bunx/node_modules/create-svelte/bin.js:19
        const dir = await p.text({
                    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error: "create-svelte" exited with code 1 (SIGHUP)
```

edit:

I am having the same issue with npm

**Comment by maietta** [comment]
Same.

Using Ubuntu 22.02 under WSL:

Windows 11 Home
Version	22H2
OS build	22621.2283

Under Ubuntu 22.02:
- Bun 1.0.1
- Node v12.22.9
- NPM 9.8.0

**Comment by n00ki** [comment]
I'm having the same issue when trying to run `bun create svelte@latest myapp`.

```
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/private/var/folders/sc/3q988q7d36vb9mfldl4nb3vj5hfx51/T/dlx-5713/5/node_modules/create-svelte/bin.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.1
error: "create-svelte" exited with code 1 (SIGHUP)
```

* Apple MBP - Ventura 13.4
* Node v18.16.1

**Comment by Kireobat** [comment]
I was now able to run these commands after updating node to v18.18.0 and upgrading bun to 1.0.3

`bun create svelte@latest`

`npm create svelte@latest`
