### ISSUE TITLE
`require('node:module')._preloadModules` is not a function.

### ISSUE THREAD

**Issue by imcm7** [oven-sh/bun#6227]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 6.2.0-33-generic x86_64 x86_64

### What steps can reproduce the bug?

https://github.com/imcm7/nuxt-db/tree/main/server
install mikro-orm and `bun -b db:update`

### What do you see instead?

@Jarred-Sumner with -b also not run, some days ago all was ok

```
process[exports.REGISTER_INSTANCE] = service;
132 |     // Register the extensions.
133 |     registerExtensions(service.options.preferTsExts, service.extensions.compiled, service, originalJsHandler);
134 |     (0, cjs_resolve_hooks_1.installCommonjsResolveHooksIfNecessary)(service);
135 |     // Require specified modules before start-up.
136 |     module_1.Module._preloadModules(service.options.require);
        ^
TypeError: module_1.Module._preloadModules is not a function. (In 'module_1.Module._preloadModules(service.options.require)', 'module_1.Module._preloadModules' is undefined)
      at register (/home/node/nuxt/node_modules/ts-node/dist/index.js:136:4)
      at /home/node/nuxt/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:115:28
      at registerTsNode (/home/node/nuxt/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:104:32)
      at /home/node/nuxt/node_modules/@mikro-orm/cli/CLIConfigurator.js:28:33
      at processTicksAndRejections (:55:76)
error: script "db:update" exited with code 1 (SIGHUP)

``

### Additional information

_No response_

**Comment by imcm7** [comment]
you can pass all you want but it not work https://github.com/oven-sh/bun/issues/6226

**Comment by imcm7** [comment]
Some think changed and broke

**Comment by B4nan** [comment]
I think you should drop the [`useTsNode` option](https://github.com/imcm7/nuxt-db/blob/main/package.json#L55) from your package.json, that option triggers the `ts-node.register()` which you don't need with bun. Instead, you need the new `alwaysAllowTs` option, which will make the ORM respect the TS files, but as opposed to the `useTsNode` it won't trigger the `ts-node.register()` call.

**Comment by imcm7** [comment]
@B4nan but I use bun node anlways, I mean without --bun.
Now I use `bun run dev` not pnpm because with bun it work faster in dev mode, I think some bug in nuxt.

**Comment by imcm7** [comment]
@B4nan with pnpm also not work

**Comment by notramo** [comment]
Is this issue still relevant?
`commitlint` works in Bun 1.0.14, which was previously crashing because of this bug.

**Comment by Jarred-Sumner** [comment]
@paperdave fixed this some time ago

**Comment by notramo** [comment]
@Jarred-Sumner I checked it again, and `commitlint` crashes if the `node_modules` were installed by `pnpm` (but works if it was installed by Bun). Since the Bun built-in package manager is highly unusable for complex scenarios (e.g. workspaces), it's very likely that some projects use `pnpm` for package management, and Bun for everything else.

**Comment by paperclover** [comment]
this issue is not fixed as of 1.0.14. the work seems to be started on pr here: #6188. i did not have time to finish it up at the time, and i am now focusing on the windows build. someone else will have to pickup implementing the `node:module` internal apis.

**Comment by PaulRBerg** [comment]
Getting this error in a GitPod instance of my [Hardhat template](https://github.com/PaulRBerg/hardhat-template):

```
An unexpected error occurred:

131 |     process[exports.REGISTER_INSTANCE] = service;
132 |     // Register the extensions.
133 |     registerExtensions(service.options.preferTsExts, service.extensions.compiled, service, originalJsHandler);
134 |     (0, cjs_resolve_hooks_1.installCommonjsResolveHooksIfNecessary)(service);
135 |     // Require specified modules before start-up.
136 |     module_1.Module._preloadModules(service.options.require);
          ^
TypeError: module_1.Module._preloadModules is not a function. (In 'module_1.Module._preloadModules(service.options.require)', 'module_1.Module._preloadModules' is undefined)
      at register (/workspace/hardhat-template/node_modules/ts-node/dist/index.js:136:5)
      at /workspace/hardhat-template/node_modules/ts-node/register/transpile-only.js:1:1
      at loadTsNode (/workspace/hardhat-template/node_modules/hardhat/internal/core/typescript-support.js:71:5)
      at /workspace/hardhat-template/node_modules/hardhat/internal/cli/cli.js:127:17
      at main (/workspace/hardhat-template/node_modules/hardhat/internal/cli/cli.js:75:23)
      at /workspace/hardhat-template/node_modules/hardhat/internal/cli/cli.js:305:1
      at /workspace/hardhat-template/node_modules/hardhat/internal/cli/bootstrap.js:15:1
```

**Comment by ashayp22** [comment]
Getting this error with macOS arm64, Bun v1.1.17 and [threads.js v1.7.0](https://threads.js.org/usage) when setting up a pool with thread.js.

### Error

<img width="1247" alt="Screenshot 2024-07-03 at 1 59 11 PM" src="https://github.com/oven-sh/bun/assets/21179174/21533b08-c92e-44af-8b6c-01064383c3e1">


### Setup

```typescript
// index.ts
import { spawn, Pool, Worker } from "threads";

const pool = Pool(
  () => spawn(new Worker("./workers/add")),
  8
);
```

```typescript
// workers/add.ts
import { expose } from "threads/worker"

expose(function add(a, b) {
  return a + b
})
```

**Comment by Jarred-Sumner** [comment]
Confirming this is not fixed, and also probably very easy to implement.
