### ISSUE TITLE
Reading text file line by line

### ISSUE THREAD

**Issue by woxxo** [oven-sh/bun#6692]
### What is the problem this feature would solve?

AI assistant replies to the inquiry **"read file line by line"** like this:

_To read a file line by line in Bun, you can use the Bun.file().lines() API. This API allows you to asynchronously iterate over each line of the file. Here is an example:_

```javascript
const foo = Bun.file("foo.txt"); 

for await (const line of foo.lines()) {
  console.log(line);
}
```
_In this sample, substitute "foo.txt" with the actual path to the file you want to read[1](https://bun.sh/docs/api/file-io).
Sources: File I/O – [API](https://bun.sh/docs/api/file-io)_

But this example is not working in Bun 1.0.7!
```
3 | for await (const line of foo.lines()) {
                             ^
TypeError: foo.lines is not a function. (In 'foo.lines()', 'foo.lines' is undefined)
```

### What is the feature you are proposing to solve the problem?

It would be useful to have an interface to read text files as text lines, not as binary stream. Something like this `.lines()` method mentioned above.

### What alternatives have you considered?

In Node.js it is possible:
```javascript
const readline = require("readline");
const rl = readline.createInterface({ input });
rl.on("line", (line) => {
  // proccess line
})
```

**Comment by Electroid** [comment]
Bun does not actually implement `Bun.file().lines()`, sorry that the AI mislead you.

**Comment by Lippiece** [comment]
I'm sorry, is it actually not planned? It would be nice to have simple methods to read lines.

> Bun does not actually implement `Bun.file().lines()`, sorry that the AI mislead you.
