### ISSUE TITLE
`ReadableStream` is not working in `bun test` after `1.0.4`

### ISSUE THREAD

**Issue by aralroca** [oven-sh/bun#6289]
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Try to run this test:

```ts
it('ReadableStream is not working in bun test after 1.0.4', async () => {
  const stream = new ReadableStream({
    start(controller) {
      controller.enqueue("a");
      controller.enqueue("b");
      controller.enqueue("c");
      controller.close();
    },
  });
  const result = await Bun.readableStreamToText(stream);

  expect(result).toEqual("abc");
})
```

### What is the expected behavior?

 `stream.getReader` function should exist and the test should work as expected.

### What do you see instead?

Error:

```sh
1 | (async function (stream, sink, isNative) {"use strict";
                                                                                     ^
TypeError: undefined is not a function
      at readStreamIntoSink (:1:32)
      at readableStreamIntoText (:1:20)
```

Neither is possible to access to `stream.getReader` function.

**Comment by aralroca** [comment]
I realized that only is happening with `happy-dom`. 

With:

```ts
  beforeAll(() => {
    GlobalRegistrator.unregister();
  })

  afterAll(() => {
    GlobalRegistrator.register();
  })
```

Now works fine.

**Comment by aralroca** [comment]
I'm going to close it because is problem of `happy-dom` version and not Bun.

**Comment by Amatewasu** [comment]
@aralroca Thank you a lot for yout ticket and your insights.

I think I am running into a similar issue.

When I run `bun test`:
```
src/app.test.tsx:
1 | (function (){"use strict";// build/tmp_modules/thirdparty/node-fetch.ts
                       ^
TypeError: undefined is not an object or null
      at node-fetch:1:20
      at processTicksAndRejections (:61:76)
```

```bash
bun -v
1.0.11
```
```
"@happy-dom/global-registrator": "12.6.0"
```

I struggle to understand your fix (or how to apply it).
I have the file `happydom.ts`:
```ts
import { GlobalRegistrator } from "@happy-dom/global-registrator";

GlobalRegistrator.register();
```
that is preloaded thanks to the following `bunfig.toml` configuration file:
```toml
[test]
preload = ["./happydom.ts", "./bunSvgPlugin.ts"]
```

**Comment by Amatewasu** [comment]
For people reading this issue, it looks like upgrading happy-dom to the latest version "12.10.3" gets rid of the error.
