### ISSUE TITLE
0.8.0 Breaks sodium-plus (via SodiumPlus.auto())

### ISSUE THREAD

**Issue by etinquis** [oven-sh/bun#4303]
### What version of Bun is running?

0.8.0+c60385716b7a7ac9f788cdf7dfe37250321e0670

### What platform is your computer?

Docker container (Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown)

### What steps can reproduce the bug?

index.ts:
```
import { SodiumPlus } from 'sodium-plus';

const sodium = await SodiumPlus.auto();
console.trace(sodium.backend.backendName);
const buf = await sodium.randombytes_buf(20);
console.trace(buf);
```

`docker run -v .:/app --rm -it --workdir /app oven/bun:0.8.0 sh`
`bun install`
`bun run index.ts`

Output:
```
SodiumNativeBackend
      at /app/index.ts:4:0
708 |      * @param {number} number
709 |      * @return {Promise<Buffer>}
710 |      */
711 |     async randombytes_buf(number) {
712 |         let buf = Buffer.alloc(number);
713 |         this.sodium.randombytes_buf(buf);
            ^
TypeError: this.sodium.randombytes_buf is not a function. (In 'this.sodium.randombytes_buf(buf)', 'this.sodium.randombytes_buf' is undefined)
      at /app/node_modules/sodium-plus/lib/backend/sodiumnative.js:713:8
      at randombytes_buf (/app/node_modules/sodium-plus/lib/backend/sodiumnative.js:711:26)
      at /app/node_modules/sodium-plus/lib/sodiumplus.js:1073:21
```

### What is the expected behavior?

`docker run -v .:/app --rm -it --workdir /app oven/bun:0.7.0 sh`
`bun install`
`bun run index.ts`

Output:
```
LibsodiumWrappersBackend
      at /app/index.ts:4:0
Buffer(20) [ 250, 101, 31, 26, 43, 152, 28, 142, 105, 233, 173, 234, 252, 172, 254, 165, 164, 61, 202, 67 ]
      at /app/index.ts:6:0
```

### Additional information

SodiumPlus auto function: https://github.com/paragonie/sodium-plus/blob/c935781f34509e962894f40e52a02fe1ee527b7d/lib/sodiumplus.js#L65C40-L65C40
It appears to be successfully resolving 'sodium-native' in https://github.com/paragonie/sodium-plus/blob/c935781f34509e962894f40e52a02fe1ee527b7d/lib/backend/sodiumnative.js#L6C19-L6C19 but with a reduced API surface (I guess?), where it fell back to libsodium-wrapper in 0.7.0.

**Comment by etinquis** [comment]
I'm guessing this may be related to #4170, #3652

**Comment by Jarred-Sumner** [comment]
This appears to have worked in Bun v0.1.1 - Bun v0.1.7, but not any version after that:


```js
# v0.1.7
LibsodiumWrappersBackend
      at /Users/jarred/Desktop/sody.js:4:0
Uint8Array(20) [ 79, 19, 175, 190, 79, 60, 253, 179, 6, 44, 5, 60, 78, 102, 113, 217, 169, 103, 109, 28 ]
      at /Users/jarred/Desktop/sody.js:6:0

# v0.8.1
❯ bun sody.js
SodiumNativeBackend
      at /Users/jarred/Desktop/sody.js:4:0
708 |      * @param {number} number
709 |      * @return {Promise<Buffer>}
710 |      */
711 |     async randombytes_buf(number) {
712 |         let buf = Buffer.alloc(number);
713 |         this.sodium.randombytes_buf(buf);
            ^
TypeError: this.sodium.randombytes_buf is not a function. (In 'this.sodium.randombytes_buf(buf)', 'this.sodium.randombytes_buf' is undefined)
      at /Users/jarred/Desktop/node_modules/sodium-plus/lib/backend/sodiumnative.js:713:8
      at randombytes_buf (/Users/jarred/Desktop/node_modules/sodium-plus/lib/backend/sodiumnative.js:711:26)
      at /Users/jarred/Desktop/node_modules/sodium-plus/lib/sodiumplus.js:1073:21

```

I think it used the WASM backend before

**Comment by etinquis** [comment]
@Jarred-Sumner  My fault for not including the packages.json as well.  I'm not including sodium-native in my version:
```
{
  "dependencies": {
    "sodium-plus": "^0.9.0"
  }
}
```
I can indeed reproduce the failure on 0.7.0 if sodium-native is included, but if it's not then it works and falls back to the sodium wrapper version.

**Comment by etinquis** [comment]
FWIW, neither the working 0.7.0 nor the failing 0.8.0 wind up with sodium-native in node_modules after install:
```
> docker run --rm -it -v .:/app --workdir /app oven/bun:0.8.0 sh
# bun --version
0.8.0
# bun install 
bun install v0.8.0 (c6038571)
 + sodium-plus@0.9.0

 11 packages installed [634.00ms]
# ls node_modules
base64-js  big-integer  buffer  ieee754  is-typedarray  libsodium  libsodium-wrappers  poly1305-js  sodium-plus  typedarray-to-buffer  xsalsa20
# bun run index.ts
SodiumNativeBackend
      at /app/index.ts:4:0
708 |      * @param {number} number
709 |      * @return {Promise<Buffer>}
710 |      */
711 |     async randombytes_buf(number) {
712 |         let buf = Buffer.alloc(number);
713 |         this.sodium.randombytes_buf(buf);
            ^
TypeError: this.sodium.randombytes_buf is not a function. (In 'this.sodium.randombytes_buf(buf)', 'this.sodium.randombytes_buf' is undefined)
      at /app/node_modules/sodium-plus/lib/backend/sodiumnative.js:713:8
      at randombytes_buf (/app/node_modules/sodium-plus/lib/backend/sodiumnative.js:711:26)
      at /app/node_modules/sodium-plus/lib/sodiumplus.js:1073:21
```

Is there a global copy of sodium-native in the 0.8.0 container that wasn't there before?  Where would I look?

**Comment by pcfreak30** [comment]
See https://github.com/oven-sh/bun/issues/4170#issuecomment-1694484031

**Comment by Electroid** [comment]
Closing as duplicate of #4170
