### ISSUE TITLE
Bun 0.2.0 crashes on MacOS Mojave [check ticket -> #1266]

### ISSUE THREAD

**Issue by chrisAXZA** [oven-sh/bun#1330]
### Version

0.2.0

### Platform

local 18.7.0 Darwin Kernel Version 18.7.0 root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

As commented by [kt3k](https://github.com/kt3k): run any script with` bun run script.js`

### How often does it reproduce? Is there a required condition?

semper

### What is the expected behavior?

Run script

### What do you see instead?

```
dyld: lazy symbol binding failed: Symbol not found: _pthread_self_is_exiting_np
  Referenced from: ... (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _pthread_self_is_exiting_np
  Referenced from: ... (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

Crash at 0xBAF3F81801000000

----- bun meta -----
Bun v0.2.0 (b542921f) macOS x64 18.7.0
RunCommand: 
Elapsed: 26ms | User: 3ms | Sys: 24ms
RSS: 3.94MB | Peak: 3.94MB | Commit: 67.11MB | Faults: 581
----- bun meta -----
```

**Comment by shakfu** [comment]
I am running on macOS Catalina 10.15.7 and after upgrade from 0.13 to 0.20 have been experiencing the same problems:

```bash
$ cat serve.js
// http.js
export default {
  port: 3000,
  fetch(request) {
    return new Response("Welcome to Bun!");
  },
};

$ bun --version
0.2.0

$ bun run serve.js
dyld: lazy symbol binding failed: Symbol not found: _pthread_self_is_exiting_np
  Referenced from: $HOME/.bun/bin/bun (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _pthread_self_is_exiting_np
  Referenced from: $HOME/.bun/bin/bun (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib


Crash at 0x5EF0F21A01000000


----- bun meta -----
Bun v0.2.0 (b542921f) macOS x64 19.6.0
RunCommand:
Elapsed: 1ms | User: 1ms | Sys: 3ms
RSS: 3.82MB | Peak: 3.82MB | Commit: 67.11MB | Faults: 0
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by shakfu** [comment]
This is still an issue in v0.2.1

```bash
$ bun --version
0.2.1

$ bun run serve.js
dyld: lazy symbol binding failed: Symbol not found: _pthread_self_is_exiting_np
  Referenced from: $HOME/.bun/bin/bun (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _pthread_self_is_exiting_np
  Referenced from: $HOME/.bun/bin/bun (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib


Crash at 0x5E90171001000000


----- bun meta -----
Bun v0.2.1 (1835e4b9) macOS x64 19.6.0
RunCommand:
Elapsed: 10ms | User: 2ms | Sys: 5ms
RSS: 3.90MB | Peak: 3.90MB | Commit: 67.11MB | Faults: 115
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by chrisAXZA** [comment]
Probably will take some time in order to be solved.
[Jarred-Sumner](https://github.com/Jarred-Sumner) => “webkit has dropped support for their memory allocator on macOS 10.xx as of the most recent webkit upgrade - need to think on what to do about this”

**Comment by shakfu** [comment]
@chrisAXZA thanks and understood.

**Comment by shakfu** [comment]
@chrisAXZA 

Incidentally, I recently upgraded to macOS Monterey v12.6.1 (x86_64) and retried the above test on `bun 0.2.2` and it worked! :smile:

**Comment by Electroid** [comment]
Thanks for reporting this! We're going to track this issue here: #1266
