### ISSUE TITLE
error TS2339: Property 'trailingZeroDisplay' does not exist on type 'NumberFormatOptions'

### ISSUE THREAD

**Issue by esciullo** [oven-sh/bun#19364]
### What version of Bun is running?

1.2.10+db2e7d7f7
with "@types/bun": "1.2.10"

### What platform is your computer?

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Typescript code:
```typescript 
Intl.NumberFormatOptions["trailingZeroDisplay"]
```

Bun command:
```bash
bun --bun tsc --build
```
```bash
error TS2339: Property 'trailingZeroDisplay' does not exist on type 'NumberFormatOptions'
error: "tsc" exited with code 1
```

### What is the expected behavior?

Build properly

### What do you see instead?

```error TS2339: Property 'trailingZeroDisplay' does not exist on type 'NumberFormatOptions'```

### Additional information

Works fine with version <= 1.2.4

**Comment by alii** [comment]
Thanks for reporting - could you try specifying a target of 2023 or later in tsconfig please?

**Comment by rhuanbarreto** [comment]
https://codesandbox.io/p/sandbox/repro-trailing-zero-3g94p2

**Comment by alii** [comment]
Could you please try updating to TypeScript 5.8.3 in `package.json` and then running `bun install`? It looks like this might have been a more recent addition to TypeScript's lib files.

It's acceptable to keep `ESNext` as the target here, so no change necessary there.

**Comment by rhuanbarreto** [comment]
I did it in the sandbox. No luck.

**Comment by alii** [comment]
Will close this as the issue actually concerns specific project configuration and not @types/bun — but still happy to assist if the above suggestions are not working for you! Thanks
