### PR TITLE
Fixes expect.extend on prototypes

### LINKED ISSUE #16434: RTL-extended DOM matchers missing/fail tests on Bun v1.1.43, work on Bun v1.1.42
### What version of Bun is running?

1.1.43+76800b049

### What platform is your computer?

Linux 6.12.9-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

On Bun v1.1.43:
1. Extend the React Testing Library DOM matchers as outlined in https://bun.sh/guides/test/testing-library (specifically the section involving `@testing-library/jest-dom/matchers`)
2. Create a test that uses an extended matcher (e.g. `toHaveClass` as in `expect(...).toHaveClass(...)`)
3. Run test, get output similar to `TypeError: expect(document.documentElement).toHaveClass is not a function. (In 'expect(document.documentElement).toHaveClass("dark")', 'expect(document.documentElement).toHaveClass' is undefined)`

Test above on Bun v1.1.42 and make sure tests pass

### What is the expected behavior?

Tests pass (extended DOM matchers recognized)

### What do you see instead?

Tests fail (extended DOM matchers not recognized)

### Additional information

**Screenshots:**

The below use [proto](https://github.com/moonrepo/proto).

Executed with `proto run bun 1.1.42 -- test`:

Image

Executed with `proto run bun 1.1.43 -- test`:

Image
Image

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #16434

### How did you verify your code works?

Test

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 11:35 PM PT - Jan 15th, 2025</sup></div>

@Jarred-Sumner, your commit 7bef4af1a2fd06e84c8635237e56867f93378e84 is building: [`#9757`](https://buildkite.com/bun/bun/builds/9757)
