### ISSUE TITLE
Bun types not supporting Typescript 5.7 TypedArrays now being generic over ArrayBufferLike

### ISSUE THREAD

**Issue by nathankleyn** [oven-sh/bun#14892]
### What version of Bun is running?

1.1.32+fe8d0079e

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

1. Run a typecheck of the following code:

```ts
Buffer.from("foo").equals(Buffer.from("bar"))
```

### What is the expected behavior?

It should typecheck successfully and work.

### What do you see instead?

There is a type error:

```
Argument of type 'Buffer' is not assignable to parameter of type 'Uint8Array'.
  The types returned by 'entries()' are incompatible between these types.
    Type 'IterableIterator<[number, number]>' is missing the following properties from type 'ArrayIterator<[number, number]>': map, filter, take, drop, and 9 more.ts(2345)
```

But the actual call works.

### Additional information

This feature was introduced in Typescript 5.7 beta:

https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-beta/#typedarrays-are-now-generic-over-arraybufferlike

I'm not sure what the policy is surrounding beta features from Typescript, but figure worth raising a bug just in case because the types are preventing making a call that is actually valid in the underlying platform. I can work around it by pinning a newer version of `@types/node`, not sure if that's the expected way to do things though.

**Comment by guest271314** [comment]
I don't think Bun uses Microsoft TypeScript for parsing. I'm not sure if type checking happens at all in Bun for `.ts` files. 

`@types/node` and `@types/bun` are not consistent, have overlapping definitions, and will throw when `tsc` is used for type checking, when `@types/node` and `@types/bun` are used in the same script.

**Comment by guest271314** [comment]
AFAICT there's no general way to check Bun types within Bun. 

When trying to use `deno check` we'll get to a point where this throws

```
error: Module not found "https://raw.githubusercontent.com/oven-sh/bun/497fa59bf02dc5374ca306d5eaaf9ae03585272b/packages/bun-types/fetch".
    at https://raw.githubusercontent.com/oven-sh/bun/497fa59bf02dc5374ca306d5eaaf9ae03585272b/packages/bun-types/globals.d.ts:1962:21

```

**Comment by guest271314** [comment]
> Bun doesn't support type checking itself. However it does provide the `bun-types` or `@types/bun` package which provides types for Bun specific features plus re-exports the types for Node parity features by having a depednency on `@types/node`. This package is designed to be added as a depdencny so that Typescript (specifically `tsc`) can then correctly check types for stuff you intend to run on Bun.

Unfortunately Bun types conflict with Node.js types. I had to use the Microsoft TypeScript resizable implementation from the unmerged PR before version 5.7 was released. 

`tsc` can't handle some Bun types and Node.js types in the same script. Even using version 5.7.

I have to use either `// @ts-ignore` and/or `--skipLibCheck` for `tsc` to not throw.

Basically every JavaScript runtime implements TypeScript parsing differently. Just like every JavaScript runtime is different. Deno is still using `tsc` version 5.6.2 in the canary build.


I think you can import types from anywhere, and include `.d.ts` from Microsoft TypeScript or anywhere else in the `.ts` file.

Example https://github.com/guest271314/NativeMessagingHosts/blob/main/nm_typescript.ts#L1C1-L69C2. See [TypeScript Playground](https://www.typescriptlang.org/play/?target=99&jsx=0&ts=5.7.0-dev.20241023#code/JYWwDg9gTgLgBGKEDGBTAzuuAzJI4BEAdhACaoBciKG6BA3AFCiSyHkkOPIRHrxQArkRihKcflGBEA5nAC8cIgEMAbsBnKY0AHSD0qKAEEZqEUx594AI0HZshinCNQoygJ4AhOw6gKlqADuzq4e3vaGABQADAA0cADecCDKAB6e7jCoADJmMjAAFk4AjNEATAAscABU1XBlcAC+AJQWvPxw6kFOACJaygBqwEH+RCN9MIPDgZG2EVCt3O3wZjzkUE4AKqipMACiRGuGoyPbuwdHUJGLjAA2qAKoyqTK1vdOAHJkqABSAMo6ABKT1IfxgUCe+AAZIkcKQnNEmnAAD5wYHPV73MEQ5QgAA8AFVpDAABwuNzuAB8sUYcDggSkkze4gA6ozMahsZDCcSyaEqTS6TtgDAnNcFJTOhBgKR-OL5JKEo0mMxsHBIkIRGIdPxlLB0CyRQVIgQemYIARms1ErT1UkcS9mUjFGaSDqYKRpIs6ZEkgyRRznXBXRB3aQIIIYN67XBhfBGv4Q4tGoxVerNaIQKh3XqYAajSavuRLdaEraHYHFNQ0Jgw9ImHT-Uz7idgmyA8yubjfbbG4zUJFVMpboJUKXe3SEEga+gwxGYDomwOhyOxw3J41BU14mNggBhCMiACKo8E0hk2K0qBk7l9cAKGgKLKvUAAsnqANZOACSRGw0hFdwmitdc7zjINq1oZNU2ANUNWETNs11fVDUKE1vCIEsbTpAB6HC4AJdBzzgawIEKOAeBALMRCwLQ4EKVAJFxRjELgcMMCIAByeBAmgD8cGgNjzTgW5iXiDgIAogpUGQD9bTwoSSAAWlEkQlI0EgISUCAlOEcg1SUpTnFUaVZRYaBRFkOAAAEYHcMAMBw2wiDgAArfR4GwQTVMsmR5Pw2z0HUmRNNQcsQUrOAMJ0f97hNHDyFUHD+E9TDmndHEQGudcm0i3c4HbZtOXBbkiREPkKUpHtJzgZR0HcQ56X7Qdh1Hccatw-CJJU4lgtC7TdKIfSJ06my8z66Awo62rAmUEUouERdmuilL53iFc2vXOlN1tTcAn3Q8YBPVAz1kS8shvO8HxkJ8X3fKAvzgX9-yIQDgOjMDUnmhMq2nKCmBTRhsGEZBRF4WNDm+V9aGUUxIizTBYfECBrFcmSoycMrSXJDxsLgCEYEEKAXNWb4oB0UnyEif4AHkPgy89YNvBH0CRkDGEBuqGuQHAQbBog6lMGBocRuHmicIx6sOABxMxDC0aAeXKnGqTx+54BZpHclkQonCIQQQGsY5FGidd1fxkEafsAxRSUA2jb8E31y8vxlFm+bInNzXTDgCA1QrZl2snWD1TmXwdGsTIcjycj5DjuBEShGFvejnWCgUePoiDmqw8MHQISIgAvAcKmjGqXfVc3gH8U24GrvE4Aqeg64Aahb7OOq6QIdQeLGSUiYB4hTgBtYAAF0y43Ebkhh0xtfydPFC7nQhaxgBmMoYnicFNunlP-BTnVBGsPUKUiUutsnXPyYL4Bi5iSeUxznw89v+-r4jqP5-IluZ9F7N7hp0nhXT2Dw6412bvXP+rNTA6EAQvSBbd4gOittgG2bcO50mXjbPuGpLbWweEPWeqBR4T0vk-YOcEP6RyyN-Re8cU50MwXAdwwxbiynyn3FWswX4LEvnSRhMdF4J34RbZ4qCbYQOnh-N+A4s7kN2hzVMXNGrA0OPzCQZhSAixgQOFOmNeQq3FnAAACngYABg8QmRlIqW0bs5rwHyp4W4KNIjDwnJwwx-JIieJEBvbhw9D7wMKBPCOvDmhbgEcQrcE8JwZUhNcOJYBgAOU2BASIuVmTxCSIgVAqgzAwD3C4gwTgd6MRaADVM4IgJljpBXexHtLAdH3n7OAQsdFI2uB3Bp8ADBDQ6XDFO0YUwJmQFoZA6dIjiGUEQdwQc+naOIVMyG5ABkDmzEM6McZspKMYDsVg8AkiU1QGs+IcZ4jtOiWIx09x4gLNOU1DsLZlSMCAA) 


```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "target": "Latest",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

which is not so simple to reproduce locally with `tsc` without skipping library checks. Both Node.js and Bun implement `fetch()` and `tsc` doesn't have the capability to sort out which definition to apply, so errors.

Good luck.

```
/*
  #!/usr/bin/env -S /home/user/deno -A
  #!/usr/bin/env -S /home/user/bun run
  #!/usr/bin/env -S /home/user/node --experimental-transform-types

  TypeScript Native Messaging host
  guest271314, 7-28-2024
*/

/*
declare let readable: NodeJS.ReadStream & {
    fd: 0;
} | ReadableStream<Uint8Array>, writable: WritableStream<Uint8Array>, exit: () => void;
declare function encodeMessage(message: object): Uint8Array;
declare function getMessage(): AsyncGenerator<Uint8Array>;
declare function sendMessage(message: Uint8Array): Promise<void>;
export { encodeMessage, exit, getMessage, readable, sendMessage, writable, };
*/

// Source JavaScript: https://github.com/guest271314/NativeMessagingHosts/blob/main/nm_host.js
//
// Convert JavaScript to TypeScript, no obvious equivalent with tsc
// https://www.codeconvert.ai/javascript-to-typescript-converter
//
// Resizable ArrayBuffer supported by tsc Version 5.7.0-dev.20241019
/**
* /// <reference types="https://raw.githubusercontent.com/microsoft/TypeScript/2ac4cb78d6930302eb0a55d07f154a2b0597ae32/src/lib/es2024.arraybuffer.d.ts" />
*/

import process from "node:process";
const runtime: string = navigator.userAgent;
const buffer: ArrayBuffer = new ArrayBuffer(0, { maxByteLength: 1024 ** 2 });
const view: DataView = new DataView(buffer);
const encoder: TextEncoder = new TextEncoder();

let readable: NodeJS.ReadStream & { fd: 0 } | ReadableStream<Uint8Array>,
  writable: WritableStream<Uint8Array>,
  exit: () => void = () => {};

if (runtime.startsWith("Deno")) {
  // @ts-ignore Deno
  ({ readable } = Deno.stdin);
  // @ts-ignore Deno
  ({ writable } = Deno.stdout);
  // @ts-ignore Deno
  ({ exit } = Deno);
}

if (runtime.startsWith("Node")) {
  readable = process.stdin;
  writable = new WritableStream({
    write(value) {
      process.stdout.write(value);
    },
  }, new CountQueuingStrategy({ highWaterMark: Infinity }));
  ({ exit } = process);
}

if (runtime.startsWith("Bun")) {
  // @ts-ignore Bun
  readable = Bun.file("/dev/stdin").stream();
  writable = new WritableStream<Uint8Array>({
    async write(value) {
      // @ts-ignore Bun
      await Bun.write(Bun.stdout, value);
    },
  }, new CountQueuingStrategy({ highWaterMark: Infinity }));
  ({ exit } = process);
}
```

`deno.json`

```
{
  "nodeModulesDir": "auto",
  "lint": {
    "rules": {
      "tags": ["recommended"],
      "include": [
        "no-irregular-whitespace",
        "constructor-super",
        "eqeqeq",
        "no-async-promise-executor",
        "no-await-in-sync-fn",
        "no-case-declarations",
        "no-global-assign no-node-globals",
        "no-non-null-asserted-optional-chain",
        "no-process-globals",
        "no-unreachable",
        "no-unsafe-negation",
        "no-unused-labels",
        "no-unused-vars",
        "no-undef"
      ],
      "exclude": [
        "no-explicit-any",
        "no-undef"
      ]
    }
  },
  "compilerOptions": {
    "target": "esnext",
    "types": [
      "https://raw.githubusercontent.com/microsoft/TypeScript/2ac4cb78d6930302eb0a55d07f154a2b0597ae32/src/lib/es2024.arraybuffer.d.ts"
    ],
    "lib": [
      "dom",
      "dom.iterable",
      "dom.asynciterable",
      "deno.ns",
      "deno.unstable"
    ]
  }
}
```

**Comment by guest271314** [comment]
This is what I mean by including the definition in the `.ts` file https://github.com/guest271314/NativeMessagingHosts/blob/e972ae4d5de399456a1282f9edde12bb93120c92/nm_host.ts#L1-L64. I think `tsc` also recognizes the `<reference>` tag for local or external type references.

```
// TypeScript Native Messaging host
// guest271314, 7-28-2024
/*
#!/usr/bin/env -S /home/user/bin/deno run
#!/usr/bin/env -S /home/user/bin/bun run 
#!/usr/bin/env -S /home/user/bin/node --experimental-default-type=module --experimental-strip-types
*/
  /**
  * /// <reference types="https://raw.githubusercontent.com/microsoft/TypeScript/eeffd209154b122d4b9d0eaca44526a2784073ae/src/lib/es2024.arraybuffer.d.ts" />
  */
interface ArrayBuffer {
  /**
   * If this ArrayBuffer is resizable, returns the maximum byte length given during construction; returns the byte length if not.
   *
   * [MDN](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/maxByteLength)
   */
  get maxByteLength(): number;

  /**
   * Returns true if this ArrayBuffer can be resized.
   *
   * [MDN](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/resizable)
   */
  get resizable(): boolean;

  /**
   * Resizes the ArrayBuffer to the specified size (in bytes).
   *
   * [MDN](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/resize)
   */
  resize(newByteLength?: number): void;

  /**
   * Returns a boolean indicating whether or not this buffer has been detached (transferred).
   *
   * [MDN](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/detached)
   */
  get detached(): boolean;

  /**
   * Creates a new ArrayBuffer with the same byte content as this buffer, then detaches this buffer.
   *
   * [MDN](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/transfer)
   */
  transfer(newByteLength?: number): ArrayBuffer;

  /**
   * Creates a new non-resizable ArrayBuffer with the same byte content as this buffer, then detaches this buffer.
   *
   * [MDN](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/transferToFixedLength)
   */
  transferToFixedLength(newByteLength?: number): ArrayBuffer;
}

interface ArrayBufferConstructor {
  new (byteLength: number, options?: { maxByteLength?: number }): ArrayBuffer;
}

// Convert JavaScript to TypeScript, no obvious equivalent with tsc
// https://www.codeconvert.ai/javascript-to-typescript-converter
// But wait, there's https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

const runtime: string = navigator.userAgent;
const buffer: ArrayBuffer = new ArrayBuffer(0, { maxByteLength: 1024 ** 2 });
```

**Comment by guest271314** [comment]
An example of Bun types and Node.js types incompatibility. `tsc` says Bun types, and Node.js types have independent errors, too. If you can find a way for `tsc` to not throw - without skipping library checks, I'd be interested in the combination of options you passed to `tsc` to achieve that.

```
bun install typescript@next @types/node undici-types @types/bun
```

`test.ts`

```
import process from "node:process";
const runtime: string = navigator.userAgent;
const buffer: ArrayBuffer = new ArrayBuffer(0, { maxByteLength: 1024 ** 2 });
const view: DataView = new DataView(buffer);
const encoder: TextEncoder = new TextEncoder();

let readable: NodeJS.ReadStream & { fd: 0 } | ReadableStream<Uint8Array>,
  writable: WritableStream<Uint8Array>,
  exit: () => void = () => {};

if (runtime.startsWith("Node")) {
  readable = process.stdin;
  writable = new WritableStream({
    write(value) {
      process.stdout.write(value);
    },
  }, new CountQueuingStrategy({ highWaterMark: Infinity }));
  ({ exit } = process);
}

if (runtime.startsWith("Bun")) {
  readable = Bun.file("/dev/stdin").stream();
  writable = new WritableStream<Uint8Array>({
    async write(value) {
      await Bun.write(Bun.stdout, value);
    },
  }, new CountQueuingStrategy({ highWaterMark: Infinity }));
  ({ exit } = process);
}
```

```
node_modules/.bin/tsc --target esnext -d --types @types/node,@types/bun --module nodenext --moduleResolution nodenext --allowSyntheticDefaultImports test.ts
```

```
node_modules/@types/node/globals.d.ts:509:14 - error TS2300: Duplicate identifier 'fetch'.

509     function fetch(
                 ~~~~~

  node_modules/bun-types/globals.d.ts:1029:6
    1029  var fetch: Fetch;
              ~~~~~
    'fetch' was also declared here.

node_modules/@types/node/module.d.ts:360:13 - error TS2687: All declarations of 'dirname' must have identical modifiers.

360             dirname: string;
                ~~~~~~~

node_modules/@types/node/module.d.ts:366:13 - error TS2687: All declarations of 'filename' must have identical modifiers.

366             filename: string;
                ~~~~~~~~

node_modules/bun-types/bun.d.ts:117:8 - error TS2420: Class 'ShellError' incorrectly implements interface 'ShellOutput'.
  Property 'bytes' is missing in type 'ShellError' but required in type 'ShellOutput'.

117  class ShellError extends Error implements ShellOutput {
           ~~~~~~~~~~

  node_modules/bun-types/bun.d.ts:434:3
    434   bytes(): Uint8Array;
          ~~~~~~~~~~~~~~~~~~~~
    'bytes' is declared here.

node_modules/bun-types/globals.d.ts:1029:6 - error TS2300: Duplicate identifier 'fetch'.

1029  var fetch: Fetch;
          ~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:28708:18
    28708 declare function fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
                           ~~~~~
    'fetch' was also declared here.
  node_modules/@types/node/globals.d.ts:509:14
    509     function fetch(
                     ~~~~~
    and here.

node_modules/bun-types/globals.d.ts:1939:12 - error TS2687: All declarations of 'dirname' must have identical modifiers.

1939   readonly dirname: string;
                ~~~~~~~

node_modules/bun-types/globals.d.ts:1942:12 - error TS2687: All declarations of 'filename' must have identical modifiers.

1942   readonly filename: string;
                ~~~~~~~~

node_modules/bun-types/overrides.d.ts:3:29 - error TS2305: Module '"bun"' has no exported member 'PathLike'.

3 import type { BunFile, Env, PathLike } from "bun";
                              ~~~~~~~~

node_modules/typescript/lib/lib.dom.d.ts:16004:11 - error TS2430: Interface 'MessageEvent<T>' incorrectly extends interface 'Bun.MessageEvent<T>'.
  Types of property 'ports' are incompatible.
    Type 'readonly MessagePort[]' is not assignable to type 'readonly import("worker_threads").MessagePort[]'.
      Type 'MessagePort' is missing the following properties from type 'MessagePort': ref, unref, addListener, emit, and 13 more.

16004 interface MessageEvent<T = any> extends Event {
                ~~~~~~~~~~~~

node_modules/typescript/lib/lib.dom.d.ts:26068:11 - error TS2430: Interface 'WebSocket' incorrectly extends interface 'import("/home/xubuntu/bin/node_modules/@types/ws/index").WebSocket'.
  Types of property 'binaryType' are incompatible.
    Type 'BinaryType' is not assignable to type '"arraybuffer" | "nodebuffer" | "fragments"'.
      Type '"blob"' is not assignable to type '"arraybuffer" | "nodebuffer" | "fragments"'.

26068 interface WebSocket extends EventTarget {
                ~~~~~~~~~

node_modules/typescript/lib/lib.dom.d.ts:28708:18 - error TS2300: Duplicate identifier 'fetch'.

28708 declare function fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
                       ~~~~~

  node_modules/bun-types/globals.d.ts:1029:6
    1029  var fetch: Fetch;
              ~~~~~
    'fetch' was also declared here.


Found 11 errors in 6 files.

Errors  Files
     1  node_modules/@types/node/globals.d.ts:509
     2  node_modules/@types/node/module.d.ts:360
     1  node_modules/bun-types/bun.d.ts:117
     3  node_modules/bun-types/globals.d.ts:1029
     1  node_modules/bun-types/overrides.d.ts:3
     3  node_modules/typescript/lib/lib.dom.d.ts:16004
```

**Comment by MonsterDeveloper** [comment]
Will there be an update for this? The only workaround for now to make Bun work with TS 5.7 is `overrides` in `package.json` for the `@types/node`.

[Official TypeScript 5.7 release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#notable-behavioral-changes) say that `@types/node` needs to be updated in order to work correctly with the new behavior. `bun-types`, however, still uses `@types/node@20`.

There's already an open PR #13987 that bumps `@types/node` to `22`, which seems to be a resolution.

**Comment by alii** [comment]
I've added a test case for this in #18024 and the tests are passing. It should merge soon and addresses a lot of issues relating to @types/bun. Will be closing this issue when it merges, but if you're still seeing this issue in other places, or even the same place, leave a comment and I'll reopen and investigate.

If you want to try it out once the PR merges, you can tell Bun/your package manager to use the canary version of `bun-types` by adding this to `package.json`:

```jsonc
{
  "resolutions": {
    "bun-types": "canary" // Add this line to force @types/bun to resolve to canary
  }
}
```

This works because @types/bun is simply a wrapper of the `bun-types` package

Bun's canary types publish daily, so you might have to wait up to 24 hours after the PR merges
