### PR TITLE
fix(hmr): redirect named_imports after import dedup (#28886)

### PR DESCRIPTION
**Pull request by robobun**
## Summary

Fixes a regression from #26892 (barrel import optimization) where HMR bundles crash at runtime with `X is not a function` when a file has multiple `import { ... } from 'barrel'` statements referencing the same barrel package.

## Repro

```js
// index.ts (HMR mode)
import { Alpha } from 'barrel-lib';
import { Beta } from 'barrel-lib';
console.log(Alpha(), Beta());  // → 'Beta is not a function'
```

Reported in [#28886](https://github.com/oven-sh/bun/issues/28886): `@fluentui/react-combobox`’s submodule imports in `@fluentui/react-tag-picker` break because `useComboboxBaseState` etc. resolve to `undefined` in the HMR wrapper.

## Root cause

`ConvertESMExportsForHmr.deduplicatedImport` (runs during parse) merges the two `import` statements: it marks the second record `is_unused=true` and folds its clause items into the first statement. `named_imports` still contains an entry for each clause item — including entries whose `import_record_index` points at the **dedup'd (unused)** record.

`resolveImportRecords` skips unused records, so that record’s `path.text` never becomes the resolved absolute path. `barrel_imports.scheduleBarrelDeferredImports` then iterates `named_imports`, follows the stale index to the unresolved specifier, fails to find it in `pathToSourceIndexMap`, and silently drops the request.

For a `sideEffects: false` barrel this means:
1. The consumer never seeds `requested_exports[barrel]` with that name.
2. `applyBarrelOptimization` marks the submodule's import record unused.
3. `convertStmtsForChunkForDevServer` emits `var import_X = {}` for it.
4. `hmr.exports.X = import_X.X` is `undefined` at runtime.

## Fix

After dedup in `deduplicatedImport`, redirect `named_imports` entries that currently point at the dedup'd record to the **surviving** record's index. Covers clause items, `default_name`, and `namespace_ref` — so any downstream code that follows `ni.import_record_index` always sees a record with a resolved path.

## Verification

```
bun bd test test/bake/dev/bundle.test.ts -t 'two import statements from the same barrel'
    → PASS
git stash && bun bd test test/bake/dev/bundle.test.ts -t 'two import statements from the same barrel'
    → FAIL (Beta is not a function)
```

New regression test in `test/bake/dev/bundle.test.ts`.

Fixes #28886

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 3:51 AM PT - Apr 5th, 2026</sup></div>

@robobun, your commit 92a809ccc754b481bf9486c329e04fea5b4b57b5 is building: [`#43826`](https://buildkite.com/bun/bun/builds/43826)

File: test/bake/dev/bundle.test.ts [hunk 1]
```diff
@@ -652,3 +652,39 @@ devTest("barrel optimization: two export-from blocks pointing to the same source
...
+    `,
+    "node_modules/barrel-lib/alpha.js": `export const Alpha = () => "ALPHA";`,
+    "node_modules/barrel-lib/beta.js": `export const Beta = () => "BETA";`,
+    "node_modules/barrel-lib/gamma.js": `export const Gamma = () => "GAMMA";`,
+  },
+  async test(dev) {
+    await using c = await dev.client("/");
+    await c.expectMessage("got: ALPHA BETA");
+  },
+});
```
[the remark this answers is not in the document]
Comment (robobun) [reply test/bake/dev/bundle.test.ts:692]: Added reload step in 7ce855f.
