### ISSUE TITLE
Unable to start a Vite/Nuxt/ESBuild dev server with Bun

### ISSUE THREAD

**Issue by NikhilVerma** [oven-sh/bun#18347]
### What version of Bun is running?

1.2.4

### What platform is your computer?

Darwin 24.2.0 arm64 arm

### What steps can reproduce the bug?

Versions

bun: 1.2.4
node: 23.5.0

Dependencies (enforced using overrides)

1. "nuxt": "3.15.4"
2. "esbuild": "0.25.0"
3. "fsevents": "2.3.3"

When running my dev server I get this error (using `bun --bun nuxt dev`). The same error does not occur if I run this via NodeJS

### What is the expected behavior?

The dev server runs

### What do you see instead?

```
Assertion failed: (napi_call_function(env, recv, callback, 3, args, &recv) == napi_ok), function fse_dispatch_event, file fsevents.c, line 151.
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
	github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
	github.com/evanw/esbuild/cmd/esbuild/service.go:114 +0x88
main.runService(0x1)
	github.com/evanw/esbuild/cmd/esbuild/service.go:160 +0x47c
main.main()
	github.com/evanw/esbuild/cmd/esbuild/main.go:241 +0x898

goroutine 35 [chan receive]:
main.runService.func1()
	github.com/evanw/esbuild/cmd/esbuild/service.go:98 +0x40
created by main.runService in goroutine 1
	github.com/evanw/esbuild/cmd/esbuild/service.go:97 +0x19c

goroutine 36 [chan receive]:
main.(*serviceType).sendRequest(0x1400018c2a0, {0x1027ba4a0, 0x140003fd5f0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:192 +0x138
main.runService.func3()
	github.com/evanw/esbuild/cmd/esbuild/service.go:125 +0x44
created by main.runService in goroutine 1
	github.com/evanw/esbuild/cmd/esbuild/service.go:122 +0x2e4
```

**Comment by Necrelox** [comment]
Do you try this on Bun 1.2.5?

**Comment by NikhilVerma** [comment]
@Necrelox I've tried that too just now and it fails with the same error

**Comment by dannote** [comment]
Same with Nuxt 3.16.1 and Bun 1.2.6

**Comment by dannote** [comment]
I monkey-patched `fsevents` with the following code:

```c
void fse_dispatch_event(napi_env env, napi_value callback, void *context, void *data)
{
  if (!env)
  {
    fprintf(stderr, "fse_dispatch_event: env is NULL\n");
    return;
  }
  if (!callback)
  {
    fprintf(stderr, "fse_dispatch_event: callback is NULL\n");
    return;
  }
  napi_valuetype callback_type;
  napi_status status = napi_typeof(env, callback, &callback_type);
  if (status != napi_ok) {
    fprintf(stderr, "napi_typeof failed: %d\n", status);
    return;
  }
  if (callback_type != napi_function) {
    fprintf(stderr, "fse_dispatch_event: callback is not a function, type=%d\n", callback_type);
    return;
  }

  fse_events_t *events = data;
  if (!events || !events->events) {
    fprintf(stderr, "fse_dispatch_event: events or events->events is NULL\n");
    return;
  }
  int argc = 3, idx = 0;
  napi_value args[argc];
  for (idx = 0; idx < events->length; idx++)
  {
    status = napi_create_string_utf8(env, events->events[idx].path, NAPI_AUTO_LENGTH, &args[0]);
    if (status != napi_ok) {
      fprintf(stderr, "napi_create_string_utf8 failed: %d\n", status);
      return;
    }
    status = napi_create_uint32(env, events->events[idx].flags, &args[1]);
    if (status != napi_ok) {
      fprintf(stderr, "napi_create_uint32 failed: %d\n", status);
      return;
    }
    status = napi_create_int64(env, events->events[idx].id, &args[2]);
    if (status != napi_ok) {
      fprintf(stderr, "napi_create_int64 failed: %d\n", status);
      return;
    }
    napi_value recv;
    status = napi_get_null(env, &recv);
    if (status != napi_ok) {
      fprintf(stderr, "napi_get_null failed: %d\n", status);
      return;
    }
    status = napi_call_function(env, recv, callback, 3, args, &recv);
    if (status != napi_ok) {
      fprintf(stderr, "napi_call_function failed: %d (idx=%d)\n", status, idx);
      return;
    }
  }
  free(events->events);
  free(events);
}
```

Here is what I get in my logs now:

```
✔ Nuxt Nitro server built in 592ms                                                                                                                nitro 11:43:35 PM
ℹ Vite client warmed up in 2ms                                                                                                                          11:43:35 PM
fse_dispatch_event: callback is not a function, type=6
fse_dispatch_event: callback is not a function, type=6
ℹ Vite server warmed up in 2159ms                                                                                                                       11:43:37 PM
fse_dispatch_event: callback is not a function, type=6
fse_dispatch_event: callback is not a function, type=6
fse_dispatch_event: callback is not a function, type=6
^C%
```

**Comment by dannote** [comment]
For anyone wondering about potential workarounds to get Nuxt dev server working with Bun, here is my current setup:

```ts
// nuxt.config.ts

export default defineNuxtConfig({
  devtools: {
    enabled: !process.versions.bun
  },
  vite: {
    server: {
      watch: {
        usePolling: !!process.versions.bun
      }
    }
  },
  watchers: {
    chokidar: {
      usePolling: !!process.versions.bun
    },
  },
  nitro: {
    preset: 'bun',
    watchOptions: {
      usePolling: !!process.versions.bun
    },
  },
})
```

Start the dev server with the following flags:

```bash
bun --bun run dev --no-fork
```

**Comment by osdiab** [comment]
If anyone has suggestions on how to get Tanstack Start to not crash with this error, that would be much appreciated - this does not seem to do the trick unfortunately:

```
const app: App = await defineConfig({
	vite: {
		plugins: [tsconfigPaths()],
		build: {
			watch: { chokidar: { usePolling: !!process.versions.bun } },
		},
	},
	server: {
		watchOptions: { usePolling: !!process.versions.bun },
	},
});
```

**Comment by dannote** [comment]
I can confirm that `fsevents` works in Bun 1.2.9
