### PR TITLE
node:tls: shut the wrapped stream down when a client-side TLSSocket wrap ends or is destroyed

### PR DESCRIPTION
**Pull request by robobun**
### Problem
- `new tls.TLSSocket(stream)` without `isServer`, then `end()` or `destroySoon()`, kills the process: `TypeError: socket.shutdown is not a function. (In 'socket.shutdown()', 'socket.shutdown' is undefined)` at `endNT (node:net)`, thrown from a nextTick. Bun 1.4.2 did nothing. Unreleased regression from #42181, found by a fuzz run.
- This wrap keeps the wrapped stream as `_handle` until `connect()` upgrades it (`src/js/node/tls.ts:834`). `TLSSocket.prototype._final` used to park on the handshake, which never starts here. Since #42181 it reaches `endNT` (`src/js/node/net.ts:385`), which calls `_handle.shutdown()`. A JS stream has none.

### Fix
- `_final` ends the wrapped stream with `stream.end(cb)`, as node's `JSStreamSocket.doShutdown` does. A wrapped `net.Socket` that is not connected yet waits for its `'connect'` first, as in node.
- `closeSocketHandle` destroys a handle that is a stream, as `JSStreamSocket.doClose` does. The `destroy()` that `destroySoon()` issues on `'finish'` threw `handle.close is not a function` here. Supersedes #35842, with `instanceof Duplex` for `typeof close`: an http2 stream has its own `close(code, callback)`.
- The wrap closes when its stream closes, as node's `_wrapHandle` does. That ends an `end()` that waits on a refused connection, and closes the wrap once the peer answers the FIN.
- Verified: `test/js/node/tls/node-tls-connect.test.ts`, 7 new tests (21 cells) that run the same fixture on node v26.3.0 with the same expected report. All 7 fail on main with the TypeError. Also vendored `test-tls-*`, `test-https-*`, `test-http2-*`, `test-net-*`, `test/js/node/tls/`, `test/js/node/net/`.

### Background
- `_final` is the shutdown hook of the writable side. `'finish'` follows its callback. `destroySoon()` is `end()` plus `destroy()` on `'finish'`.
- `_handle` is normally a native socket with `shutdown()` and `close()`. Only the client-side wrap holds a JS stream there (#37664 changes that).
- Node puts such a stream in a `JSStreamSocket`. Its `doShutdown` calls `stream.end()`, its `doClose` calls `stream.destroy()`.

<details><summary>Notes</summary>

Reproduction (no certificates needed), from the report:

```js
const net = require("net"), tls = require("tls");
const how = process.argv[2] || "end";
const srv = net.createServer(c => { c.on("data", () => {}); c.on("end", () => console.log("peer: got FIN")); c.on("error", () => {}); });
srv.listen(0, "127.0.0.1", () => {
  const raw = net.connect(srv.address().port, "127.0.0.1", () => {
    const s = new tls.TLSSocket(raw, { rejectUnauthorized: false });
    s.on("error", e => console.log("tls 'error':", e.code || e.message));
    s.on("finish", () => console.log("tls 'finish'"));
    s.on("close", () => console.log("tls 'close'"));
    setTimeout(() => { console.log("calling", how + "()"); how === "end" ? s.end() : s.destroySoon(); }, 50);
    setTimeout(() => { console.log("exit: destroyed=" + s.destroyed, "writableFinished=" + s.writableFinished); process.exit(0); }, 500);
  });
});
```

| call | node v26.3.0 | bun 1.4.2 | main (97c191b7c0) | this branch |
| --- | --- | --- | --- | --- |
| `end()` | `finish`, FIN, `close`, `destroyed=true` | nothing | uncaught TypeError, exit 1 | same as node |
| `destroySoon()` | `finish`, FIN, `close`, `destroyed=true` | nothing | uncaught TypeError, exit 1 | same as node |

Measured again after the rebase onto main f385d9a639: main still throws in both modes, the 7 new tests fail there with the TypeError, and they pass on this branch.

Twelve cells throw on main: a connected, a connecting, and a never-connected `net.Socket`, and a user `Duplex`, each with `end()`, `end(cb)`, and `destroySoon()`. With this branch all twelve match node in the `'finish'`, `'error'` and `'close'` events of the TLS socket.

What the first five new tests pin, per transport (connected, still connecting, connected later, `Duplex`, `Duplex` with a `close(code, callback)` of its own), identical on node v26.3.0 and this branch. The peer keeps its side open (`allowHalfOpen`), so the stream stays open under the wrap:
- `end()`: `'finish'`, the peer sees the FIN, the wrap is `readOnly`, nothing is destroyed. A socket that is not connected yet gets its `'connect'` first.
- `destroySoon()`: `'finish'`, `'close'`, the peer sees the FIN, the wrap and the stream are destroyed.
- `destroy()`: `'close'`, the wrap and the stream are destroyed. Over a socket that is already connected the peer sees the FIN of the closed transport. The stream's own `close()` is never called. With the `typeof close` form of the check that cell fails: `close()` receives the completion callback and the stream survives.

`peerSawFin` in these reports is what the peer's `'end'` handler recorded, and the key is present only where a FIN is owed.

The last two tests close the stream under the wrap, again identical on node v26.3.0 and this branch:
- A peer that closes when the FIN arrives: `end()` gives `'finish'`, `'close'`, and the wrap and the stream are destroyed.
- A refused connection: `end()` and `destroySoon()` wait for `'connect'`, the stream reports `ECONNREFUSED` and closes, and the wrap closes with it (`'close'`, no `'finish'`).

The wrap follows the `'close'` of its stream one tick later, and only while that stream is still its handle. One tick later, because the stream machinery emits `'finish'` one tick after the `_final` callback: a stream that fails in its own `final` calls back and closes in the same turn, and node reports `'finish'` and then `'close'` for it (measured, and the same here). Only while it is the handle, because after `connect({ socket })` the native handle reports the close.

This PR guards 2 of the 6 places where `node:net` calls the wrapped stream as if it were a native handle. The other four are older than #42181, throw from the call itself (so the caller can catch them), and are unchanged here:
- `_write` calls `_handle.$write()`: `write()`, `end(data)`, `end('')` and `uncork()` throw `socket.@write is not a function`.
- `ref()` and `unref()` call `_handle.ref()` / `_handle.unref()`: they throw over a generic `Duplex` (a wrapped `net.Socket` has both).
- `resetAndDestroy()` calls `_handle.terminate()`.

The wrap exists in this form so that `_handle._parentWrap` works for http2-wrapper. #37664 removes all four sites, because the wrap then has a native handle. When the `_handle = socket` assignment in the constructor goes away, the two branches added here are dead code and can go with it.

Found on the way, handed off separately:
- `end()` before the TLS handle is attached emits `'finish'` and sends no FIN: `tls.connect({ socket: stillConnecting }).end()`, and `new TLSSocket(sock, { isServer: true }).end()` in the same tick. Both are older than #42181.
- `endNT` calls `shutdown()` with no guard, so any throw there is an uncaught exception.

Differences from node that remain:
- Node also forwards the `'error'` of the stream: the constructor adds `wrap.on('error', err => this._emitTLSError(err))`, so the TLS socket emits `'_tlsError'` (and `'error'` once control is released), and the stream's error never counts as unhandled. Bun's client-side wrap does not listen for it until `connect()` upgrades it, so a wrapped socket that fails with no `'error'` listener of its own is still an uncaught exception. That is older than this PR. #37664 closes it.
- The wrap does not read its transport, so after the peer's FIN it emits `'close'` but no `'end'`.
- Node shuts the TCP handle down below the wrapped `net.Socket`, so that socket has `writableEnded === false` and emits no `'finish'`. Here the wrapped socket ends through its own `end()`, so it reports both. For a wrapped `Duplex` node calls `end()` too, and the reports are identical.

The order of the checks in `_final`: a write that happened before the handshake still parks on the handshake signal first, as #42181 left it. The stream branch applies only while `_handle instanceof Duplex`, which only the client-side constructor branch produces. After `connect({ socket })` the handle is native and the old path runs.

On the fixture: an uncaught exception does not end a bun process while the top-level await of the entry module is pending (#22546). The process prints the error and keeps running. The fixture installs an `uncaughtException` handler that prints and exits 1, so the new tests fail in about 2 s with the TypeError in the assertion, and do not time out.

Review findings: two reviewers asked `_final` to settle when a wrapped socket fails before `'connect'`, and one asked it to forward the error of `stream.end()`. Node does neither (measured on v26.3.0: the `end()` callback of a wrap over a stream whose `final` fails gets no error, and a refused connection leaves `_final` unsettled). What node does have is the close path above, which is now in.

Suites run with a debug build of this branch, compared with a debug build of main:
- `test/js/node/tls/node-tls-connect.test.ts`: 85 pass, 18 skip, 0 fail (after the rebase onto f385d9a639).
- `tsc --noEmit -p src/js/tsconfig.json` (the typecheck of the built-in modules that CI runs since #43649): no error.
- `test/js/node/test/parallel/test-tls-*.js` (186 files): 185 pass. `test-tls-client-allow-partial-trust-chain.js` needs the `node:test` runner.
- `test-https-*`, `test-http2-*`, `test-net-*` (473 files): 461 pass. The 12 that fail (`test-https-proxy-request*.mjs`, `test-https-request-proxy-post.mjs`, `test-https-timeout.js`, two `node:test` files) fail the same way on main in this environment.
- `test/js/node/tls/*.test.ts`, `test/js/node/net/*.test.ts`: no new failure. `node-tls-server.test.ts` (2) and `node-net.test.ts` (11) have failures that need DNS or more than 5 s on a debug build, identical on main.

Self-reviewed: 3 changes requested, 3 made. `closeSocketHandle` tests `instanceof Duplex`. A cell covers a stream with its own `close()`. The `destroy()` cells from #35842 are in.

</details>

---

**[human-review]** gate passed · iteration 1 · 4 files touched

<details><summary>fails on main (without fix)</summary>

```console
ASAN without fix: 7 failed, 18 skipped
$ BUN_DEBUG_QUIET_LOGS=1 bun scripts/build.ts --profile=debug --quiet test "--reporter=junit" "--reporter-outfile=/tmp/pr_gate.xml" test/js/node/tls/node-tls-connect.test.ts
bun test v1.4.3 (367d939d9)

test/js/node/tls/node-tls-connect.test.ts:
(pass) should have checkServerIdentity [2.66ms]
(pass) should thow ECONNRESET if FIN is received before handshake [298.99ms]
(pass) initializes authorizationError to null in the TLSSocket constructor [6.50ms]
(pass) setMaxSendFragment mirrors OpenSSL's [512, 16384] acceptance without throwing [126.61ms]
(pass) should be able to grab the JSStreamSocket constructor [15.87ms]
(skip) tls.connect > should work with alpnProtocols
(pass) tls.connect > Bun.serve() should work with tls and Bun.file() [74.10ms]
(pass) tls.connect > should have peer certificate when using self asign certificate [73.52ms]
(skip) tls.connect > should have peer certificate
(skip) tls.connect > getCipher, getProtocol, getEphemeralKeyInfo, getSharedSigalgs, getSession, exportKeyingMaterial and isSessionReused should work
(skip) tls.connect > should process options correctly when connect is called with only options
(skip) tls.connect > should process port an
... (truncated)

release without fix: 18 skipped
bun test v1.4.3-canary.1 (847fb6544)

test/js/node/tls/node-tls-connect.test.ts:
(pass) should have checkServerIdentity [0.09ms]
(pass) should thow ECONNRESET if FIN is received before handshake [7.13ms]
(pass) initializes authorizationError to null in the TLSSocket constructor [0.14ms]
(pass) setMaxSendFragment mirrors OpenSSL's [512, 16384] acceptance without throwing [4.36ms]
(pass) should be able to grab the JSStreamSocket constructor [0.36ms]
(skip) tls.connect > should work with alpnProtocols
(pass) tls.connect > Bun.serve() should work with tls and Bun.file() [5.95ms]
(pass) tls.connect > should have peer certificate when using self asign certificate [4.29ms]
(skip) tls.connect > should have peer certificate
(skip) tls.connect > getCipher, getProtocol, getEphemeralKeyInfo, getSharedSigalgs, getSession, exportKeyingMaterial and isSessionReused should work
(skip) tls.connect > should process options correctly when connect is called with only options
(skip) tls.connect > should process port and host correctly
(skip) tls.connect > should process port, host, and callback correctly
(skip) tls.connect > should handle the absence of a callback gracefully
(skip) tls.c
... (truncated)
```

</details>

<details><summary>passes on PR (with fix)</summary>

```console
ASAN with fix: 18 skipped
$ BUN_DEBUG_QUIET_LOGS=1 bun scripts/build.ts --profile=debug --quiet test "--reporter=junit" "--reporter-outfile=/tmp/pr_gate.xml" test/js/node/tls/node-tls-connect.test.ts
bun test v1.4.3 (367d939d9)

test/js/node/tls/node-tls-connect.test.ts:
(pass) should have checkServerIdentity [3.01ms]
(pass) should thow ECONNRESET if FIN is received before handshake [297.76ms]
(pass) initializes authorizationError to null in the TLSSocket constructor [6.38ms]
(pass) setMaxSendFragment mirrors OpenSSL's [512, 16384] acceptance without throwing [92.93ms]
(pass) should be able to grab the JSStreamSocket constructor [17.23ms]
(skip) tls.connect > should work with alpnProtocols
(pass) tls.connect > Bun.serve() should work with tls and Bun.file() [72.63ms]
(pass) tls.connect > should have peer certificate when using self asign certificate [72.80ms]
(skip) tls.connect > should have peer certificate
(skip) tls.connect > getCipher, getProtocol, getEphemeralKeyInfo, getSharedSigalgs, getSession, exportKeyingMaterial and isSessionReused should work
(skip) tls.connect > should process options correctly when connect is called with only options
(skip) tls.connect > should process port and
... (truncated)

release with fix: 18 skipped
$ bun scripts/build.ts --profile=release
[configured] bun-profile → bun (stripped) in 976ms (unchanged)
ninja: Entering directory `/workspace/bun/build/release'
[1/212] gen generated_host_exports.rs
generated_host_exports.rs: 121 exports (host=5, lazy=10, generic=106, rust=0); 245 extern-C blocks audited
[2/212] gen ZigGeneratedClasses.{cpp,h,rs}
Found 2 classes from /workspace/bun/src/jsc/resolve_message.classes.ts
  - ResolveMessage (15 fields)
  - BuildMessage (10 fields)
Found 1 classes from /workspace/bun/src/runtime/api/Archive.classes.ts
  - Archive (4 fields, 1 class fields)
Found 2 classes from /workspace/bun/src/runtime/api/BunObject.classes.ts
  - ResourceUsage (8 fields)
  - Subprocess (20 fields)
Found 1 classes from /workspace/bun/src/runtime/api/cron.classes.ts
  - CronJob (5 fields)
Found 3 classes from /workspace/bun/src/runtime/api/filesystem_router.classes.ts
  - FileSystemRouter (5 fields)
  - FrameworkFileSystemRouter (2 fields)
  - MatchedRoute (8 fields)
Found 1 classes from /workspace/bun/src/runtime/api/Glob.classes.ts
  - Glob (5 fields)
Found 1 classes from /workspace/bun/src/runtime/api/h2.classes.ts
  - H2FrameParser (29 fields)
Found 
... (truncated)
```

</details>

<details><summary>diff hotspot</summary>

```
src/js/node/net.ts                                 |  7 +-
 src/js/node/tls.ts                                 | 19 ++++-
 test/js/node/tls/node-tls-connect.test.ts          | 77 +++++++++++++++++-
 .../tls/tls-shutdown-before-handshake-fixture.mjs  | 91 +++++++++++++++++++++-
 4 files changed, 185 insertions(+), 9 deletions(-)
```

</details>

**gate history** · 3 passed · 0 rejected · iteration 1

<details><summary>evidence per changed file</summary>

```
file                                                      reads  edits  tests
src/js/node/net.ts                                            6      2     40
src/js/node/tls.ts                                            4      3     38
test/js/node/tls/node-tls-connect.test.ts                     5      7     34
…t/js/node/tls/tls-shutdown-before-handshake-fixture.mjs      6     12     36
```

</details>

### CODE REVIEW

**Comment by robobun** [comment]
**Status:** fix pushed, waiting for CI.

Reproduced with the script from the report (in the PR notes) on a debug build of main (97c191b7c0):

```sh
bun bd t1.cjs end          # TypeError: socket.shutdown is not a function, exit 1
bun bd t1.cjs destroySoon  # same
```

The same throw occurs for a connected, a connecting and a never-connected `net.Socket` and for a user `Duplex`, each with `end()`, `end(cb)` and `destroySoon()` (12 of 12 cells). Node v26.3.0 throws in none. With this branch none of the 12 throws, and `bun bd test test/js/node/tls/node-tls-connect.test.ts` passes (65 pass, 0 fail). With `src/` at main the 5 new tests fail with the TypeError.

File: src/js/node/tls.ts [hunk 1]
```diff
@@ -897,11 +897,21 @@ TLSSocket.prototype._start = function _start() {
...
     return this.once(kSecureConnectDone, NetSocket.prototype._final.bind(this, callback));
   }
+  // A client-side wrap holds the stream it wraps as its handle until connect() upgrades it.
+  if (handle instanceof Duplex) {
+    // https://github.com/nodejs/node/blob/v26.3.0/lib/internal/tls/wrap.js#L964-L973
+    if (handle instanceof NetSocket && handle.pending) {
+      return handle.once("connect", this._final.bind(this, callback));
+    }
+    // https://github.com/nodejs/node/blob/v26.3.0/lib/internal/js_stream_socket.js#L155-L160
+    return handle.end(() => callback());
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/js/node/tls.ts:920]: Not changed: node does not forward this error either.

`JSStreamSocket.doShutdown` completes the shutdown with status 0 whatever `stream.end()` reports: `this.stream.end(() => { this.finishShutdown(handle, 0); })` ([js_stream_socket.js#L155-L160](https://github.com/nodejs/node/blob/v26.3.0/lib/internal/js_stream_socket.js#L155-L160)). Measured on node v26.3.0 with a wrapped `Duplex` whose `final` fails with `EBOOM`, then `tlsSocket.end(cb)`: `cb` receives no error, `'finish'` fires, `writableFinished === true`, `errored === null`. This branch gives the same four values. With `handle.end(callback)` the wrap would be destroyed with `EBOOM`, `cb` would receive the error, and `'finish'` would not fire.

Node reports the failure of the stream on another path. The constructor adds `wrap.on('error', err => this._emitTLSError(err))` and `wrap.on('close', () => this.destroy())`, so the TLS socket also emits `'_tlsError'` and then `'close'`. Bun's client-side wrap does not listen to its transport until `connect()` upgrades it. That gap is older than this PR. I added it to the notes under the differences that remain. #37664 removes it, because it upgrades the wrap in the constructor.

File: src/js/node/tls.ts [hunk 2]
```diff
@@ -897,11 +897,21 @@ TLSSocket.prototype._start = function _start() {
...
-  if (!this._handle) return callback();
+  const handle = this._handle;
+  if (!handle) return callback();
   // https://github.com/nodejs/node/blob/v26.3.0/src/crypto/crypto_tls.cc#L1119-L1133
   if (this.secureConnecting && this[kPreHandshakeWrite]) {
     return this.once(kSecureConnectDone, NetSocket.prototype._final.bind(this, callback));
   }
+  // A client-side wrap holds the stream it wraps as its handle until connect() upgrades it.
+  if (handle instanceof Duplex) {
+    // https://github.com/nodejs/node/blob/v26.3.0/lib/internal/tls/wrap.js#L964-L973
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/js/node/tls.ts:915]: Not changed: node waits for `'connect'` only, too.

`net.Socket.prototype._final` does `this.once('connect', () => this._final(cb))` ([net.js#L536-L541](https://github.com/nodejs/node/blob/v26.3.0/lib/net.js#L536-L541)), and `TLSSocket.connecting` for a wrapped socket clears only on its `'connect'` ([wrap.js#L964-L973](https://github.com/nodejs/node/blob/v26.3.0/lib/internal/tls/wrap.js#L964-L973)). Measured on node v26.3.0 with `new tls.TLSSocket(net.connect(deadPort))` and `end(cb)`: `_final` is never settled, there is no `'finish'`, and `cb` receives `ERR_STREAM_DESTROYED`.

What ends the wait in node is the `'close'` of the transport. `_wrapHandle` adds `wrap.on('close', () => this.destroy())`, and the destroy abandons the pending `_final`. So the missing piece in bun is the same as in the other thread: the client-side wrap does not follow the `'error'` and `'close'` of its transport until `connect()` upgrades it. To settle `_final` here would emit `'finish'` for a FIN that was never sent, and node does not do that. The notes now list this case under the differences that remain.

File: src/js/node/tls.ts [hunk 3]
```diff
@@ -897,11 +897,21 @@ TLSSocket.prototype._start = function _start() {
...
+    if (handle instanceof NetSocket && handle.pending) {
+      return handle.once("connect", this._final.bind(this, callback));
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/js/node/tls.ts:917]: The hang is real, and 12f39c1 fixes it, but not with a second settle path in `_final`.

Node also waits for `'connect'` only (`net.Socket.prototype._final`, [net.js#L536-L541](https://github.com/nodejs/node/blob/v26.3.0/lib/net.js#L536-L541)). Measured on node v26.3.0 with `new tls.TLSSocket(net.connect(deadPort))` and `end(cb)`: `_final` is never settled, there is no `'finish'`, and `cb` receives `ERR_STREAM_DESTROYED`. To call `callback()` on the stream's `'close'` would emit `'finish'` for a FIN that was never sent.

What ends the wait in node is that the wrap closes with its stream: `_wrapHandle` adds `wrap.on('close', () => this.destroy())` ([wrap.js#L739-L741](https://github.com/nodejs/node/blob/v26.3.0/lib/internal/tls/wrap.js#L739-L741)). The client-side constructor branch now does the same. The destroy abandons the pending `_final`, so `destroySoon()` on a refused connection ends with `'close'` and `destroyed === true`, as in node. It runs one tick after the stream's `'close'`, so a `'finish'` that is already queued is emitted first, and only while the wrap still holds that stream as its handle (after a `connect({ socket })` upgrade the native handle reports the close).

Two new fixture cells pin this to node v26.3.0: a refused connection under `end()` / `destroySoon()` / `destroy()`, and a peer that closes when the FIN arrives (there `end()` now gives `'finish'`, `'close'`, `destroyed === true`, which was the one remaining difference in the report's own script).

**Comment by robobun** [comment]
On the "outside diff" comment in the latest CodeRabbit review (forward the error of `handle.end()` to the `_final` callback): this is the finding from the thread at https://github.com/oven-sh/bun/pull/42330#discussion_r3990324675, which ended as invalid. Not changed, for the same reason.

Node completes this shutdown with status 0 whatever `stream.end()` reports: `this.stream.end(() => { this.finishShutdown(handle, 0); })` ([js_stream_socket.js#L155-L160](https://github.com/nodejs/node/blob/v26.3.0/lib/internal/js_stream_socket.js#L155-L160)). Measured on node v26.3.0 with a wrapped `Duplex` whose `final` fails: the `end()` callback of the TLS socket gets no error, `'finish'` fires, then `'close'`. Since 12f39c1 this branch prints the same three lines, because the wrap now closes with its stream. `handle.end(error => callback(error))` would replace `'finish'` with an error on the TLS socket, which node does not report there.

**Comment by robobun** [comment]
<div><sup>Updated 8:39 AM PT - Sep 11th, 2026</sup></div>

:hourglass_flowing_sand: @robobun, your commit 12f39c178af5c028c84358d37c599a17b6cad183 is still building in [`Build #114322`](https://buildkite.com/bun/bun/builds/114322), but has 1 failures so far ([All Failures](http://bun-linux2:6786/?commit=12f39c178af5c028c84358d37c599a17b6cad183)):

<ul><li><a href="https://github.com/oven-sh/bun/blob/12f39c178af5c028c84358d37c599a17b6cad183/test/js/bun/http/serve-pending-promise-abort-leak.test.ts"><code>test/js/bun/http/serve-pending-promise-abort-leak.test.ts</code></a> - code 1 on <a href="https://buildkite.com/bun/bun/builds/114322#01a09114-b134-4a6a-abf6-66819741023f">🐧 13 x64-asan</a></li></ul>

**Comment by alii** [comment]
@robobun Buildkite failed on this head (12f39c178, https://buildkite.com/bun/bun/builds/114322, Sep 11) and it has not run since. Please rebase onto main so CI runs again. #42350 edits the same fixture (tls-shutdown-before-handshake-fixture.mjs) and node-tls-connect.test.ts, so expect a conflict with it. Whichever lands second needs a rebase.

**Comment by robobun** [comment]
@alii Rebased onto main (f385d9a639), new head 847fb65. The rebase had no conflict. CI runs again on this head.

Checked on the rebased tree, with a debug build:
- `test/js/node/tls/node-tls-connect.test.ts`: 85 pass, 0 fail. With `src/` at current main the 7 new tests still fail with `TypeError: socket.shutdown is not a function`, so main still has the bug.
- `tsc --noEmit -p src/js/tsconfig.json` (new in CI since #43649): no error.
- Vendored `test-tls-*.js`: 185 of 186 pass. `test-tls-client-allow-partial-trust-chain.js` needs the `node:test` runner and fails the same way on main.

On the old red build (114322): the only red test was `test/js/bun/http/serve-pending-promise-abort-leak.test.ts` on x64-asan, which also failed on the PRs merged at that time. This diff does not touch it.

On #42350: it is still open, so there is no conflict with main today. I did a trial merge of its branch into this one. In `src/` the two do not overlap (#42350 changes only `src/runtime/socket/UpgradedDuplex.rs`, this PR only `src/js/node/tls.ts` and `net.ts`). The conflicts are in `tls-shutdown-before-handshake-fixture.mjs` and `node-tls-connect.test.ts`, where both PRs add fixture modes and tests next to each other. Both sides can be kept as they are. I will rebase this PR if #42350 lands first.

File: test/js/node/tls/tls-shutdown-before-handshake-fixture.mjs [hunk 4]
```diff
@@ -93,6 +100,74 @@ if (mode === "end" || mode === "destroySoon") {
...
+    socket[method]();
+    // Only the graceful shapes owe the peer a FIN, and destroy() leaves nothing to connect.
+    const peerSawFin = peer !== undefined && method !== "destroy";
+    if (transport === "unconnected" && peerSawFin) raw.connect(peer.port, "127.0.0.1");
+
+    const settled = method === "end" && !peerCloses && !refused ? "finish" : "close";
+    await Promise.all([once(socket, settled), peerSawFin && peer.sawFin]);
+
+    const { writableFinished, readyState, destroyed } = socket;
+    const result = { log: [...log], peerSawFin, writableFinished, readyState, destroyed, transportDestroyed: raw.destroyed };
```
[the remark this answers is not in the document]
Comment (robobun) [reply test/js/node/tls/tls-shutdown-before-handshake-fixture.mjs]: Correct, fixed in e5de3ab.

`peerSawFin` in the `wrap` mode now comes from the peer: its `'end'` handler sets a flag, and the report reads that flag after the await. The report has the key only where a FIN is owed: `end()` and `destroySoon()` over a socket, and `destroy()` over a socket that is already connected. The `destroy()` cells over a connected socket now expect `peerSawFin: true`, which is what both runtimes do (the transport closes and the peer gets the FIN). There are no `false` cells left. `destroy()` before the connection exists, a refused connection and a `Duplex` have no peer to observe, so the key is absent there.

All 21 cells are still byte-identical on node v26.3.0 and this branch (three rounds), and the file passes: 85 pass, 0 fail.

The older `end` / `destroySoon` modes of this fixture (from #42181) report a constant `peerSawFin: true` after the same kind of await. I left them as they are, because they are not part of this change.

**Comment by alii** [comment]
Closing this in favor of #37664. That PR removes the cause, the client wrap keeping the wrapped stream as its handle, instead of guarding two of the sites that call into it. It needs a rebase onto main first. The 21-cell matrix from this PR should be its acceptance test. Reopen this if #37664 cannot land in time.

**Comment by robobun** [comment]
Understood. #37664 removes the cause, and this PR only guarded two of the call sites.

The matrix is handed over: https://github.com/oven-sh/bun/pull/37664#issuecomment-5808729486 has the commands to move the fixture and the tests (their diff applies cleanly on current main), the 21 cells, what node does in each group of cells, and the 12-cell throw script from the report.

For the release timing: main still throws `TypeError: socket.shutdown is not a function` on `new tls.TLSSocket(stream).end()` until #37664 lands. It is a regression from #42181 that is in no release yet. This branch stays as it is (e5de3ab, based on f385d9a639, [build 120141](https://buildkite.com/bun/bun/builds/120141) passed 181 of 181 jobs), so it can be reopened and rebased if #37664 cannot land in time.
