### ISSUE TITLE
`@types/*` packages in `.bun/node_modules/` resolved based on alphabetical workspace package name ordering

### ISSUE THREAD

**Issue by bohdanbirdie** [oven-sh/bun#26140]
### What version of Bun is running?

1.3.5+1e86cebd7

### What platform is your computer?

Darwin 24.6.0 arm64 arm

### What steps can reproduce the bug?

In a monorepo with workspaces using different versions of `@types/react` (React 18 vs React 19), Bun incorrectly hoists `@types/react` to `.bun/node_modules/@types/react` based on **alphabetical package name ordering**, not based on which package actually needs which version.

### Minimal reproduction

1. Create a monorepo with two workspaces:

**package.json** (root):
```json
{
  "name": "repro",
  "workspaces": ["packages/*"]
}
```

**packages/aaa-react19/package.json**:
```json
{
  "name": "@repro/aaa-react19",
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0"
  }
}
```

**packages/bbb-react18/package.json**:
```json
{
  "name": "@repro/bbb-react18",
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "swr": "^2.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.7"
  }
}
```

2. Run `bun install`

3. Check the global symlink:
```bash
ls -la node_modules/.bun/node_modules/@types/react
```

4. The symlink points to `@types/react@19.x` because `aaa` < `bbb` alphabetically

5. Now rename `aaa-react19` to `zzz-react19`:
```json
{
  "name": "@repro/zzz-react19",
  ...
}
```

6. Run `rm -rf node_modules bun.lock && bun install`

7. Check the symlink again - it now points to `@types/react@18.x` because `zzz` > `bbb`

### Evidence from systematic testing

We tested this by changing ONLY the package name of a React 19 project in a monorepo that also has a React 18 project called `@repro/bbb-react18`:

| Package Name | Global @types/react | Reason |
|-------------|---------------------|--------|
| `@repro/aaa-react19` | 19.x | aaa < bbb |
| `@repro/bbb-react19` | 19.x | bbb = bbb (same, React 19 wins) |
| `@repro/ccc-react19` | 18.x | ccc > bbb |
| `@repro/zzz-react19` | 18.x | zzz > bbb |

The cutoff is exactly at the alphabetically first React 18 package that declares `@types/react`.

### What is the expected behavior?

Each workspace should resolve `@types/react` to its own declared version. The global symlink in `.bun/node_modules/@types/react` should not affect type resolution for workspaces that declare a different version.

Alternatively, if a global symlink must exist, it should not be determined by alphabetical package name ordering - this is arbitrary and leads to confusing, hard-to-debug issues.

### What do you see instead?

TypeScript compilation fails in React 18 projects with errors like:

```
error TS2322: Type 'bigint' is not assignable to type 'ReactNode'.
```

This happens because React 19's `ReactNode` type includes `bigint`, while React 18's does not. When TypeScript resolves types from dependencies stored in the `.bun/` cache, it finds the global symlink pointing to the wrong version.

The affected projects have the correct `@types/react` version in their own `node_modules/`, but TypeScript still picks up the wrong types from transitive dependencies that reference the `.bun/node_modules/` location.

### Workarounds we found

1. **Remove `@types/react` from React 19 projects** - React 19 includes built-in TypeScript types, so `@types/react` is optional. This prevents the React 19 types from "winning" the global symlink.

2. **Rename the package** - Rename the React 19 package to something alphabetically after all React 18 packages.

### Why this is particularly problematic

- The bug is extremely hard to diagnose - changing a package NAME shouldn't affect type resolution
- It affects any monorepo with mixed dependency versions (not just React)
- The workarounds are all suboptimal hacks
- Projects that work in isolation fail when added to a monorepo, depending on their name

### Possibly Related issues

- #6850 - Support for nohoist / multiple versions of the same package
- #23615 - Two Critical Bugs Making Bun 1.3 Isolated Installs + Catalog Unusable for Monorepos

### Example repo
https://github.com/bohdanbirdie/bun-ordering
