### PR TITLE
fix(node/fs): `fs.close` and `fs.Dir.closeSync`

### LINKED ISSUE #16622: Missing closedirSync in fs
### What version of Bun is running?

1.2.0

### What platform is your computer?

Linux 6.12.10-amd64 x86_64 unknown

### What steps can reproduce the bug?

This function no longer works in bun 1.2:
```ts
export async function isDirectoryEmpty(directory) {
	const dirHandle = await fsp.opendir(directory)
	const iter = dirHandle[Symbol.asyncIterator]()
	let next = await iter.next()
	while (!next.done) {
		await dirHandle.close()
		return false
	}
	return true
}
```
Failing with error message:
```ts
TypeError: fs.closedirSync is not a function. (In 'fs.closedirSync(this.#handle)', 'fs.closedirSync' is undefined)
      at close (node:fs:423:27)
```

### What is the expected behavior?

The function should not fail

### What do you see instead?

```ts
TypeError: fs.closedirSync is not a function. (In 'fs.closedirSync(this.#handle)', 'fs.closedirSync' is undefined)
      at close (node:fs:423:27)
```

### Additional information

The method `dirHandle.close()` is invoking internally `closedirSync()` but it cannot find it

### PR DESCRIPTION
**Pull request by DonIsaac**
### What does this PR do?
Closes  #16622

- fix misnamed `closedirSync` call to `closeSync` (if only we had type checking...
- fill in method stub for `fs.Dir.prototype.closeSync`
- throw `ERR_DIR_CLOSED` when `dir.read[Sync]()` is called after `dir.close[Sync]()`'

### How did you verify your code works?

I added tests

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 9:27 PM PT - Jan 23rd, 2025</sup></div>

@DonIsaac, your commit ff9da490678a0f8c59ab88ac440b1ac9ca363fe8 is building: [`#10440`](https://buildkite.com/bun/bun/builds/10440)

**Comment by staabm** [comment]
the added file is empty

grafik
