### ISSUE TITLE
Missing closedirSync in fs

### ISSUE THREAD

**Issue by rboati** [oven-sh/bun#16622]
### What version of Bun is running?

1.2.0

### What platform is your computer?

Linux 6.12.10-amd64 x86_64 unknown

### What steps can reproduce the bug?

This function no longer works in bun 1.2:
```ts
export async function isDirectoryEmpty(directory) {
	const dirHandle = await fsp.opendir(directory)
	const iter = dirHandle[Symbol.asyncIterator]()
	let next = await iter.next()
	while (!next.done) {
		await dirHandle.close()
		return false
	}
	return true
}
```
Failing with error message:
```ts
TypeError: fs.closedirSync is not a function. (In 'fs.closedirSync(this.#handle)', 'fs.closedirSync' is undefined)
      at close (node:fs:423:27)
```

### What is the expected behavior?

The function should not fail

### What do you see instead?

```ts
TypeError: fs.closedirSync is not a function. (In 'fs.closedirSync(this.#handle)', 'fs.closedirSync' is undefined)
      at close (node:fs:423:27)
```

### Additional information

The method `dirHandle.close()` is invoking internally `closedirSync()` but it cannot find it
