### ISSUE TITLE
`bun-types@1.1.40` is missing `toMatchInlineSnapshot` type

### ISSUE THREAD

**Issue by seveibar** [oven-sh/bun#15863]
### What version of Bun is running?

1.1.40+b5b51004e

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

```ts
import { test, expect } from "bun:test"

test("toMatchInlineSnapshot", () => {
  // Throws type error
  expect(true).toMatchInlineSnapshot()
})
```

### What do you see instead?

```
Property 'toMatchInlineSnapshot' does not exist on type 'Matchers<RegExpMatchArray | null>'. Did you mean 'toMatchSnapshot'?ts(2551)
```

I don't example understand why this is happening because the type definition seems to be defined in `bun-types` here:

https://github.com/oven-sh/bun/blob/e66a3471586d1258ccfdf7afbaddb8362e46415b/packages/bun-types/test.d.ts#L1322

**Comment by seveibar** [comment]
Here's a hotfix:

```ts
declare module "bun:test" {
  interface Matchers<T = unknown> {
    toMatchInlineSnapshot(snapshot?: string | null): Promise<MatcherResult>
  }
}
```

**Comment by mary-ext** [comment]
it seems to be present in bun-types@1.1.42

**Comment by seveibar** [comment]
If you install the latest @bun/types (version 1.1.15 for me) it seems to be fixed now

**Comment by seveibar** [comment]
Re-opening because I tried this on a recent project and it still didn't work with bun types version 1.1.15
