### PR TITLE
bundler: pass the real import.meta to cjs output for the bun target

### PR DESCRIPTION
**Pull request by robobun**
### Problem
- `bun build --compile --bytecode` bakes the build machine's source paths into `import.meta.path`, `.dir`, `.file` and `.url`. Without `--bytecode` the same build reports `/$bunfs/root/<name>`. `--format=cjs` alone does the same. `--asset` lookups under `import.meta.dir` break, and every shipped binary contains the build tree.
- Cause: `src/js_parser/fold.rs:513` inlines those properties as the source paths for all cjs output (#23803, for the `import.meta is only valid inside modules` SyntaxError of #14954). Every other use of `import.meta` still throws that SyntaxError in cjs output, which is #21097.

### Fix
- Bun's CommonJS wrapper already passes the module's real `import.meta` as a sixth argument when the wrapper declares one (`JSCommonJSModule.cpp:228`). `LinkerContext::chunk_has_bun_cjs_wrapper` decides once per chunk whether the chunk gets the `@bun-cjs` wrapper. The header and footer, the chunk renamer (which reserves the name `$Bun_import_meta` there) and a printer option for every file in the chunk use that answer.
- Inside such a chunk the printer prints `import.meta` as `$Bun_import_meta` and reports that on its result. The header declares the argument when any part range reported it. Chunks without the wrapper, such as the browser chunk of an HTML import, print `import.meta` as before.
- The parser inlines the source paths only for Bake and for cjs output of files whose target is not bun (`inline_import_meta_paths`, set in `ParseTask`).
- Correct because the runtime builds the object the way the ESM loader does (`ZigGlobalObject.cpp:3923`), so cjs output gets the ESM values for every property. Output that does not use `import.meta` is unchanged.
- Verified: `test/bundler/bundler_bun.test.ts`, 7 new tests, 6 fail on the released build. Other suites are listed in the notes.

### Background
- cjs output for bun is a `(function(exports, require, module, __filename, __dirname) {...})` script that the runtime calls, and that `--bytecode` compiles. `import.meta` is a syntax error in a script. A bun build with an HTML import also emits browser chunks, which are plain module scripts without the wrapper.
- `$Bun_import_meta` is the name the runtime transpiler already uses for this argument when it wraps a CommonJS file that uses `import.meta`. Both sites read `E::ImportMeta::CJS_WRAPPER_ARG`.
- Reserved names are names the renamer gives to no symbol in a chunk. `exports` and `module` are reserved in cjs output the same way, which is what lets the printer emit `require.main == module` by name.
- `PrintResultSuccess` is what the printer returns per part range. #37677 derives the ESM bytecode module record from what the printer emitted instead of from the AST. The new `uses_import_meta_arg` flag on it follows that pattern.

Fixes #21097

<details><summary>Notes</summary>

Repro on main, and the binary built from this branch:

```
$ cat ident.ts
console.log(JSON.stringify({ path: import.meta.path, dir: import.meta.dir, url: import.meta.url, main: import.meta.main, bunMain: Bun.main }));
$ bun build --compile --bytecode ./ident.ts --outfile ./bc && ./bc
# main:  {"path":"/tmp/proj/ident.ts","dir":"/tmp/proj","url":"file:///tmp/proj/ident.ts","main":true,"bunMain":"/$bunfs/root/bc"}
# fixed: {"path":"/$bunfs/root/bc","dir":"/$bunfs/root","url":"file:///$bunfs/root/bc","main":true,"bunMain":"/$bunfs/root/bc"}
$ strings ./bc | grep -c /tmp/proj
# main: 4, fixed: 0. A file that also uses __dirname keeps the hits of the __dirname inlining, see below.
```

The sixth argument hook dates from #3104 (2023), so it predates `@bun-cjs` output (#14232). Bundles built this way load on every Bun that can load `@bun-cjs` output. #19250's closing note lists these inlined `import.meta` values as the remaining build paths in a `--bytecode` binary.

Output of a plain `bun build --target=bun --format=cjs` for a file that uses `import.meta`, plus a `.cjs` dependency that uses it too:

```js
// @bun @bun-cjs
(function(exports, require, module, __filename, __dirname, $Bun_import_meta) {
// lib/dep.cjs
var require_dep = __commonJS(function(exports2) {
  exports2.pathOfDep = () => $Bun_import_meta.path;
});
// entry.ts
var $Bun_import_meta2 = "user variable";
console.log($Bun_import_meta.path === Bun.main);
})
```

A user variable with the reserved name is renamed, in nested scopes too. `--minify` output keeps the argument because the header is printed by the linker. Non-compile `--target=bun --format=cjs` bundles change as well: `import.meta.dir` is now the output directory at run time, which is what esm output of the same build already reported. cjs output for node and browser, esm output, iife output and Bake are unchanged. The embedded sqlite module, which the loader builds as `import.meta.require(...)` without the parser, now works in cjs output too, because the argument is declared from what the printer emitted, not from a parser flag.

Revision history. The first revision keyed the printer on the build's target and declared the argument from the per-file `HAS_IMPORT_META` flag. Review of that revision found two things. The sqlite module has no such flag, so it was patched with one (commit 767beef, now removed). And a bun build with an HTML import prints browser chunks with the same printer options, so `import.meta.env` in a client file became a bare `$Bun_import_meta` reference in a chunk that has no wrapper (main ships `import.meta` there). Reproduced with this branch's debug build before the rework. The current revision keys everything on `chunk_has_bun_cjs_wrapper` and is covered by `bun/ImportMetaFormatCjsHtmlImport`, which checks that the browser chunk still contains `import.meta` and that only the server chunk is wrapped. A `--target=node --format=cjs` build whose entry has a `#!/usr/bin/env bun` hashbang gets the wrapper today, because the entry's own target is bun. The entry file now uses the argument (its target is bun, so nothing is inlined) and the other files keep the inlined paths. Checked: such a bundle runs, and `import.meta.env` in it used to be a SyntaxError.

Related open PRs, and how this composes with them:

- #38173 makes the sqlite module print `require(...)` in cjs output. No shared lines any more. Its tests pin `require(`, the test here only runs the bundle, so both pass in either order.
- #33859 narrows when a chunk counts as bun for the pragma and the wrapper. That decision now has one home, `chunk_has_bun_cjs_wrapper`, so its narrowing goes there, and the header block has a small textual conflict either way.
- #38200 lowers `import.meta` to an empty per-file object for cjs and iife output of other targets. Whichever lands second excludes the files this PR leaves alone (cjs output for bun), where the wrapper supplies the real object. Its `inline_import_meta` gate and `inline_import_meta_paths` here are the same predicate.
- #29066 makes `__dirname` / `__filename` use the virtual path in `--compile` output (the CJS sibling in the fuzz ledger). It also rewrites `import.meta.dir/.dirname/.path/.filename` to those identifiers for `--compile` cjs output and leaves `.url` and `.file` inlined. With this PR that fold.rs hunk is not needed. Its `__dirname` change and Windows separator fix are independent.

Found while testing and handed off separately: two bundled modules that both use `__dirname` collide (the last declaration wins), and `new Worker(new URL("./w.ts", import.meta.url))` from the executables docs fails in every standalone executable with `ModuleNotFound /$bunfs/root/w.ts` (the `.ts` to `.js` remap only applies to relative specifiers). A `--bytecode` build of that docs example only appeared to work before because it loaded the worker from the source tree on the build machine.

Test placement: `compile/HelloWorldWithProcessVersionsBun` in `bundler_compile.test.ts` fails on every debug build independent of this change, so the new compile case lives in `bundler_bun.test.ts`, which is green on a debug build. The compile case also reads `import.meta.env`, which is the #21097 program. Three `bake/dev/production` tests timed out locally at the 5 s default and pass with a longer timeout. They do not involve `import.meta`.

Suites run with the debug build after the rework: `bundler_bun` (17 tests), `bundler_banner`, `bundler_cjs`, `html-import-manifest`, `bundler_html_server`, `bundler_edgecase`, `bun-build-api`, `esbuild/default -t "ImportMeta|import.meta"`, `bundler_compile -t "Bytecode|ImportMeta|pathToFileURLWorks|sqlite|html"`, `bake/dev/import-meta-inline`, `js/bun/resolve/import-meta`. `cargo clippy` and `cargo fmt` are clean for the four touched crates.
</details>

---

**[human-review]** gate passed · iteration 1 · 14 files touched

<details><summary>fails on main (without fix)</summary>

```console
ASAN without fix: 6 FAILED
$ BUN_DEBUG_QUIET_LOGS=1 bun scripts/build.ts --profile=debug --quiet test "--reporter=junit" "--reporter-outfile=/tmp/pr_gate.xml" test/bundler/bundler_bun.test.ts
bun test v1.4.3 (e0a2b82fd)

test/bundler/bundler_bun.test.ts:
(pass) bundler > bun/bytecode-depth-cli [1122.23ms]
(pass) bundler > bun/bytecode-depth-api [487.06ms]
(pass) bundler > bun/import-bun-format-cjs [446.69ms]
(pass) bundler > bun/embedded-sqlite-file [411.87ms]
(pass) bundler > bun/sqlite-file [388.10ms]
(pass) bundler > bun/TargetBunNoSourcemapMessage [448.36ms]
(pass) bundler > bun/TargetBunSourcemapInline [454.11ms]
(pass) bundler > bun/unicode comment [340.15ms]
233 |       // --bytecode writes a second file, which the CLI only allows with --outdir.
234 |       ...(bytecode ? { outdir: "/out" } : {}),
235 |       files: importMetaFiles,
236 |       onAfterBundle(api) {
237 |         const out = api.readFile(bytecode ? "/out/entry.js" : "/out.js");
238 |         expect(out).toStartWith(bunCjsWrapper(bytecode ? "@bytecode " : "", ", $Bun_import_meta"));
                          ^
error: expect(received).toStartWith(expected)

Expected to start with: "// @bun @bun-cjs\n(function(exports, req
... (truncated)

release without fix: all passed
bun test v1.4.3-canary.1 (954f4cde7)

test/bundler/bundler_bun.test.ts:
(pass) bundler > bun/bytecode-depth-cli [22.42ms]
(pass) bundler > bun/bytecode-depth-api [9.64ms]
(pass) bundler > bun/import-bun-format-cjs [7.16ms]
(pass) bundler > bun/embedded-sqlite-file [8.42ms]
(pass) bundler > bun/sqlite-file [6.86ms]
(pass) bundler > bun/TargetBunNoSourcemapMessage [8.13ms]
(pass) bundler > bun/TargetBunSourcemapInline [7.88ms]
(pass) bundler > bun/unicode comment [6.11ms]
(pass) bundler > bun/ImportMetaFormatCjs [8.01ms]
(pass) bundler > bun/ImportMetaFormatCjs+minify [7.42ms]
(pass) bundler > bun/ImportMetaFormatCjs+bytecode [10.47ms]
(pass) bundler > bun/ImportMetaFormatCjsUnused [7.23ms]
(pass) bundler > bun/ImportMetaFormatCjsEmbeddedSqlite [7.49ms]
(pass) bundler > bun/ImportMetaFormatCjsHtmlImport [6.44ms]
(pass) bundler > bun/ImportMetaCompileBytecode [148.66ms]
(pass) bundler > bun/ExportsConditionsDevelopmentAPI [8.41ms]
(pass) bundler > bun/ExportsConditionsDevelopmentInProductionAPI [7.06ms]
(pass) bundler > bun/ExportsConditionsDevelopmentCLI [8.33ms]
(pass) bundler > bun/ExportsConditionsDevelopmentInProductionCLI [8.02ms]

 19 pass
 0 fail
 44 expect() c
... (truncated)
```

</details>

<details><summary>passes on PR (with fix)</summary>

```console
ASAN with fix: all passed
$ BUN_DEBUG_QUIET_LOGS=1 bun scripts/build.ts --profile=debug --quiet test "--reporter=junit" "--reporter-outfile=/tmp/pr_gate.xml" test/bundler/bundler_bun.test.ts
bun test v1.4.3 (e0a2b82fd)

test/bundler/bundler_bun.test.ts:
(pass) bundler > bun/bytecode-depth-cli [990.43ms]
(pass) bundler > bun/bytecode-depth-api [456.81ms]
(pass) bundler > bun/import-bun-format-cjs [439.49ms]
(pass) bundler > bun/embedded-sqlite-file [418.60ms]
(pass) bundler > bun/sqlite-file [406.53ms]
(pass) bundler > bun/TargetBunNoSourcemapMessage [559.97ms]
(pass) bundler > bun/TargetBunSourcemapInline [456.70ms]
(pass) bundler > bun/unicode comment [345.19ms]
(pass) bundler > bun/ImportMetaFormatCjs [650.53ms]
(pass) bundler > bun/ImportMetaFormatCjs+minify [562.79ms]
(pass) bundler > bun/ImportMetaFormatCjs+bytecode [783.74ms]
(pass) bundler > bun/ImportMetaFormatCjsUnused [434.43ms]
(pass) bundler > bun/ImportMetaFormatCjsEmbeddedSqlite [596.85ms]
(pass) bundler > bun/ImportMetaFormatCjsHtmlImport [378.73ms]
(pass) bundler > bun/ImportMetaCompileBytecode [3453.59ms]
(pass) bundler > bun/ExportsConditionsDevelopmentAPI [353.04ms]
(pass) bundler > bun/ExportsConditionsDevelopmentInProduc
... (truncated)

release with fix: all passed
$ bun scripts/build.ts --profile=release
[configured] bun-profile → bun (stripped) in 616ms (unchanged)
ninja: Entering directory `/workspace/bun/build/release'
[0/5] cargo bun_runtime → libbun_runtime.a
[1m[92m   Compiling[0m bun_core v0.0.0 (/workspace/bun/src/bun_core)
[1m[92m   Compiling[0m bun_errno v0.0.0 (/workspace/bun/src/errno)
[1m[92m   Compiling[0m bun_ptr v0.0.0 (/workspace/bun/src/ptr)
[1m[92m   Compiling[0m bun_boringssl_sys v0.0.0 (/workspace/bun/src/boringssl_sys)
[1m[92m   Compiling[0m bun_safety v0.0.0 (/workspace/bun/src/safety)
[1m[92m   Compiling[0m bun_base64 v0.0.0 (/workspace/bun/src/base64)
[1m[92m   Compiling[0m bun_cares_sys v0.0.0 (/workspace/bun/src/cares_sys)
[1m[92m   Compiling[0m bun_zlib_sys v0.0.0 (/workspace/bun/src/zlib_sys)
[1m[92m   Compiling[0m bun_zstd v0.0.0 (/workspace/bun/src/zstd)
[1m[92m   Compiling[0m bun_picohttp v0.0.0 (/workspace/bun/src/picohttp)
[1m[92m   Compiling[0m bun_brotli v0.0.0 (/workspace/bun/src/brotli)
[1m[92m   Compiling[0m bun_output v0.0.0 (/workspace/bun/src/output)
[1m[92m   Compiling[0m bun_clap v0.0.0 (/workspace/bun/src/clap)
[1m[92m   Compiling[0m bu
... (truncated)
```

</details>

<details><summary>diff hotspot</summary>

```
src/ast/e.rs                                       |   5 +
 src/bundler/LinkerContext.rs                       |   8 ++
 src/bundler/ParseTask.rs                           |   4 +
 src/bundler/bundle_v2.rs                           |   7 +-
 .../linker_context/generateCodeForFileInChunkJS.rs |   8 +-
 .../generateCompileResultForJSChunk.rs             |   2 +
 src/bundler/linker_context/postProcessJSChunk.rs   |  55 ++++---
 src/bundler/linker_context/renameSymbolsInChunk.rs |   5 +
 src/bundler/transpiler.rs                          |   1 +
 src/js_parser/fold.rs                              |   8 +-
 src/js_parser/p.rs                                 |   2 +-
 src/js_parser/parse/parse_entry.rs                 |   6 +
 src/js_printer/lib.rs                              |  32 +++--
 test/bundler/bundler_bun.test.ts                   | 158 +++++++++++++++++++++
 14 files changed, 253 insertions(+), 48 deletions(-)
```

</details>

**gate history** · 3 passed · 0 rejected · iteration 1

<details><summary>evidence per changed file</summary>

```
file                                                      reads  edits  tests
src/ast/e.rs                                                  3      4     21
src/bundler/LinkerContext.rs                                  4      3     21
src/bundler/ParseTask.rs                                     10      7     21
src/bundler/bundle_v2.rs                                      2      1     21
…/bundler/linker_context/generateCodeForFileInChunkJS.rs      3      4     21
…ndler/linker_context/generateCompileResultForJSChunk.rs      1      2     21
src/bundler/linker_context/postProcessJSChunk.rs             11     10     21
src/bundler/linker_context/renameSymbolsInChunk.rs            3      2     21
src/bundler/transpiler.rs                                     2      1     21
src/js_parser/fold.rs                                         2      2     21
src/js_parser/p.rs                                            7      1     21
src/js_parser/parse/parse_entry.rs                            6      6     21
src/js_printer/lib.rs                                        11     10     21
test/bundler/bundler_bun.test.ts                              5     11     21
```

</details>

**root cause** · written by the author bot

When the bundler lowers a Bun target to CommonJS (which `--bytecode` implies), the parser inlines `import.meta.url`, `import.meta.path`, `import.meta.dir`, and `import.meta.file` as string constants taken from the build machine's source path, so the standalone executable reports the build directory instead of the virtual `/$bunfs/root/<name>` location that the non-CJS compile uses. The fix makes `inline_import_meta_paths` an explicit opt-in that stays off for Bun CommonJS compile output and instead threads a wrapper argument through the linker and printer, so the Bun CJS module wrapper rece…

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 11:07 PM PT - Aug 19th, 2026</sup></div>

@robobun, your commit abc4ede1fc054bf7ac1ca8e96939fde0dcb69abd is building: [`#101515`](https://buildkite.com/bun/bun/builds/101515)

**Comment by robobun** [comment]
**Status**: ready for review.

**Reproduced** on main (`cfa9f8e1`) with `bun build --compile --bytecode ./ident.ts --outfile bc && ./bc`, where `ident.ts` prints `import.meta.path`, `.dir`, `.url` and `Bun.main`: the first three are the build directory's paths, `Bun.main` is `/$bunfs/root/bc`. `strings bc | grep -c <build dir>` is 4. With this branch all four values are under `/$bunfs/root` and the count is 0.

**Verification**: `bun bd test test/bundler/bundler_bun.test.ts` passes (15 tests). On the released build the 4 new cjs, cjs+minify, cjs+bytecode and compile+bytecode cases fail with the inlined build paths, the `import.meta.filename` SyntaxError, and `false false false false <build dir>` from the executable.

File: src/js_printer/lib.rs [hunk 1]
```diff
@@ -2974,23 +2974,27 @@ pub(crate) mod __gated_printer {
...
+                    {
+                        // `post_process_js_chunk` declares this argument on the
+                        // `@bun-cjs` wrapper of every chunk whose files use import.meta.
+                        self.print(E::ImportMeta::CJS_WRAPPER_ARG);
+                    } else {
+                        // Most of the time, leave it in there
+                        if let Some(mi) = self.module_info() {
+                            mi.flags.contains_import_meta = true;
+                        }
+                        self.print(b"import.meta");
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/js_printer/lib.rs:3315]: The TODO and the assertion predate this PR. This branch is the runtime transpiler's wrapper (WrapMode::BunCommonjs), which the bundler never uses, so the new branch below does not change it. I checked `bun build --no-bundle` with and without `--format=cjs` on a .cjs file that uses import.meta with a debug build: neither trips the assertion. I am leaving that line as it is, since whatever case the TODO refers to is outside this change.

File: test/bundler/bundler_bun.test.ts [hunk 2]
```diff
@@ -137,6 +137,146 @@ error: Hello World`,
...
+      // source, but cjs output never keeps that part, so the wrapper does not
+      // take the argument.
+      expect(api.readFile("/out.js")).toStartWith(
+        "// @bun @bun-cjs\n(function(exports, require, module, __filename, __dirname) {",
+      );
+    },
+    run: { stdout: "no import.meta here" },
+  });
+  // The sqlite loader builds its module as `import.meta.require(...)` without
+  // parsing anything, so it is the one import.meta the parser does not see.
```
[the remark this answers is not in the document]
Comment (robobun) [reply test/bundler/bundler_bun.test.ts]: There is no GitHub issue for this case. It came up while reviewing this PR (the sqlite loader is the one import.meta the parser never sees), so there is no URL to add.

File: src/ast/e.rs [hunk 3]
```diff
@@ -201,6 +201,19 @@ pub struct Super;
...
+impl ImportMeta {
+    /// Sixth parameter of Bun's CommonJS module wrapper,
+    /// `(exports, require, module, __filename, __dirname, $Bun_import_meta)`.
+    /// `evaluateCommonJSModuleOnce` (JSCommonJSModule.cpp) passes the module's
+    /// `import.meta` object for it whenever the wrapper declares more than five
+    /// parameters. The runtime transpiler declares it for CommonJS files that
+    /// use `import.meta`. The bundler declares it on the `@bun-cjs` wrapper of
+    /// a chunk that uses `import.meta` and prints every `import.meta` in the
+    /// chunk as this name, so the values describe the output file at run time,
+    /// exactly like `import.meta` in esm output.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/ast/e.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/bundler/ParseTask.rs [hunk 4]
```diff
@@ -1061,18 +1061,20 @@ pub mod parse_worker {
...
+                    &mut topts.define,
+                    opts,
+                    log,
+                    root,
+                    source,
+                    b"",
+                )?
+                .ok_or(AnyError::ParserError)?;
+                // Only the parser sets this when it reads `import.meta`. cjs
+                // output declares the wrapper's import.meta argument based on it.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/bundler/ParseTask.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/bundler/ParseTask.rs [hunk 5]
```diff
@@ -2606,6 +2608,14 @@ pub mod parse_worker {
             opts.lower_import_meta_main_for_node_js = true;
         }
 
+        // cjs output for bun keeps `import.meta` as written: the linker adds
+        // `E::ImportMeta::CJS_WRAPPER_ARG` to the `@bun-cjs` wrapper and the
+        // printer prints `import.meta` as that argument (see
+        // `post_process_js_chunk`). Both key off the build's target, so this
+        // does too, not off a per-file hashbang override.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/bundler/ParseTask.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/bundler/linker_context/postProcessJSChunk.rs [hunk 6]
```diff
@@ -36,6 +36,33 @@ fn print_result_take_code(r: &mut PrintResult) -> Box<[u8]> {
...
+/// of a file in the chunk as that name when the build targets bun with cjs
+/// output, which is the same condition as here (both read `c.options`, so a
+/// `#!/usr/bin/env bun` hashbang that only switches the entry point's own
+/// target does not count). Every AST with an `import.meta` node carries
+/// `HAS_IMPORT_META`: the parser sets it, and the sqlite loader sets it on
+/// the AST it synthesizes (`ParseTask`).
+///
+/// The runtime module is skipped. Its one `import.meta` is the `__require`
+/// definition, and cjs output never links `__require` in
+/// (`should_call_runtime_require`).
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/bundler/linker_context/postProcessJSChunk.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/js_parser/parse/parse_entry.rs [hunk 7]
```diff
@@ -94,6 +94,13 @@ pub struct Options<'a> {
     pub import_meta_main_value: Option<bool>,
     pub lower_import_meta_main_for_node_js: bool,
 
+    /// Replace `import.meta.dir`, `.dirname`, `.file`, `.path` and `.url` with
+    /// the source file's own paths at bundle time. Bake wants the source
+    /// paths. cjs output for a target other than bun has no `import.meta` at
+    /// run time, so the source paths are the only values available there.
+    /// Set by the bundler (`ParseTask`).
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/js_parser/parse/parse_entry.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/js_printer/lib.rs [hunk 8]
```diff
@@ -2974,23 +2974,27 @@ pub(crate) mod __gated_printer {
...
-                        self.print(b"import.meta");
-                    } else {
-                        // Note: The bundler will not hit this code path. The bundler will replace
-                        // the ImportMeta AST node with a regular Identifier AST node.
-                        //
-                        // This is currently only used in Bun's runtime for CommonJS modules
-                        // referencing import.meta
+                    } else if self.options.import_meta_ref.is_valid() {
+                        // Bun's runtime wrapping a CommonJS module that references import.meta.
+                        // The bundler never sets `import_meta_ref`.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/js_printer/lib.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/js_printer/lib.rs [hunk 9]
```diff
@@ -2974,23 +2974,27 @@ pub(crate) mod __gated_printer {
...
                         // TODO: This assertion trips when using `import.meta` with `--format=cjs`
                         debug_assert!(self.options.module_type == bundle_opts::Format::Cjs);
 
                         self.print_symbol(self.options.import_meta_ref);
+                    } else if self.options.bundling
+                        && self.options.module_type == bundle_opts::Format::Cjs
+                        && self.options.target.is_bun()
+                    {
+                        // `post_process_js_chunk` declares this argument on the
+                        // `@bun-cjs` wrapper of every chunk whose files use import.meta.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/js_printer/lib.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/js_printer/renamer.rs [hunk 10]
```diff
@@ -1086,6 +1090,9 @@ pub fn compute_initial_reserved_names(
     // using these names in this case even if there is not a risk of a name
     // collision because there is still a risk of node incorrectly detecting
     // something in a nested scope as an top-level export.
+    //
+    // The printer emits the import.meta argument of the `@bun-cjs` wrapper by
+    // name, so no symbol in the chunk may be given that name either.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/js_printer/renamer.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/ast/e.rs [hunk 11]
```diff
@@ -201,6 +201,14 @@ pub struct Super;
 #[derive(Clone, Copy, Default)]
 pub struct ImportMeta;
 
+impl ImportMeta {
+    /// Sixth parameter of Bun's CommonJS module wrapper. `evaluateCommonJSModuleOnce`
+    /// (JSCommonJSModule.cpp) passes the module's `import.meta` for it when the wrapper
+    /// declares more than five parameters. Declared by the runtime transpiler and by the
+    /// bundler's `@bun-cjs` wrapper.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/ast/e.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/bundler/ParseTask.rs [hunk 12]
```diff
@@ -2606,6 +2607,11 @@ pub mod parse_worker {
             opts.lower_import_meta_main_for_node_js = true;
         }
 
+        // For bun, cjs output gets import.meta from the `@bun-cjs` wrapper instead
+        // (`chunk_uses_import_meta`), which reads the build target like this does.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/bundler/ParseTask.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/bundler/linker_context/postProcessJSChunk.rs [hunk 13]
```diff
@@ -36,6 +36,25 @@ fn print_result_take_code(r: &mut PrintResult) -> Box<[u8]> {
     }
 }
 
+/// Whether the `@bun-cjs` wrapper must declare `E::ImportMeta::CJS_WRAPPER_ARG`.
+/// Must match the printer's `EImportMeta` condition, which also reads `c.options`.
+/// The runtime module's only `import.meta` is `__require`, which cjs output never
+/// links in (`should_call_runtime_require`).
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/bundler/linker_context/postProcessJSChunk.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/js_parser/parse/parse_entry.rs [hunk 14]
```diff
@@ -94,6 +94,10 @@ pub struct Options<'a> {
     pub import_meta_main_value: Option<bool>,
     pub lower_import_meta_main_for_node_js: bool,
 
+    /// Replace `import.meta.dir`, `.dirname`, `.file`, `.path` and `.url` with the
+    /// source file's paths (Bake, and cjs output that has no `import.meta` at run time).
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/js_parser/parse/parse_entry.rs]: Shortened to one line in 8b4d92c. The remaining sentence records which other code this has to agree with.

File: src/bundler/LinkerContext.rs [hunk 15]
```diff
@@ -2157,6 +2157,13 @@ impl<'a> LinkerContext<'a> {
         Ok(true)
     }
 
+    /// Whether `post_process_js_chunk` wraps `chunk` in the `@bun-cjs` function wrapper.
+    /// The chunk renamer and the printer of every file in the chunk key off the same answer.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/bundler/LinkerContext.rs]: Reduced to one line in a48bb23.

File: src/js_printer/lib.rs [hunk 16]
```diff
@@ -1145,6 +1145,9 @@ pub struct Options<'a> {
     pub to_esm_ref: Ref,
     pub require_ref: Option<Ref>,
     pub import_meta_ref: Ref,
+    /// The bundler prints this file inside the `@bun-cjs` function wrapper, whose
+    /// `E::ImportMeta::CJS_WRAPPER_ARG` parameter stands in for `import.meta`.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/js_printer/lib.rs]: Reduced to one line in a48bb23.

**Comment by robobun** [comment]
Closed #28692 in favor of this PR. On a build of this branch, the `--compile --bytecode` test from #28692 passes, and so does the repro from #21097 with the exact flags from the issue (`bun build --compile --minify --sourcemap --bytecode`). The other change in #28692, exit code 1 when bytecode generation fails, is covered by #36708.

**Comment by robobun** [comment]
This also fixes #40903, the worker case: in a `--compile --bytecode` (or `--compile --format=cjs`) binary, `new Worker(new URL("./worker.ts", import.meta.url))` resolved against the baked build-machine path, loaded the on-disk source, and failed with `Cannot find module '@babel/parser' from '/private/tmp/repro/babel-worker.ts'`.

I verified this branch merged with current main (1ab272b833, which has #40619): the repro from #40903 now prints `metaUrl: "file:///$bunfs/root/babel-worker.js"` and the worker resolves its bundled imports, with and without `--bytecode`, and with the source directory removed. Consider adding "Fixes #40903" to the body.

**Comment by robobun** [comment]
Verified a case from a fuzz matrix on top of current main (`1ab272b833`, merged cleanly, debug build): an entry point that calls `import.meta.resolve(...)` and `import.meta.require(...)` under `--compile --bytecode` (default cjs format).

```
echo 'export const b=2;' > b.ts; echo 'module.exports={x:1}' > c.cjs
printf 'console.log("start");\nconsole.log(import.meta.resolve("./b.ts"));\nconsole.log(JSON.stringify(import.meta.require("./c.cjs")));\n' > bc.ts
bun build --compile --bytecode ./bc.ts ./b.ts ./c.cjs --outfile app && ./app
```

On main this prints `error: Failed to generate bytecode for ./bc.js`, exits 0, and the executable dies with `SyntaxError: import.meta is only valid inside modules` (the debug build panics earlier in `OutputFileList::take`, see #36708). With this branch the build generates bytecode for the chunk and the executable prints `start`, `file:///$bunfs/root/b.ts`, `{"x":1}`. The same holds for `--compile --format=cjs` without bytecode, and `--target=bun --bytecode --outdir` writes the `.jsc` file.

**Comment by max-leuthaeuser** [comment]
Any update? What is the expected timeline to get this merged/released?

**Comment by robobun** [comment]
Rebased onto current main (`c01965ff72`). The six commits are squashed into one. The only conflict was in `postProcessJSChunk.rs`, where main added `module_preload_registration` next to the new `chunk_uses_import_meta_arg` helper. Both are kept.

Verified on main before the rebase that this PR is still needed. With a debug build of `c01965ff72`:

- `bun build --compile --bytecode` still bakes the build machine path into `import.meta.path`, `.dir` and `.url`. The #40903 repro (a `Worker` created from `new URL("./worker.ts", import.meta.url)`) still fails with `ModuleNotFound resolving "/tmp/proj/src/worker.ts"` once the source tree is gone. With the source tree present the worker loads from disk, which is why the binary can appear to work.
- `import.meta.env` under `--compile --bytecode` is still `SyntaxError: import.meta is only valid inside modules` at build time (#21097).
- Of the 7 new tests in `bundler_bun.test.ts`, 6 fail on main. All 19 tests in that file pass on this branch.

Also run on the rebased build: `bundler_cjs`, `bundler_banner`, `bundler_html_server`, `bundler_edgecase`, `js/bun/resolve/import-meta`, `bundler_compile -t "Bytecode|ImportMeta|pathToFileURLWorks|sqlite|html|Worker"`, `esbuild/default -t "ImportMeta|import.meta"`. All pass.
