### ISSUE TITLE
Getting error 'response.headers.hasOwnProperty' is undefined' after upgrading to bun v1.0.10

### ISSUE THREAD

**Issue by apd-f** [oven-sh/bun#6973]
### What version of Bun is running?

1.0.10+d85bd49d8

### What platform is your computer?

Linux 6.5.6-76060506-generic x86_64 x86_64

### What steps can reproduce the bug?

_This is my first bug report, I apologize if its incorrect/missing something._

When signing into my expressjs webapp via Azure AD using msal-node I get the following error:
```
4247 |      * Checks a NetworkResponse object's RetryAfter header
4248 |      * @param response
4249 |      */
4250 |     static checkResponseForRetryAfter(response) {
4251 |         if (response.headers) {
4252 |             return (response.headers.hasOwnProperty(HeaderNames.RETRY_AFTER) &&
                       ^
TypeError: response.headers.hasOwnProperty is not a function. (In 'response.headers.hasOwnProperty(HeaderNames.RETRY_AFTER)', 'response.headers.hasOwnProperty' is undefined)
      at checkResponseForRetryAfter (<project_directory>/node_modules/@azure/msal-common/dist/index.cjs:4252:20)
      at postProcess (<project_directory>/node_modules/@azure/msal-common/dist/index.cjs:4227:12)
      at <project_directory>/node_modules/@azure/msal-common/dist/index.cjs:4316:8
      at processTicksAndRejections (:61:76)
```

I have verified that it works on bun v1.0.9

I am using the basic configuration for msal-node, relevant files can be found here: [AuthConfig.js](https://github.com/Azure-Samples/ms-identity-node/blob/main/App/authConfig.js), [AuthProvider.js](https://github.com/Azure-Samples/ms-identity-node/blob/main/App/auth/AuthProvider.js)

### What is the expected behavior?

Login should follow msal-node redirect process and redirect to my post login screen, with azure ad user info stored in session

### What do you see instead?

I get redirected to my sites error page which displays the error message: response.headers.hasOwnProperty is not a function. (In 'response.headers.hasOwnProperty(HeaderNames.RETRY_AFTER)', 'response.headers.hasOwnProperty' is undefined) and there is no user info stored in the session

### Additional information

The only change I made was upgradeing to the latest bun version. Downgrading fixes the issue

**Comment by Jarred-Sumner** [comment]
oh no, it looks like `IncomingMessage` does not have a `null` prototype: 

https://github.com/nodejs/node/blob/1936160c31afc9780e4365de033789f39b7cbc0c/lib/_http_incoming.js#L114

But `OutgoingMessage` does have a`null` prototype:

https://github.com/nodejs/node/blob/1936160c31afc9780e4365de033789f39b7cbc0c/lib/_http_outgoing.js#L659
