### ISSUE TITLE
npm-upgrade CLI stopped working in 1.0.15: Cannot find module "@babel/runtime/helpers/interopRequireDefault"

### ISSUE THREAD

**Issue by dszymon** [oven-sh/bun#7456]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

1. Run `bunx npm-ugrade` or `bunx --bun npm-upgrade`

### What is the expected behavior?

```sh
npx npm-upgrade
Checking for outdated production, optional, development, peer and bundled dependencies for "/some/path"...
[================----] 22/27 81%
```

### What do you see instead?

with `--bun`:
```sh
error: Cannot find module "@babel/runtime/helpers/interopRequireDefault" from "/private/tmp/npm-upgrade@latest--bunx/node_modules/npm-upgrade/lib/bin/cli.js"
```

without:
```sh
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /private/tmp/npm-upgrade@latest--bunx/node_modules/npm-upgrade/lib/bin/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/private/tmp/npm-upgrade@latest--bunx/node_modules/npm-upgrade/lib/bin/cli.js:4:30)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/tmp/npm-upgrade@latest--bunx/node_modules/npm-upgrade/lib/bin/cli.js'
  ]
}

Node.js v20.9.0
```

### Additional information

it did work in 1.0.14

**Comment by dylan-conway** [comment]
This is a regression involving the `get-caller-file` package which is used by dependencies of `npm-upgrade`. `get-caller-file` uses `Error.prepareStackTrace` and `getFileName` to get the caller from the callsites.
```js
const getCallerFile = require("get-caller-file");
console.log(getCallerFile());
```
bun 1.0.13: /path/to/file/index.js
bun 1.0.15 prints an empty string.
