### ISSUE TITLE
[REGRESSION] Web build in 1.13.10 crashes with "is not a function"

### ISSUE THREAD

**Issue by Foorack** [oven-sh/bun#28886]
### What version of Bun is running?

1.3.10+30e609e08

### What platform is your computer?

Linux 6.17.0-1012-oem x86_64 x86_64

### What steps can reproduce the bug?

I created a minimally reproducable demo.

1. git clone https://github.com/Foorack/bun1-13-10-regression /tmp/bunreact
2. cd /tmp/bunreact
3. `bun --hot src/index.ts` # on both Bun 1.3.9 and 1.3.10

### What is the expected behavior?

foorack@hostname:/tmp/bunreact$ bun1.3.9 --hot src/index.ts 
Server running at http://localhost:3000/
Bundled page in 146ms: src/index.html
^C

### What do you see instead?

foorack@hostname:/tmp/bunreact$ bun --hot src/index.ts 
Server running at http://localhost:3000/
Bundled page in 106ms: src/index.html
frontend TypeError: import_react_combobox2.useComboboxBaseState is not a function
      at Object.useTagPicker_unstable (http://localhost:3000/_bun/client/index-00000000bbc03270.js:83521:54)
      at TagPicker (http://localhost:3000/_bun/client/index-00000000bbc03270.js:87497:42)
      at Object.react_stack_bottom_frame (http://localhost:3000/_bun/client/index-00000000bbc03270.js:101608:20)
      at renderWithHooks (http://localhost:3000/_bun/client/index-00000000bbc03270.js:92135:24)
      at updateFunctionComponent (http://localhost:3000/_bun/client/index-00000000bbc03270.js:93559:21)
      at updateSimpleMemoComponent (http://localhost:3000/_bun/client/index-00000000bbc03270.js:93413:16)
      at updateMemoComponent (http://localhost:3000/_bun/client/index-00000000bbc03270.js:93384:185)
      at beginWork (http://localhost:3000/_bun/client/index-00000000bbc03270.js:94276:20)
      at runWithFiberInDEV (http://localhost:3000/_bun/client/index-00000000bbc03270.js:88271:72)
      at performUnitOfWork (http://localhost:3000/_bun/client/index-00000000bbc03270.js:96769:98)
    from browser tab http://localhost:3000/
^C

### Additional information

1.13.0 = OK
1.13.6 = OK
1.13.9 = OK
1.13.10 = BROKEN
1.13.11 = BROKEN

**Comment by robobun** [comment]
🚀 Picked up — investigating the HMR regression from barrel optimization (#26892).
