### ISSUE TITLE
Cannot find module "client.node" using `bun build` with @tigerbeetle/tigerbeetle-node

### ISSUE THREAD

**Issue by rhodee** [oven-sh/bun#9951]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Steps to reproduce from the code in this repo: https://github.com/rhodee/bun-tigerbeetle

```sh
NODE_ENV=production bun build --compile --outfile=buntb --target=bun ./index.ts
./buntb
```

### What is the expected behavior?

The build should result in an artifact that exits (0). 

### What do you see instead?

The current behavior is an error looking for a `.node` file.

```
error: Cannot find module "./bin/aarch64-macos/client.node" from "/$bunfs/root/buntb"
```

### Additional information

The same behavior was observed in < bun v1.1 with this package too: https://www.npmjs.com/package/@connectrpc/connect-express. 

After upgrading to v1.1, `bun build` was successful. I wonder if this issue https://github.com/oven-sh/bun/issues/5139 is relevant for addressing the one I am currently experiencing?

**Comment by xcaeser** [comment]
same problem here, weirdly using tigerbeetle too

**Comment by Khaalidsub** [comment]
faced the same issue. I had this issue while creating a pnpm workspace with nestjs. Normal repo worked fine
