### ISSUE TITLE
Bug: Property 'aborted' does not exist on type 'AbortSignal'

### ISSUE THREAD

**Issue by nikelborm** [oven-sh/bun#22431]
### What version of Bun is running?

1.2.21+7c45ed97d

### What platform is your computer?

Linux 6.16.4-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

```bash
# Clone the repro repo
git clone https://github.com/nikelborm/bun-signal-aborted-repro.git

cd bun-signal-aborted-repro

# Install dependencies
bun install

# Works fine as expected
bun run index.ts
# Outputs:
# 1 signal.aborted:  false
# 2 signal.aborted:  true

# Fails
./node_modules/.bin/tsc
# Outputs
# index.ts:3:42 - error TS2339: Property 'aborted' does not exist on type 'AbortSignal'.
#
# 3 console.log('1 signal.aborted: ', signal.aborted);
#                                            ~~~~~~~
#
# index.ts:6:44 - error TS2339: Property 'aborted' does not exist on type 'AbortSignal'.
#
# 6   console.log('2 signal.aborted: ', signal.aborted);
#                                              ~~~~~~~
#
#
# Found 2 errors in the same file, starting at: index.ts:3
```

### What is the expected behavior?

The code below should not produce any ts errors

```ts
const signal = AbortSignal.timeout(20);

console.log('1 signal.aborted: ', signal.aborted);

setTimeout(() => {
  console.log('2 signal.aborted: ', signal.aborted);
}, 40);
```

### What do you see instead?

It does: `Property 'aborted' does not exist on type 'AbortSignal'.`

### Additional information

Repro: https://github.com/nikelborm/bun-signal-aborted-repro.git

**Comment by nikelborm** [comment]
It works fine in `1.2.6`, but in `1.2.7` and later it doesn't work.

in version of types `1.2.6`
```ts
const signal = AbortSignal.timeout(123);

console.log('1 signal.aborted: ', signal.aborted);

setTimeout(() => {
  console.log('2 signal.aborted: ', signal.aborted);
}, 40);
```
doesn't produce any errors

in version of types `1.2.7`
```ts
const signal = AbortSignal.timeout(123);

console.log('1 signal.aborted: ', signal.aborted);

setTimeout(() => {
  console.log('2 signal.aborted: ', signal.aborted);
}, 40);
```
it complains about `Property 'timeout' does not exist on type '{ new (): AbortSignal; prototype: AbortSignal; }'.ts(2339)`

And without timeout, the target error `Property 'aborted' does not exist on type 'AbortSignal'.` appears
```ts
const signal = new AbortSignal();

console.log('1 signal.aborted: ', signal.aborted);

setTimeout(() => {
  console.log('2 signal.aborted: ', signal.aborted);
}, 40);
```

**Comment by alii** [comment]
Fixed this and the regexp issue in #22439. Thank you for reporting both with excellent repros and detail 🙂
