### ISSUE TITLE
Vite/PostCSS/lightningcss build issue with Alpine docker image

### ISSUE THREAD

**Issue by marksamman** [oven-sh/bun#16915]
### What version of Bun is running?

1.2.1

### What platform is your computer?

image: oven/bun:1.2.1-alpine in CI

### What steps can reproduce the bug?

```
vite build
```

### What is the expected behavior?

No error

### What do you see instead?

```
error during build:
[vite:css] Failed to load PostCSS config (searchPath: /builds/projectname/frontend/src): [Error] Loading PostCSS Plugin failed: Cannot find module '../lightningcss.linux-x64-gnu.node' from '/builds/projectname/frontend/node_modules/lightningcss/node/index.js'
(@/builds/projectname/frontend/postcss.config.js)
Error: Loading PostCSS Plugin failed: Cannot find module '../lightningcss.linux-x64-gnu.node' from '/builds/projectname/frontend/node_modules/lightningcss/node/index.js'
(@/builds/projectname/frontend/postcss.config.js)
    at <anonymous> (/builds/projectname/frontend/node_modules/vite/dist/node/chunks/dep-M1IYMR16.js:14805:15)
    at processTicksAndRejections (native:7:[39](/projectname/frontend/-/jobs/105966#L39))
```

### Additional information

It worked fine with Bun 1.1.34 alpine image, some release after that broke it and it has been broken ever since (still broken in 1.2.0 and 1.2.1).
Works fine with the Debian Docker images.

**Comment by nicksrandall** [comment]
I ran into this same issue.

I believe the root of the issue is that the `detect-libc` library that lightningcss uses to detect your MUSL or GNU is incorrectly detecting the alpine image as GNU instead of MUSL.

There are a few ways to solve this:
- Make sure you have glibc installed on your alpine image (see note below)
- Patch the lightningcss package to force it to select MUSL (I haven't tested this but I *think* it could work)
- Just don't use alpine for now and move to Debian.

> Also note that there is a regression in Bun 1.2.1 that is preventing Vite from running properly. If you're going to do some testing, make sure do it on 1.2.0 (until the never version of Bun is released with a fix). 

## Adding glibc to alpine image
Add the following line to you alpine based docker image:

```
RUN apk add --no-cache libc6-compat make g++ python3
```

> I'm not sure that all of those are needed but that seemed to work for me.

**Comment by Kinqdos** [comment]
This was fixed by the latest tailwind version
