### ISSUE TITLE
Bun 1.3.1 error in vite build

### ISSUE THREAD

**Issue by Malvolio** [oven-sh/bun#24047]
### What version of Bun is running?

1.3.1+89fa0f343

### What platform is your computer?

Ubuntu   24.04.3

### What steps can reproduce the bug?

This is a complex Vite/TanstackStart app.

Everything works on 1.3.0 but the Vite build/TanstackStart pre-generation fails. 

### What is the expected behavior?

Should pre-render without issue

### What do you see instead?

```
website build: [prerender] Crawling: /faq
website build: Error in renderToPipeableStream: TypeError: v is not a function
website build:     at Nv (file:///home/runner/work/qrable/qrable/packages/cswww/dist/server/assets/router-q5x__LNj.js:61:46035)
website build:     at Uc (/home/runner/work/qrable/qrable/node_modules/.bun/react-dom@18.3.1+f4eacebf2041cd4f/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:70:44)
website build:     at Xc (/home/runner/work/qrable/qrable/node_modules/.bun/react-dom@18.3.1+f4eacebf2041cd4f/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:72:253)
website build:     at Z (/home/runner/work/qrable/qrable/node_modules/.bun/react-dom@18.3.1+f4eacebf2041cd4f/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
website build:     at Yc (/home/runner/work/qrable/qrable/node_modules/.bun/react-dom@18.3.1+f4eacebf2041cd4f/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:81:98)
website build:     at Xc (/home/runner/work/qrable/qrable/node_modules/.bun/react-dom@18.3.1+f4eacebf2041cd4f/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:73:145)
website build:     at Z (/home/runner/work/qrable/qrable/node_modules/.bun/react-dom@18.3.1+f4eacebf2041cd4f/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
website build:     at Yc (/home/runner/work/qrable/qrable/node_modules/.bun/react-dom@18.3.1+f4eacebf2041cd4f/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:81:98)
website build:     at Xc (/home/runner/work/qrable/qrable/node_modules/.bun/react-dom@18.3.1+f4eacebf2041cd4f/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:73:145)
website build:     at Z (/home/runner/work/qrable/qrable/node_modules/.bun/react-dom@18.3.1+f4eacebf2041cd4f/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89) undefined
```

### Additional information

 I don’t think it has anything to do with the specifics of my code, I think there is just an incompatibility with react-dom.
