### ISSUE TITLE
Setup dev env error when running 'make setup' command

### ISSUE THREAD

**Issue by teobler** [oven-sh/bun#6210]
### What platform is your computer?

Darwin 23.0.0 x86_64 i386

### What steps can reproduce the bug?

1. Clone the repo
2. install all the dependencies needed list in development doc
3. run 'make setup' in root dir

### What is the expected behavior?

should setup env successfully

### What do you see instead?

```bash
Build Summary: 1/4 steps succeeded; 1 failed (disable with --summary none)
obj transitive failure
├─ install generated to bun-debug.o transitive failure
│  ├─ zig build-obj bun-debug Debug native-native.11.0 1 errors
│  └─ zig build-obj bun-debug Debug native-native.11.0 (+1 more reused dependencies)
└─ zig build-obj bun-debug Debug native-native.11.0 (+1 more reused dependencies)
src/deps/c_ares.zig:1:1: error: type 'src.deps.c_ares.struct_nameinfo' does not support array initialization syntax
const c = @import("std").c;
^~~~~
referenced by:
    CallbackWrapper__anon_296660: src/deps/c_ares.zig:332:10
    getNameInfo__anon_172605: src/deps/c_ares.zig:633:44
    lookupService: src/bun.js/api/bun/dns_resolver.zig:2665:28
make[3]: *** [dev-obj-track] Error 2
make[2]: *** [zig-no-link] Error 2
make[1]: *** [dev] Error 2
make: *** [setup] Error 2
```

**Comment by Hanaasagi** [comment]
Please check your zig version (**0.12.0-dev.163+6780a6bbf**). I think this error is due to recent changes in compiler. https://github.com/ziglang/zig/issues/17127

**Comment by teobler** [comment]
Hi @Hanaasagi, thanks a lot, seems this issue is not fixed yet. 
Is that means I need to fix my zig version to **0.12.0-dev.163+6780a6bbf**, I'm using latest version for building(**0.12.0-dev.405+c1e94b28a**)

**Comment by teobler** [comment]
Update: after I upgrade my zig version to 0.12.0-dev.706+62a0fbdae, the error changed - 
```bash
zig build-obj bun-debug Debug native-native.11.0: error: the following command terminated unexpectedly:
/path/.zvm/master/zig build-obj -freference-trace=16 /path/bun/root.zig -lc -fno-strip --cache-dir /path/bun/zig-cache --global-cache-dir /Users/user/.cache/zig --name bun-debug -fno-compiler-rt -fno-stack-check -fno-omit-frame-pointer -target native-native.11.0 -mcpu haswell --mod build_options::/path/bun/zig-cache/c/d9b0919195fca0c105f19b563efd8511/options.zig --mod async_io::/path/bun/src/io/io_darwin.zig --deps async_io,build_options --main-pkg-path /path/bun --listen=-
Build Summary: 1/4 steps succeeded; 1 failed (disable with --summary none)
obj transitive failure
├─ install generated to bun-debug.o transitive failure
│  ├─ zig build-obj bun-debug Debug native-native.11.0 failure
│  └─ zig build-obj bun-debug Debug native-native.11.0 (+1 more reused dependencies)
└─ zig build-obj bun-debug Debug native-native.11.0 (+1 more reused dependencies)
error: the following build command failed with exit code 1:
/path/bun/zig-cache/o/756f6bc7d0ef6f0e4f3e0293e12ae4d2/build /Users/qrzhang/.zvm/master/zig /path/bun /path/bun/zig-cache /Users/user/.cache/zig obj -freference-trace -freference-trace -Dcpu=native
make[3]: *** [dev-obj-track] Error 1
make[2]: *** [zig-no-link] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by Hanaasagi** [comment]
@teobler 
> Is that means I need to fix my zig version to 0.12.0-dev.163+6780a6bbf,   

Yes, you need to install 0.12.0-dev.163+6780a6bbf. Please follow the development guide to setup your zig environment.

- Doc: https://bun.sh/docs/project/development#install-zig

**Comment by teobler** [comment]
Thanks a lot @Hanaasagi, just thinking zig version is not important, so I used latest version.
After using version from doc it works now.
