### ISSUE TITLE
`ENOTSUP` when calling `lchmod`

### ISSUE THREAD

**Issue by riywo** [oven-sh/bun#8980]
### What version of Bun is running?

1.0.27

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

```js
import { createWriteStream, createReadStream, existsSync } from "node:fs";
import { Readable } from "node:stream";
import { finished } from "node:stream/promises";
import { createGunzip } from "node:zlib";
import tar from "tar-fs";

const file = "node-v20.9.0-linux-x64.tar.gz";

const url = `https://nodejs.org/download/release/v20.9.0/${file}`;
const res = await fetch(url);
if (!res.body) throw new Error(res.statusText);
await finished(Readable.fromWeb(res.body).pipe(createWriteStream(file)));

const stream = createReadStream(file);
const extract = tar.extract(".");
await finished(stream.pipe(createGunzip()).pipe(extract));
```

### What is the expected behavior?

The `tar.gz` file is extracted. Node.js doesn't have any issue.

### What do you see instead?

```
$ bun index.mjs                 
ENOTSUP: Operation not supported on transport endpoint
   errno: -95
 syscall: "lchmod"
   path: "node-v20.9.0-linux-x64/bin/corepack"
```

**Comment by nektro** [comment]
this may be linux specific or fixed because this works on arm64 darwin with bun-v1.0.27-12-g6f1939621c

**Comment by argosphil** [comment]
I suspect the code is trying to unpack a tarball in a directory on a file system which doesn't support setting permissions, maybe shared over the network or an older Windows-native file system?

**Comment by paperclover** [comment]
I can reproduce this on native linux. but not on mac. windows does not implement chmod (i think its a no-op)

Adding Linux Tag.
