### PR TITLE
Add Bun.CookieMap.getAll() for cookie names that repeat in a header

### PR DESCRIPTION
**Pull request by robobun**
### Problem
- `new Bun.CookieMap("session=first; session=second")` has `size === 2` and iterates both entries, but `get("session")` only returns `"first"`. Nothing exposes the other value by name. Fixes #41037.

### Fix
- Add `CookieMap.getAll(name): string[]`. It collects the matching values from the same iterator that `entries()` uses. `get()` is unchanged.
- Verified: `test/js/bun/cookie/cookie-map.test.ts` (new `duplicate cookie names` block, fails on stock bun with `getAll is not a function`).

---

**[human-review]** gate passed · iteration 0 · 7 files touched

<details><summary>fails on main (without fix)</summary>

```console
ASAN without fix: 10 failed, 18 skipped
$ BUN_DEBUG_QUIET_LOGS=1 bun scripts/build.ts --profile=debug --quiet test "--reporter=junit" "--reporter-outfile=/tmp/pr_gate.xml" test/js/bun/cookie/cookie-map.test.ts test/js/bun/util/cookie.test.js
bun test v1.4.1 (a6c4cc276)

test/js/bun/cookie/cookie-map.test.ts:
(pass) Bun.Cookie and Bun.CookieMap > can create a basic Cookie [17.43ms]
(pass) Bun.Cookie and Bun.CookieMap > can create a Cookie with options [6.05ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.toString() formats properly [4.81ms]
(pass) Bun.Cookie and Bun.CookieMap > can set Cookie expires as Date [158.02ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.isExpired() returns correct value [4.28ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.isExpired() gives Max-Age precedence over Expires [5.51ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse works with all attributes [4.56ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse keeps Expires when Max-Age comes first [4.67ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse takes the last value of a repeated attribute [3.26ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse reads every attribute in any order [10.52ms]
(pass) Bun.Cookie an
... (truncated)

release without fix: 18 skipped
bun test v1.4.1-canary.1 (bd292f775)

test/js/bun/cookie/cookie-map.test.ts:
(pass) Bun.Cookie and Bun.CookieMap > can create a basic Cookie [0.06ms]
(pass) Bun.Cookie and Bun.CookieMap > can create a Cookie with options [0.05ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.toString() formats properly [0.09ms]
(pass) Bun.Cookie and Bun.CookieMap > can set Cookie expires as Date [5.32ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.isExpired() returns correct value [0.08ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.isExpired() gives Max-Age precedence over Expires [0.06ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse works with all attributes [0.05ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse keeps Expires when Max-Age comes first [0.06ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse takes the last value of a repeated attribute [0.02ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse reads every attribute in any order [0.10ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.serialize creates cookie string [0.03ms]
(pass) Bun.Cookie and Bun.CookieMap > can create an empty CookieMap [0.06ms]
(pass) Bun.Cookie and Bun.CookieMap > can create Cooki
... (truncated)
```

</details>

<details><summary>passes on PR (with fix)</summary>

```console
ASAN with fix: 18 skipped
$ BUN_DEBUG_QUIET_LOGS=1 bun scripts/build.ts --profile=debug --quiet test "--reporter=junit" "--reporter-outfile=/tmp/pr_gate.xml" test/js/bun/cookie/cookie-map.test.ts test/js/bun/util/cookie.test.js
bun test v1.4.1 (a6c4cc276)

test/js/bun/cookie/cookie-map.test.ts:
(pass) Bun.Cookie and Bun.CookieMap > can create a basic Cookie [18.08ms]
(pass) Bun.Cookie and Bun.CookieMap > can create a Cookie with options [5.54ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.toString() formats properly [4.71ms]
(pass) Bun.Cookie and Bun.CookieMap > can set Cookie expires as Date [157.43ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.isExpired() returns correct value [4.26ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.isExpired() gives Max-Age precedence over Expires [5.78ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse works with all attributes [4.71ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse keeps Expires when Max-Age comes first [4.89ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse takes the last value of a repeated attribute [2.26ms]
(pass) Bun.Cookie and Bun.CookieMap > Cookie.parse reads every attribute in any order [10.01ms]
(pass) Bun.Cookie an
... (truncated)

release with fix: 18 skipped
$ bun scripts/build.ts --profile=release
[configured] bun-profile → bun (stripped) in 587ms (unchanged)
ninja: Entering directory `/workspace/bun/build/release'
[1/30] gen generated_host_exports.rs
generated_host_exports.rs: 122 exports (host=5, lazy=10, generic=107, rust=0); 244 extern-C blocks audited
[2/30] gen cpp.rs (cppbind)
[3/30] gen JS modules (bundle-modules)
Preprocess modules (7325ms)
Bundle modules (33ms)
Postprocesss modules (265ms)
Bundle Functions (471ms)
Generate Code (25ms)

[8.13s] Bundled "src/js" for production
  2594 kb
  197 internal modules
  13 native modules
  50 internal functions across 16 files
[3/23] cargo bun_runtime → libbun_runtime.a
[1m[92m   Compiling[0m bun_core v0.0.0 (/workspace/bun/src/bun_core)
[1m[92m   Compiling[0m bun_errno v0.0.0 (/workspace/bun/src/errno)
[1m[92m   Compiling[0m bun_ptr v0.0.0 (/workspace/bun/src/ptr)
[1m[92m   Compiling[0m bun_boringssl_sys v0.0.0 (/workspace/bun/src/boringssl_sys)
[1m[92m   Compiling[0m bun_safety v0.0.0 (/workspace/bun/src/safety)
[1m[92m   Compiling[0m bun_base64 v0.0.0 (/workspace/bun/src/base64)
[1m[92m   Compiling[0m bun_cares_sys v0.0.0 (/workspace/bun/src/
... (truncated)
```

</details>

<details><summary>diff hotspot</summary>

```
docs/runtime/cookies.mdx                 | 12 +++++
 packages/bun-types/bun.d.ts              |  8 ++++
 src/jsc/bindings/CookieMap.cpp           | 12 +++++
 src/jsc/bindings/CookieMap.h             |  1 +
 src/jsc/bindings/webcore/JSCookieMap.cpp | 33 +++++++++++++
 test/js/bun/cookie/cookie-map.test.ts    | 80 ++++++++++++++++++++++++++++++++
 test/js/bun/util/cookie.test.js          |  5 +-
 7 files changed, 147 insertions(+), 4 deletions(-)
```

</details>

**gate history** · 2 passed · 0 rejected · iteration 0

<details><summary>evidence per changed file</summary>

```
file                                      reads  edits  tests
docs/runtime/cookies.mdx                      2      6     12
packages/bun-types/bun.d.ts                   2      4     12
src/jsc/bindings/CookieMap.cpp                4      6     12
src/jsc/bindings/CookieMap.h                  1      2     12
src/jsc/bindings/webcore/JSCookieMap.cpp      1      3     13
test/js/bun/cookie/cookie-map.test.ts         2      2      9
test/js/bun/util/cookie.test.js               4      2      7
```

</details>

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 5:37 PM PT - Aug 31st, 2026</sup></div>

@robobun, your commit aa9e34c16894a4407a5aa95447d288a38aa876ab is building: [`#108947`](https://buildkite.com/bun/bun/builds/108947)

File: src/jsc/bindings/CookieMap.cpp [hunk 1]
```diff
@@ -147,6 +147,21 @@ std::optional<String> CookieMap::get(const String& name) const
     return std::nullopt;
 }
 
+// A Cookie header may repeat a name (RFC 6265 section 5.4), so several
+// entries can match. The result is the subset of entries that iteration
+// yields, in the same order.
```
[the remark this answers is not in the document]
Comment (robobun) [reply src/jsc/bindings/CookieMap.cpp]: Trimmed to one line in bd292f7756. The comment is not a workaround note, it only says why more than one entry can match: RFC 6265 allows a Cookie header to repeat a name.

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
delete almost all the words you added. slop.

**Comment by robobun** [comment]
Done in 60b2732. The docs entry is one sentence and a four-line example, the JSDoc is one line plus param and return, the C++ comment is gone, and the PR description is cut down too.

File: docs/runtime/cookies.mdx [hunk 2]
```diff
@@ -77,6 +77,17 @@ if (cookie != null) {
 }
 ```
 
+#### `getAll(name: string): string[]`
+
+Retrieves every value for a cookie name. A `Cookie` header can repeat a name, and `get()` returns only the first value.
```
[the remark this answers is not in the document]
Comment (robobun) [reply docs/runtime/cookies.mdx:82]: Not applying this. That guidance was in the docs and JSDoc in an earlier revision, and the maintainer asked for it to be removed (see the comment above). The docs now state the behavior: the header can repeat a name, get() returns the first value, getAll() returns all of them.
