### ISSUE TITLE
`AbortSignal.timeout`  not working with typescript

### ISSUE THREAD

**Issue by bjon** [oven-sh/bun#18529]
### What version of Bun is running?

1.2.7+5c0fa6dc2

### What platform is your computer?

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. Create a new project with `bun init`
2. Add `AbortSignal.timeout(1);` to index.ts
3. Run `bunx tsc`

### What is the expected behavior?

Should compile with `tsc`

### What do you see instead?

error TS2339: Property 'timeout' does not exist on type '{ new (): AbortSignal; prototype: AbortSignal; }

### Additional information

Using `@types/bun@1.2.7`

**Comment by bjon** [comment]
This worked in 1.2.6

**Comment by alii** [comment]
Thanks for reporting, missed this one in the recent typescript updates. Will fix asap.

For now, can you include the DOM types by setting `lib: ["ESNext", "DOM"]` in your compiler options?

AbortSignal is defined in the DOM types and should fix this as a workaround

**Comment by alii** [comment]
This was fixed and will be released in the next version of Bun 🎉
