### ISSUE TITLE
ESLint find-up resolution regression in Bun 1.3.4

### ISSUE THREAD

**Issue by MortalityWatch** [oven-sh/bun#25522]
# ESLint find-up resolution regression in Bun 1.3.4

## What version of Bun is running?

1.3.4

## What platform is your computer?

Linux (Ubuntu latest in GitHub Actions) and macOS Darwin 25.1.0

## What steps can reproduce the bug?

1. Create a project with both `eslint@^9.39.2` and `@nuxt/eslint@^1.12.1` as dependencies
2. Run `bun install`
3. Run `bunx eslint .`

Minimal reproduction:

```json
{
  "devDependencies": {
    "@nuxt/eslint": "^1.12.1",
    "eslint": "^9.39.2"
  }
}
```

## What is the expected behavior?

ESLint should run successfully. This works correctly in Bun 1.3.2.

## What do you see instead?

```
TypeError: findUp is not a function
    at ConfigLoader.locateConfigFileToUse (node_modules/eslint/lib/config/config-loader.js:542:27)
    at #locateConfigFileToUse (node_modules/eslint/lib/config/config-loader.js:714:40)
    at LegacyConfigLoader.findConfigFileForPath (node_modules/eslint/lib/config/config-loader.js:760:63)
    at LegacyConfigLoader.loadConfigArrayForFile (node_modules/eslint/lib/config/config-loader.js:412:37)
    at entryFilter (node_modules/eslint/lib/eslint/eslint-helpers.js:322:24)
```

## Additional context

The issue is ESM/CJS module resolution. The dependency tree has two versions of `find-up`:

- `eslint@9.39.2` depends on `find-up@^5.0.0` (CommonJS compatible)
- `@nuxt/eslint@1.12.1` depends on `find-up@^8.0.0` (ESM only)

In Bun 1.3.2, eslint correctly receives `find-up@5` which exports `findUp` as a function.

In Bun 1.3.4, eslint incorrectly receives `find-up@8` which is ESM-only and the import doesn't resolve correctly, causing `findUp` to be undefined.

**Workaround**: Pin Bun to 1.3.2 until this is fixed.
