### ISSUE TITLE
`react-dom/server` import issue

### ISSUE THREAD

**Issue by ahmafi** [oven-sh/bun#24184]
### What version of Bun is running?

1.3.0

### What platform is your computer?

Linux 6.17.4-200.fc42.x86_64 x86_64 unknown

### What steps can reproduce the bug?

I have not tested this with on a new project yet, but since I'm experiencing this issue only with bun and not node, I think this will probably happen in new projects too.

I have Next.js (v15.3.0) project that uses `renderToStaticMarkup` from `react-dom/server` inside a `getStaticProps`. Run a standalone build, then run the project with `bun server.js`.

### What is the expected behavior?

It should work without errors as it works in Node (v22.19.0).

### What do you see instead?

```
error: Cannot find module 'react-dom/server' from '/my-project/.next/standalone/.next/server/pages/_app.js'
 ⨯ unhandledRejection:  error: Cannot find module 'react-dom/server' from '/my-project/.next/standalone/.next/server/pages/_app.js'
```
