### ISSUE TITLE
`tsc` `Cannot find name 'window'` with `bun-types` installed

### ISSUE THREAD

**Issue by spiffytech** [oven-sh/bun#3030]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Linux 6.2.15-300.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

1. `bun init`
2. Add `DOM` to the `lib` section of `tsconfig.json`
3. Edit `index.ts` to read `console.log(window)`
4. `bunx tsc --noEmit`

### What is the expected behavior?

Code compiles correctly

### What do you see instead?

`tsc` emits `TS2304: Cannot find name 'window'`

### Additional information

I'm trying to port an existing Node project to Bun. The project has Playwright code that references `window`.

My project also puts client and server code under the same npm project. Although they are compiled separately, the presence of `bun-types` in my `node_modules` folder breaks any references to DOM types in my client-side code.

**Comment by amirrezamahyari** [comment]
same issue, i use bun workspaces, importing any shared package that includes bun-types into my nextjs app will breaks DOM types.

relates https://github.com/oven-sh/bun/issues/463

**Comment by znycheporuk** [comment]
This helped me https://github.com/oven-sh/bun/issues/463#issuecomment-1179687748

**Comment by JessicaSachs** [comment]
### Current Workaround
I think this is a duplicate of #463

In particular this [comment](https://github.com/oven-sh/bun/issues/463#issuecomment-1636727109) that mentions including [@types/web](https://www.npmjs.com/package/@types/web) inside of `compilerOptions.types` which overwrite `lib` from #463 was the workaround which worked for me

### Install @types/web

```sh
bun init
bun add @types/web -D
# modify tsconfig.json to include "types"
# Celebrate
```

### Happy tsconfig.json
Here's my web-friendly `tsconfig.json` for a bare-bones project created with `bun init`

```json5
{
  "compilerOptions": {
    "lib": ["esnext", "dom"], // Add "dom" here, too, like you usually would
    "module": "esnext",
    "target": "esnext",
    "moduleResolution": "bundler",
    "moduleDetection": "force",
    "allowImportingTsExtensions": true,
    "noEmit": true,
    "composite": true,
    "strict": true,
    "downlevelIteration": true,
    "skipLibCheck": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "types": [
      "bun-types", // add Bun global
      "web"
    ]
  }
}
```

**Comment by Reljod** [comment]
> ### Current Workaround
> I think this is a duplicate of #463
> 
> In particular this [comment](https://github.com/oven-sh/bun/issues/463#issuecomment-1636727109) that mentions including [@types/web](https://www.npmjs.com/package/@types/web) inside of `compilerOptions.types` which overwrite `lib` from #463 was the workaround which worked for me
> 
> ### Install @types/web
> ```shell
> bun init
> bun add @types/web -D
> # modify tsconfig.json to include "types"
> # Celebrate
> ```
> 
> ### Happy tsconfig.json
> Here's my web-friendly `tsconfig.json` for a bare-bones project created with `bun init`
> 
> ```js
> {
>   "compilerOptions": {
>     "lib": ["esnext", "dom"], // Add "dom" here, too, like you usually would
>     "module": "esnext",
>     "target": "esnext",
>     "moduleResolution": "bundler",
>     "moduleDetection": "force",
>     "allowImportingTsExtensions": true,
>     "noEmit": true,
>     "composite": true,
>     "strict": true,
>     "downlevelIteration": true,
>     "skipLibCheck": true,
>     "jsx": "preserve",
>     "allowSyntheticDefaultImports": true,
>     "forceConsistentCasingInFileNames": true,
>     "allowJs": true,
>     "types": [
>       "bun-types", // add Bun global
>       "web"
>     ]
>   }
> }
> ```

Tried this and it now works. Thanks!

**Comment by Electroid** [comment]
We fixed this with a new package, [`@types/bun`](https://www.npmjs.com/package/@types/bun).

**Comment by asleepace** [comment]
Was able to solve this by using

```
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />

const window: Window = globalThis
```
