### ISSUE TITLE
RTL-extended DOM matchers missing/fail tests on Bun v1.1.43, work on Bun v1.1.42

### ISSUE THREAD

**Issue by coopbri** [oven-sh/bun#16434]
### What version of Bun is running?

1.1.43+76800b049

### What platform is your computer?

Linux 6.12.9-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

On Bun v1.1.43:
1. Extend the React Testing Library DOM matchers as outlined in https://bun.sh/guides/test/testing-library (specifically the section involving `@testing-library/jest-dom/matchers`)
2. Create a test that uses an extended matcher (e.g. `toHaveClass` as in `expect(...).toHaveClass(...)`)
3. Run test, get output similar to `TypeError: expect(document.documentElement).toHaveClass is not a function. (In 'expect(document.documentElement).toHaveClass("dark")', 'expect(document.documentElement).toHaveClass' is undefined)`

Test above on Bun v1.1.42 and make sure tests pass

### What is the expected behavior?

Tests pass (extended DOM matchers recognized)

### What do you see instead?

Tests fail (extended DOM matchers not recognized)

### Additional information

**Screenshots:**

The below use [proto](https://github.com/moonrepo/proto).

Executed with `proto run bun 1.1.42 -- test`:

![Image](https://github.com/user-attachments/assets/c7610709-d590-4b05-b6bc-d859447a009b)

Executed with `proto run bun 1.1.43 -- test`:

![Image](https://github.com/user-attachments/assets/411754d1-c144-4fbc-8a13-35de10844b14)
![Image](https://github.com/user-attachments/assets/3f5a64d0-7bf3-4614-99a0-4285f1f2aa93)

**Comment by coopbri** [comment]
Holy shit, that was lightning fast, no keeping up with @Jarred-Sumner. Cheers man
