### PR TITLE
bun_runtime: restore the bun_css dependency edge

### PR DESCRIPTION
**Pull request by robobun**
### Problem

- `bun bd` fails on main: `error[E0433]: cannot find module or crate bun_css` in `src/runtime/cli/pm_diff_normalize.rs:747` while compiling `bun_runtime`.
- #37301 (a1da88c23d) removed `bun_css.workspace = true` from `src/runtime/Cargo.toml` as an unused edge. That was verified before #39229 (`bun pm diff`) merged. #39229 added calls to `bun_css::StyleSheet::parse` and `bun_css::PrinterOptions` in `pm_diff_normalize.rs:747-764`. The two PRs merged in an order that left a live reference without the dependency edge.

### Fix

- Restore `bun_css.workspace = true` in `src/runtime/Cargo.toml`, plus the matching one-line `Cargo.lock` entry.
- Add `test/internal/source-lints/cargo-dep-edges.test.ts`. It checks that every `bun_*::` path a crate's code names has a dependency edge in that crate's Cargo.toml. It catches this failure class on the PR that merges second, before main breaks.
- Verified: the lint fails on main without the manifest change (it reports the `bun_css` edge) and passes with it. `cargo check -p bun_runtime` and a full `bun bd` also pass with the change and fail without it.

### Background

cargo already enforces dependency edges at compile time, but only for the code each PR rebuilds. A dead-code sweep can verify an edge is unused, then merge after another PR adds new uses of it. Both PRs are green on their own CI and the combination breaks main. The lint re-checks the pairing textually on every tree. It is conservative: it counts only workspace crate names used as `name::` paths in code, after comments and string literals are stripped, and it understands `extern crate x as y` renames, local modules that shadow a crate name, and files mounted into another crate with `#[path]`.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 3:12 PM PT - Aug 18th, 2026</sup></div>

@robobun, your commit 23e98de15cd83419043b88165c1299b24217d5e6 is building: [`#100770`](https://buildkite.com/bun/bun/builds/100770)
