### ISSUE TITLE
Regression: Recharts charts fail to render in Bun 1.3.10 (works in 1.3.9)

### ISSUE THREAD

**Issue by lucaslevin** [oven-sh/bun#27853]
### What version of Bun is running?

1.3.10+30e609e08

### What platform is your computer?

Darwin 25.3.0 arm64 arm

### What steps can reproduce the bug?

1. Create a React project that uses Recharts.

2. Install dependencies:

   ```
   bun install
   ```

3. Run the dev server with Bun 1.3.10:

   ```
   bun dev
   ```

4. Open the application in the browser.

5. Render a simple Recharts chart (e.g. `LineChart`).

The chart fails to render and the following error appears in the console:

```
TypeError: d3Scales[name] is not a function
    at getD3ScaleFromType (node_modules/recharts/es6/util/scale/RechartsScale.js)
```

Downgrading Bun to **1.3.9** fixes the issue and the charts render correctly.

### What is the expected behavior?

Charts should render correctly when using Recharts with Bun, without any runtime errors.

The same project works as expected when running with **Bun 1.3.9**, where the charts render normally.

### What do you see instead?

Charts do not render and a runtime error appears in the browser console:

```
TypeError: d3Scales[name] is not a function
    at getD3ScaleFromType (node_modules/recharts/es6/util/scale/RechartsScale.js)
```

This happens when running the project with **Bun 1.3.10**. Downgrading to **Bun 1.3.9** resolves the issue and the charts render correctly.

### Additional information

The error occurs inside Recharts when resolving D3 scale functions dynamically.

Recharts imports scales using:

```js
import * as d3Scales from "victory-vendor/d3-scale";
```

and then calls them dynamically:

```js
d3Scales[name]()
```

With **Bun 1.3.10**, the namespace import appears to be transformed so the exported values are no longer directly callable functions, which results in the runtime error.

The same code works correctly with **Bun 1.3.9**, suggesting this may be a regression in Bun’s bundler or ESM namespace handling.
```
