### ISSUE TITLE
Package manager doesn't install all files (Example libxmljs)

### ISSUE THREAD

**Issue by niklasravnsborg** [oven-sh/bun#4726]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```sh
bun init
```

```sh
bun add -d libxmljs
```

```sh
echo 'import { parseXml } from "libxmljs";
console.log(parseXml("<foo>hello</foo>").toString());' > index.ts
```

```sh
bun index.ts
```

### What is the expected behavior?

Should print:

```
<?xml version="1.0" encoding="UTF-8"?>
<foo>hello</foo>
```

### What do you see instead?

```sh
91 |         throw e
92 |       }
93 |     }
94 |   }
95 | 
96 |   err = new Error('Could not locate the bindings file. Tried:\n'
            ^
error: Could not locate the bindings file. Tried:
 → /Users/nik/Code/buntest/node_modules/libxmljs/build/xmljs.node
 → /Users/nik/Code/buntest/node_modules/libxmljs/build/Debug/xmljs.node
 → /Users/nik/Code/buntest/node_modules/libxmljs/build/Release/xmljs.node
 → /Users/nik/Code/buntest/node_modules/libxmljs/out/Debug/xmljs.node
 → /Users/nik/Code/buntest/node_modules/libxmljs/Debug/xmljs.node
 → /Users/nik/Code/buntest/node_modules/libxmljs/out/Release/xmljs.node
 → /Users/nik/Code/buntest/node_modules/libxmljs/Release/xmljs.node
 → /Users/nik/Code/buntest/node_modules/libxmljs/build/default/xmljs.node
 → /Users/nik/Code/buntest/node_modules/libxmljs/compiled/18.15.0/darwin/arm64/xmljs.node
      at bindings (/Users/nik/Code/buntest/node_modules/bindings/bindings.js:96:8)
      at /Users/nik/Code/buntest/node_modules/libxmljs/dist/lib/bindings/index.js:5:15
      at globalThis (/Users/nik/Code/buntest/node_modules/libxmljs/dist/lib/bindings/index.js:47:18)
      at require (:1:20)
      at /Users/nik/Code/buntest/node_modules/libxmljs/dist/lib/node.js:19:4
      at globalThis (/Users/nik/Code/buntest/node_modules/libxmljs/dist/lib/node.js:560:18)
      at require (:1:20)
      at /Users/nik/Code/buntest/node_modules/libxmljs/dist/lib/document.js:66:4
      at globalThis (/Users/nik/Code/buntest/node_modules/libxmljs/dist/lib/document.js:393:23)
      at require (:1:20)
      at /Users/nik/Code/buntest/node_modules/libxmljs/dist/lib/index.js:18:4
      at globalThis (/Users/nik/Code/buntest/node_modules/libxmljs/dist/lib/index.js:28:42)
      at require (:1:20)
      at /Users/nik/Code/buntest/node_modules/libxmljs/dist/index.js:28:0
      at globalThis (/Users/nik/Code/buntest/node_modules/libxmljs/dist/index.js:30:36)
```

### Additional information

It seems like the bun package manager doesn't install the `node_modules/libxmljs/build/Release/xmljs.node` file in comparison to normal npm.

In libxmljs the missing files are [described in the package.json](https://github.com/libxmljs/libxmljs/blob/650733271b7ed60b473a76b19791075d55e6e77b/package.json#L3-L9), and it uses [@mapbox/node-pre-gyp](https://github.com/mapbox/node-pre-gyp). I think the problem is related to the missing `node-gyp` feature described in #101.

When I try to manually install the binary using `cd node_modules/libxmljs/ && npm run install` I get the following error when running `bun index.ts`:

```sh
dyld[12997]: missing symbol called
zsh: killed     bun index.ts
```

**Comment by mindplay-dk** [comment]
Sounds like what I'm running into, so I don't want to open another issue - but I can add another example:

* `bun init`
* `bun install sharp`
* put a JPEG file named `image.jpg` in the folder.

Now edit the `index.ts` file and add something like:

```ts
import sharp from "sharp";

(async () => {
  const image = await sharp("image.jpg").metadata();

  console.log(image);
})()
```

Then `bun run index.ts`.

I get the following error output:

```
$ bun run index.ts
32 |     if (loadedModule) {
33 |       const [, loadedPackage] = loadedModule.match(/node_modules[\\/]([^\\/]+)[\\/]/);
34 |       help.push(`- Ensure the version of sharp aligns with the ${loadedPackage} package: "npm ls sharp"`);
35 |     }
36 |   }
37 |   throw new Error(help.join('\n'));
            ^
error: 
Something went wrong installing the "sharp" module

Cannot find module "../build/Release/sharp-linux-x64.node" from "/home/mindplay/workspace/try-bun/node_modules/sharp/lib/sharp.js"

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
      at /home/mindplay/workspace/try-bun/node_modules/sharp/lib/sharp.js:37:8
      at globalThis (/home/mindplay/workspace/try-bun/node_modules/sharp/lib/sharp.js:37:33)
      at require (:1:20)
      at /home/mindplay/workspace/try-bun/node_modules/sharp/lib/constructor.js:11:0
      at globalThis (/home/mindplay/workspace/try-bun/node_modules/sharp/lib/constructor.js:439:17)
      at require (:1:20)
      at /home/mindplay/workspace/try-bun/node_modules/sharp/lib/index.js:6:6
      at globalThis (/home/mindplay/workspace/try-bun/node_modules/sharp/lib/index.js:16:17)
```

**Comment by marmotz** [comment]
And an other example (with Bun 1.0.0):

* `bun init`
* `bun install pulsar-client`
* `index.ts` with :
```typescript
import { Client } from 'pulsar-client';

let client = new Client();
```
* we get the following error:
```
error: Cannot find module "<path>/node_modules/pulsar-client/lib/binding/pulsar.node" from "<path>/node_modules/pulsar-client/src/pulsar-binding.js"
```

**Comment by Jarred-Sumner** [comment]
This is caused by not running postinstall scripts. This will be addressed for the vast majority of cases by #4263 . Please see this issue to track the status: https://github.com/oven-sh/bun/issues/4959

**Comment by niklasravnsborg** [comment]
@Jarred-Sumner After upgrading to 1.0.18 and adding `libxmljs` to my `trustedDependencies`, I'm having trouble running the postinstall script. 

The problem is reproducible using the following steps:

1. Create a new bun project
2. Add the following to package.json
```json
{
  "name": "foo",
  "module": "index.ts",
  "type": "module",
  "dependencies": {
    "libxmljs": "latest"
  },
  "devDependencies": {
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "trustedDependencies": [
    "libxmljs"
  ]
}
```
3. Run `bun install`

I get the following error: 

```sh
❯ bun install
bun install v1.0.18 (36c316a2)
  ⚙️  libxmljs [2/2] Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)

(node:73836) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v1.0.11/node-v120-darwin-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/libxmljs/libxmljs/releases/download/v1.0.11/node-v120-darwin-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for libxmljs@1.0.11 and node@21.4.0 (node-v120 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/libxmljs/libxmljs/releases/download/v1.0.11/node-v120-darwin-arm64.tar.gz 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/myuser/foo/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:83:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
node-pre-gyp ERR! stack     at onErrorNT (node:internal/child_process:484:16)
node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
node-pre-gyp ERR! System Darwin 23.2.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/21.4.0/bin/node" "/Users/myuser/foo/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http" "-j" "max"
node-pre-gyp ERR! cwd /Users/myuser/foo/node_modules/libxmljs
node-pre-gyp ERR! node -v v21.4.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok 

error: install script from "libxmljs" exited with code 1 (SIGHUP)
```

With npm the installation works just fine (Although it takes much more time).

**Comment by n0isy** [comment]
Why this is closed? Can I use libxmljs2 or sharp npm packages? (nodegyp)
