### PR TITLE
fix dev server regressions from 1.2.5's hmr rewrite

### LINKED ISSUE #17613: Bun 1.2.3 - Failed to load bundled module
### What version of Bun is running?

1.2.3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

-

### What is the expected behavior?

Bun can run, without any issues
```ts
Bun.serve({
  routes: {...},
  development: true
});
```

### What do you see instead?

Previously, Bun `1.2.2` serve use `static` API works
```ts
Bun.serve({
  static: {...},
  development: true
});
```

When migrating to Bun `1.2.3` serve use `routes` API show this error

Image

### Additional information

Using Bun 1.2.3 and React 19 with `lazy` components

### LINKED ISSUE #17988: Maximum call size exceeded
### What version of Bun is running?

canary

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Unfortunately I can't give a precise repro since I'm running bun on my work repo.

I'm using the frontend bundler. I run bun like so: `bun index.html`

### What is the expected behavior?

It works

### What do you see instead?

A stack trace

```
frontend RangeError: Maximum call stack size exceeded
      at Object._inheritsLoose4 (http://localhost:3000/_bun/client/index-000000000eae7068.js:3332:28)
      at Object._setPrototypeOf2 [as default] (http://localhost:3000/_bun/client/index-000000000eae7068.js:5:2938)
      at Object._inheritsLoose4 (http://localhost:3000/_bun/client/index-000000000eae7068.js:3332:107)
      at Object._setPrototypeOf2 [as default] (http://localhost:3000/_bun/client/index-000000000eae7068.js:5:2938)
      at Object._inheritsLoose4 (http://localhost:3000/_bun/client/index-000000000eae7068.js:3332:107)
      at Object._setPrototypeOf2 [as default] (http://localhost:3000/_bun/client/index-000000000eae7068.js:5:2938)
      at Object._inheritsLoose4 (http://localhost:3000/_bun/client/index-000000000eae7068.js:3332:107)
      at Object._setPrototypeOf2 [as default] (http://localhost:3000/_bun/client/index-000000000eae7068.js:5:2938)
      at Object._inheritsLoose4 (http://localhost:3000/_bun/client/index-000000000eae7068.js:3332:107)
    from browser tab http://localhost:3000/overview
```

### Additional information

_No response_

### LINKED ISSUE #18007: Bun html dev server `Module "..." does not export key "..."` (importing swr)
### What version of Bun is running?

1.2.5-canary.109+589fa6274

### What platform is your computer?

windows

### What steps can reproduce the bug?

1. make `index.js` and `index.html`
2. install `swr`
3. run dev mode - `bun index.html`
4. open in browser

```js
// index.js
import "swr"; 
```
```html
<!-- index.html -->
<script type="module" src="index.js"></script>
```

### What is the expected behavior?

work and be able to use SWR: https://swr.vercel.app/docs/getting-started#quick-start

### What do you see instead?

```ts
Runtime Error
SyntaxError: Module "./node_modules/swr/dist/_internal/config-context-client-Cm1JTDEP.mjs" does not export key "IS_REACT_LEGACY"
```

### Additional information

There was an earlier issue with SWR when it was doing `export * from './types.mjs';` and nothing in the file (not sure if it is still bug)

Caused by #17954, and only an issue with dev server (`bun build` works)

### LINKED ISSUE #18059: Recharts dependency error on element.setAttribute
### What version of Bun is running?

1.2.5

### What platform is your computer?

Darwin 24.3.0 x86_64 i386

### What steps can reproduce the bug?

1. Init new project with bun init > react > shadcn + tailwindcss
2. bunx shadcn@canary add chart
3. Include a chart into App.tsx

### What is the expected behavior?

See a chart rendered.

### What do you see instead?

TypeError: element.setAttribute is not a function

### Additional information

On 1.2.3 and 1.2.4 it works correctly

### LINKED ISSUE #18110: Bun 1.2.5 broke radix-ui components
### What version of Bun is running?

1.2.5+013fdddc6

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

1. bun init
2. select react + shadcn + tailwind
3. add on page
```jsx
<Avatar>
      <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
      <AvatarFallback>CN</AvatarFallback>
</Avatar>
```
4. bun dev
5. Got TypeError: handleLoadingStatusChange is not a function

### What is the expected behavior?

Render component

### What do you see instead?

TypeError: handleLoadingStatusChange is not a function

### Additional information

Its work on Bun 1.2.4

### LINKED ISSUE #18182: With bun 1.2.5, `bun init` with `React /  Shadcn + TailwindCSS` template crashes in dev server
### What version of Bun is running?

1.2.5

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

Create a new project with bun using React/Shadcn+TailwindCSS template (which installs among other things @radix-ui/react-select)

```bash
$ bun init test-app

✓ Select a project template: React
✓ Select a React template: Shadcn + TailwindCSS
:
$ cd test-app
$ bun dev
$ bun --hot src/index.tsx
🚀 Server running at http://localhost:3000/
Bundled page in 228ms: src/index.html
```

Then access the page from a browser and click the select box inside the ApiTester component causing Runtime error

Image
Image

* Actual error is attached to the `What do you see instead` section

Note that if you `bun run build` and `bun start` does not reproduce this error.
Also note that 1.2.4 does not reproduce for `bun dev`

```bash
docker run -v .:/home/bun/app -p 3000:3000 oven/bun:1.2.4 run dev
```

### What is the expected behavior?

Same as 1.2.4, hot reloading does not break default template of `bun init`

### What do you see instead?

Run time error

Bundled page in 222ms: src/index.html
frontend TypeError: handleChange is not a function
      at /Users/shunt/Workspace/temp/test/node_modules/@radix-ui/react-use-controllable-state/dist/index.mjs:38:7
      at react-stack-bottom-frame (/Users/shunt/Workspace/temp/test/node_modules/react-dom/cjs/react-dom-client.development.js:22509:20)
      at runWithFiberInDEV (/Users/shunt/Workspace/temp/test/node_modules/react-dom/cjs/react-dom-client.development.js:543:16)
      at commitHookEffectListMount (/Users/shunt/Workspace/temp/test/node_modules/react-dom/cjs/react-dom-client.development.js:10758:29)
      at commitHookPassiveMountEffects (/Users/shunt/Workspace/temp/test/node_modules/react-dom/cjs/react-dom-client.development.js:10878:11)
      at commitPassiveMountOnFiber (/Users/shunt/Workspace/temp/test/node_modules/react-dom/cjs/react-dom-client.development.js:12653:13)
      at recursivelyTraversePassiveMountEffects (/Users/shunt/Workspace/temp/test/node_modules/react-dom/cjs/react-dom-client.development.js:12627:11)
      at commitPassiveMountOnFiber (/Users/shunt/Workspace/temp/test/node_modules/react-dom/cjs/react-dom-client.development.js:12646:11)
      at recursivelyTraversePassiveMountEffects (/Users/shunt/Workspace/temp/test/node_modules/react-dom/cjs/react-dom-client.development.js:12627:11)
      at commitPassiveMountOnFiber (/Users/shunt/Workspace/temp/test/node_modules/react-dom/cjs/react-dom-client.development.js:12755:11)
    from browser tab http://localhost:3000/

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
I apologize for letting that PR merge without enough testing.
This PR does not increase the size of `js_ast.Symbol`.

Fixes #17988.
Fixes #17613
Fixes #18110
Fixes #18182
Closes #18007 because i only disable this error since it is inaccurate. legitimate places this was thrown will degrade to "undefined is not a function" or whatever 1.2.4 did.
Fixes #18059

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 9:22 PM PT - Mar 11th, 2025</sup></div>

@paperclover, your commit d94a43a9e83188dfdb91bad6d9aae8438fa3e3bb is building: [`#13098`](https://buildkite.com/bun/bun/builds/13098)

File: src/bake/DevServer.zig [hunk 1]
```diff
@@ -166,6 +171,9 @@ deferred_request_pool: bun.HiveArray(DeferredRequest.Node, DeferredRequest.max_p
 /// UWS can handle closing the websocket connections themselves
 active_websocket_connections: std.AutoHashMapUnmanaged(*HmrSocket, void),
 
+relative_path_buf_lock: bun.DebugThreadLock,
+relative_path_buf: bun.PathBuffer,
```
Comment (dylan-conway) [inline src/bake/DevServer.zig:175]: maybe make this `*bun.PathBuffer` and get this from `bun.PathBufferPool` instead?

File: src/bake/bake.private.d.ts [hunk 2]
```diff
@@ -40,6 +48,7 @@ declare type EncodedDependencyArray = (string | number)[];
 declare type UnloadedCommonJS = (
   hmr: import("./hmr-module").HMRModule,
   module: import("./hmr-module").HMRModule["cjs"],
+  exports: any,
```
Comment (DonIsaac) [inline src/bake/bake.private.d.ts]: consider `unknown`

File: src/bake/DevServer.zig [hunk 3]
```diff
@@ -6550,15 +6672,20 @@ fn relativePath(dev: *const DevServer, path: []const u8) []const u8 {
     {
         return path[dev.root.len + 1 ..];
     }
-    const relative_path_buf = &struct {
-        threadlocal var buf: bun.PathBuffer = undefined;
-    }.buf;
-    const rel = bun.path.relativePlatformBuf(relative_path_buf, dev.root, path, .auto, true);
+
+    const rel = bun.path.relativePlatformBuf(&dev.relative_path_buf, dev.root, path, .auto, true);
     // @constCast: `rel` is owned by a mutable threadlocal buffer above
```
Comment (dylan-conway) [inline src/bake/DevServer.zig]: comment out-of-date

File: src/bake/hmr-module.ts [hunk 4]
```diff
@@ -940,3 +897,13 @@ if (side === "client") {
     onServerSideReload: cb => (onServerSideReload = cb),
   });
 }
+
+// The following API may be altered at any point.
+// Thankfully, you can just call `import.meta.hot.on`
+let testingHook = globalThis['bun do not use this outside of internal testing or else i\'ll cry'];
+testingHook && testingHook({
```
Comment (DonIsaac) [inline src/bake/hmr-module.ts]:
```suggestion
testingHook?.({
```

File: src/js_ast.zig [hunk 5]
```diff
@@ -1103,15 +1103,13 @@ pub const Symbol = struct {
...
-    /// the symbol table.
-    debug_mode_source_index: if (Environment.allow_assert)
-        Index.Int
-    else
-        u0 = 0,
+    /// Used in HMR to decide when live binding code is needed.
+    has_been_assigned_to: bool = false,
+
+    comptime {
+        bun.assert_eql(@sizeOf(Symbol), 88);
```
Comment (DonIsaac) [inline src/js_ast.zig:1110]: non-blocking: could we make `Symbol` smaller by putting `bool` fields into a packed struct?

File: test/bake/bake-harness.ts [hunk 6]
```diff
@@ -1509,11 +1645,6 @@ function testImpl<T extends DevServerTest>(
         : "PROD"
   }:${basename}-${count}: ${description}`;
   try {
-    // TODO: resolve ci flakiness.
-    if (isCI && isWindows) {
```
Comment (DonIsaac) [inline test/bake/bake-harness.ts:1513]: 🎊

File: src/js_ast.zig (hunk 5 above)
Comment (paperclover) [reply src/js_ast.zig:1110]: yes. i bet this struct could be 48 or so without all the bloat in it

File: src/bake/bake.private.d.ts (hunk 2 above)
Comment (paperclover) [reply src/bake/bake.private.d.ts]: i did but unknown in general for these codebases just leads to using `as any` which doesn't actually help anyone out.

File: src/bake/DevServer.zig (hunk 1 above)
Comment (paperclover) [reply src/bake/DevServer.zig:175]: no. i am intentionally pre-allocating it with the already large `DevServer` object (already above 20kb)

File: src/bake/hmr-module.ts (hunk 4 above)
Comment (paperclover) [reply src/bake/hmr-module.ts]: today i learned this wont eval the args if the fn is undefined. cozy

File: src/bake/bake.private.d.ts (hunk 2 above)
Comment (paperclover) [reply src/bake/bake.private.d.ts]: though, in this case i can do that since i never define this function, only calling it

File: src/bake/DevServer.zig [hunk 7]
```diff
@@ -7413,6 +7542,26 @@ fn readString32(reader: anytype, alloc: Allocator) ![]const u8 {
...
 }
 
+const TestingBatch = struct {
+    entry_points: EntryPointList,
+    timer: std.time.Timer,
+
+    const empty: @This() = .{
+        .entry_points = .empty,
+        .timer = undefined,
+    };
```
Comment (dylan-conway) [inline src/bake/DevServer.zig]: Why is this needed? Seems like `undefined` should not be used here. Instead a time should be provided when initialized

Comment (paperclover) [reply src/bake/DevServer.zig]: when there are no entry points, there isn't a sensible time to start this at. this is why all uses assert or handle .empty. i'll add this in a comment.

File: src/js_parser.zig [hunk 8]
```diff
@@ -17318,7 +17319,7 @@ fn NewParser_(
                             p.method_call_must_be_replaced_with_undefined = false;
                             switch (e_.target.data) {
                                 // If we're removing this call, don't count any arguments as symbol uses
-                                .e_index, .e_dot => {
+                                .e_index, .e_dot, .e_identifier => {
```
Comment (Jarred-Sumner) [inline src/js_parser.zig:17322]: do we need e_import_identiifer and like 5 other ones
