### ISSUE TITLE
Bun doesn't install dependencies on Windows.

### ISSUE THREAD

**Issue by Sotorev** [oven-sh/bun#14391]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

I was working on an API with bun 1.26, then I updated bun and the project does'nt work anymore. It always shows an error message saying Cannot find module... even I install those dependencies. Some of the folders in node_modules are empty too when I try to install dependencies.

**Comment by Electroid** [comment]
Can you share your package.json and what command you're running?

**Comment by Sotorev** [comment]
{
  "name": "api",
  "module": "index.ts",
  "type": "module",
  "scripts": {
    "dev": "bun --watch run ./src/app.ts",
    "start": "bun ./src/app.ts"
  },
  "devDependencies": {
    "@types/bcryptjs": "^2.4.4",
    "@types/cors": "^2.8.17",
    "@types/express": "^4.17.17",
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "cors": "^2.8.5",
    "express": "^4.21.0",
    "jose": "^4.14.6",
    "mongodb": "^5.4.0",
    "zod": "^3.22.2"
  }
}

I tried the same package.json on Ubuntu and it works perfectly, it's just my Bun's Windows version.

**Comment by Sotorev** [comment]
![Image](https://github.com/user-attachments/assets/e6bd2ead-59c0-4dd0-b6a5-8557197237d0)

On windows
![Image](https://github.com/user-attachments/assets/dde08ad8-387b-43de-8d3a-1ceabef0adc8)

I'm also watching that Windows version of bun, for some reason does'nt install anything inside some  dependencies' folders. For example express.

**Comment by sancho1952007** [comment]
I face this issue too. As a result, I have to use npm every time I need to install some dependency.

**Comment by Sotorev** [comment]
> I face this issue too. As a result, I have to use npm every time I need to install some dependency.

Did you find a solution? I'm trying to install dependencies using the v1.1.43, but I still get the same error. I need to use WSL if I want to work with bun on windows.
