### ISSUE TITLE
Bun 1.2.5 broke radix-ui components

### ISSUE THREAD

**Issue by i-mark** [oven-sh/bun#18110]
### What version of Bun is running?

1.2.5+013fdddc6

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

1. bun init
2. select react + shadcn + tailwind
3. add on page
```jsx
<Avatar>
      <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
      <AvatarFallback>CN</AvatarFallback>
</Avatar>
```
4. bun dev
5. Got TypeError: handleLoadingStatusChange is not a function

### What is the expected behavior?

Render component

### What do you see instead?

TypeError: handleLoadingStatusChange is not a function

### Additional information

Its work on Bun 1.2.4

**Comment by i-mark** [comment]
![Image](https://github.com/user-attachments/assets/eae444b0-f9ce-4f35-8835-bb4b4138cbb6)

**Comment by Torsten85** [comment]
experiencing the same for radix-ui 

<img width="953" alt="Image" src="https://github.com/user-attachments/assets/c212d000-cf4b-4fa4-867f-f5ab8894e777" />

**Comment by paperclover** [comment]
i think im missing something very obvious because both of these are not reproducing on my machine. can either of you share a full project zip or repository? does the error happen immediatly or is there a certain way to interact with it to cause this?

**Comment by i-mark** [comment]
> can either of you share a full project zip or repository? does the error happen immediatly or is there a certain way to interact with it to cause this?

No problem @paperclover. Full repo here:

[bun-radix-bug.zip](https://github.com/user-attachments/files/19219830/bun-radix-bug.zip)

Just run `bun dev` and open link in browser. It will break right away.

I download Bun 1.2.4, unzip and run:

`~/Downloads/bun-darwin-aarch64/bun --hot src/index.tsx`

In this case, there will be no problem.

PS
It worked 2 days ago in Bun 1.2.5-canary until stable release.

**Comment by paperclover** [comment]
will be fixed in #18109
