### ISSUE TITLE
Cannot build bun since meta.trait is removed in zig stg

### ISSUE THREAD

**Issue by bonyuta0204** [oven-sh/bun#7313]
### What version of Bun is running?

1.0.8

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

- zig version: 0.12.0-dev.1718+3acb0e30a
- step to reproduce
  - run `bun setup`  

### What is the expected behavior?

the compile should be succded

### What do you see instead?

bun cannot be succesfully built with zig 0.12.0-dev.1718+3acb0e30a.

This error occurs in many files.
```
src/bun.js/base.zig:86:35: error: root struct of file 'meta' has no member named 'trait'
            if (comptime std.meta.trait.isNumber(Type)) {
```

### Additional information

It appears that `meta.trait` is removed from zig stg in https://github.com/ziglang/zig/pull/18061.

**Comment by paperclover** [comment]
we do need to fix this, but bun right now must be build with `0.12.0-dev.1604+caae40c21`.

**Comment by wrongnull** [comment]
> we do need to fix this, but bun right now must be build with `0.12.0-dev.1604+caae40c21`.

There is currently third-party package that has exactly the same functions (see last comment from pull request conversation)

**Comment by paperclover** [comment]
i think we should just copy the functions we use into bun, and consider removing them if possible. there was a reason `std.meta.trait` was removed and i mostly agree with it's reasoning.
