### PR TITLE
install: fix the variable name that broke the Rust build on main

### PR DESCRIPTION
**Pull request by robobun**
### What does this PR do?

Fixes the Rust build on main. `cargo check -p bun_install` fails with:

```
error[E0425]: cannot find value `IS_PENDING_PACKAGE_INSTALL` in this scope
  --> src/install/PackageInstaller.rs:1359
```

The cause is a merge race with no textual conflict. #39816 (56c4e3d51a) added a call that uses the const generic `IS_PENDING_PACKAGE_INSTALL`. #39585 (c6a05c1014) had already replaced that const generic with the `is_pending_package_install` runtime parameter. Each PR compiled on its own branch. The combination does not.

The fix renames the one reference to the parameter name. The semantics match the other call sites in the same function (lines 1262 and 1478 use `!is_pending_package_install`).

### How did you verify your code works?

- `cargo check -p bun_install` fails on main and passes with this change.
- A full debug build (`bun bd`) passes with this change applied on top of main.

This PR adds no test files. The defect is that main does not compile, so no test file can express it: every test fails before the fix because nothing builds. #39816 already added behavior coverage for this code path (test/cli/install/bun-install-patch.test.ts, the "patchedDependencies declared by a dependency" block), and it runs again once this compiles.

### CODE REVIEW

**Comment by robobun** [comment]
I reached the same one line fix from a separate report of this build failure, so I will not open a second PR. One correction for the body: the const generic was replaced by #39770 (3d3016e329, "Trim ~2 MB from the release binary"), not by #39585. `git grep IS_PENDING_PACKAGE_INSTALL` finds 25 uses in `PackageInstaller.rs` at 3d3016e329^ and none at 3d3016e329. #39585 only removed one dead function that used the name.

If a test is wanted with this change, branch [`farm/5ea15413/fix-package-installer-build`](https://github.com/oven-sh/bun/compare/main...farm/5ea15413/fix-package-installer-build) (de1b8e1355) has the same fix plus one test in `test/cli/install/bun-install-patch.test.ts`. It installs a patched package into the root `node_modules` and into a nested one with the hoisted linker from the local registry, with a cold and a warm cache. With the fix, all 32 tests in that file pass under `bun bd test`.
