### ISSUE TITLE
Regression in 1.3 coming from 1.2.23: Cannot find module ... imported from ...

### ISSUE THREAD

**Issue by xriter** [oven-sh/bun#25927]
### What version of Bun is running?

1.3.5

### What platform is your computer?

Darwin 24.6.0 arm64 arm

### What steps can reproduce the bug?

I have docker file that builds an Astro site.
It used to have `FROM oven/bun:1.2.23`, and built fine.

After 1.3.x came out, I tried to upgrade (`FROM oven/bun:1.3.(I-forgot)`), but the build failed. A couple weeks later, after a new release, it still failed. Today I tried again with 1.3.5, and it still fails. 

Here is an excerpt from the build logs containing the error:

```
1.778 2026-01-09T14:50:07.870Z vite:resolve 2.88ms p-limit -> null
1.778 2026-01-09T14:50:07.870Z vite:resolve 2.88ms zod -> null
1.780 2026-01-09T14:50:07.872Z vite:import-analysis 7.98ms [15 imports rewritten] node_modules/astro/dist/content/runtime.js
1.780 2026-01-09T14:50:07.872Z vite:transform 11.01ms /node_modules/astro/dist/content/runtime.js
1.795 2026-01-09T14:50:07.887Z astro:vite Error when evaluating SSR module /app/src/content/config.ts: Cannot find module 'html-escaper' imported from '/app/node_modules/astro/dist/content/runtime.js'
1.795       at fetchModule (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js:46842:23)
1.795       at fetchModule (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js:46815:28)
1.795       at <anonymous> (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js:39002:28)
1.795       at handleInvoke (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js:38988:31)
1.795       at <anonymous> (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js:39075:25)
1.795       at listenerForInvokeHandler (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js:39067:41)
1.795       at emit (node:events:98:22)
1.795       at send (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js:25190:40)
1.795       at invoke (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/module-runner.js:621:34)
1.795       at invoke (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/module-runner.js:612:18)
1.798 2026-01-09T14:50:07.890Z astro:telemetry {
1.798   context: {
1.798     isGit: false,
1.798     anonymousProjectId: undefined,
1.798     packageManager: 'bun',
1.798     packageManagerVersion: '1.3.5',
1.798     anonymousId: 'b535799749ce52723e5995acc4d74abc2a1fd561f1bf972d2612a2c8148ee535',
1.798     anonymousSessionId: '656335ae7e89202acd4a24bf50188b7362fa2716769a4a592fd22386831a4e2d'
1.798   },
1.798   meta: {
1.798     nodeVersion: '24.3.0',
1.798     viteVersion: '6.4.1',
1.798     astroVersion: '5.16.6',
1.798     systemPlatform: 'linux',
1.798     systemRelease: '6.10.14-linuxkit',
1.798     systemArchitecture: 'arm64',
1.798     cpuCount: 10,
1.798     cpuModel: 'unknown',
1.798     cpuSpeed: 0,
1.798     memoryInMb: 7837,
1.798     isDocker: false,
1.798     isTTY: undefined,
1.798     isWSL: false,
1.798     isCI: false,
1.798     ciName: null
1.798   }
1.798 }
1.798 2026-01-09T14:50:07.890Z astro:telemetry [
1.798   {
1.798     "eventName": "ASTRO_CLI_ERROR",
1.798     "payload": {
1.798       "name": "GenerateContentTypesError",
1.798       "cliCommand": "build",
1.798       "isFatal": true,
1.798       "anonymousMessageHint": "`astro sync` command failed to generate content collection types: ERROR_MESSAGE"
1.798     }
1.798   }
1.798 ]
1.799 [GenerateContentTypesError] `astro sync` command failed to generate content collection types: Cannot find module 'html-escaper' imported from '/app/node_modules/astro/dist/content/runtime.js'
1.799   Hint:
1.799     This error is often caused by a syntax error inside your content, or your content configuration file. Check your src/content/config.ts file for typos.
1.799   Error reference:
1.799     https://docs.astro.build/en/reference/errors/generate-content-types-error/
1.799   Stack trace:
1.799     at syncContentCollections (/app/node_modules/.bun/astro@5.16.6+5f587ea88fefdebb/node_modules/astro/dist/core/sync/index.js:238:15)
1.799     at async setup (/app/node_modules/.bun/astro@5.16.6+5f587ea88fefdebb/node_modules/astro/dist/core/build/index.js:100:11)
1.799     at async build (/app/node_modules/.bun/astro@5.16.6+5f587ea88fefdebb/node_modules/astro/dist/core/build/index.js:45:17)
1.799     at async runCommand (/app/node_modules/.bun/astro@5.16.6+5f587ea88fefdebb/node_modules/astro/dist/cli/index.js:210:13)
1.799     at processTicksAndRejections (native:7:39)
1.799   Caused by:
1.799   Cannot find module 'html-escaper' imported from '/app/node_modules/astro/dist/content/runtime.js'
1.799     at fetchModule (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js:46842:23)
1.799     at <anonymous> (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js:39002:28)
1.799     at <anonymous> (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js:39075:25)
1.799     at emit (node:events:98:22)
1.799     at invoke (/app/node_modules/.bun/vite@6.4.1+37300340cafcd3c6/node_modules/vite/dist/node/module-runner.js:621:34)
1.805 error: script "build" exited with code 1
------
Dockerfile:29
--------------------
  27 |     
  28 |     # Build astro frontend
  29 | >>> RUN bun run build --verbose
```

Is this an Astro problem? A Bun issue? It's just interesting that it worked in 1.2.x
